### ISSUE TITLE
No reconnection after network change

### ISSUE THREAD

**Issue by kkeijzer** [librespot-org/librespot-java#103]
**Describe the bug**
Librespot-java does not reconnect after a network change.

**To Reproduce**
Many things can be done. For instance, when I connect to my VPN, or when I suspend and resume my machine, Librespot-java essentially crashes and has to be restarted manually.

**Expected behavior**
When a timeout is detected, reconnection should be attempted. So connecting to a VPN should make it re-login from the new IP, resuming from suspend should make it reconnect using a new TCP socket, and so on. I am unsure how long the Spotify servers wait until they understand that a client has timed out and left though, so reconnecting from a new socket may cause a device name collission.

**Screenshots/Stracktraces/Logs**
```
2019-06-20 20:22:41 FATAL CdnManager:312 - Failed requesting chunk from network, index: 64, retried: false
java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:232)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:286)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
	at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:238)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at xyz.gianlu.librespot.cdn.CdnManager$Streamer.request(CdnManager.java:327)
	at xyz.gianlu.librespot.cdn.CdnManager$Streamer.request(CdnManager.java:320)
	at xyz.gianlu.librespot.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:309)
	at xyz.gianlu.librespot.cdn.CdnManager$Streamer.access$1500(CdnManager.java:197)
	at xyz.gianlu.librespot.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:373)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.SocketException: Socket closed
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:183)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 28 more
```

**Version/Commit**
`1cc24bb906f5d53c48c2016981b269be84a1dd9a`

**Comment by devgianlu** [comment]
In this moment, reconnection handling is a bit wonky as I've never had a proper way to test. 

The VPN thing seems quite a good test case. I'll get around it not before I've completed the implementation of the new API as it introduces pretty big changes.

**Comment by tylkie** [comment]
I have a similar problem where my gateway sometimes restarts the internet network interface without explicitly closing associated intranet sockets.

My guess is that on the server-side (namely spotify), the connection times out and is being closed by spotify itself. Librespot does not receive any more packets but does not detect disconnection due to the socket timeout being disabled after successful connection. This causes the socket class not to throw any exception while blocking the thread with the read attempt.

I got around this problem as suggested by Kevin. The receiver thread continuously saves the timestamp of the last packet received. If the last packet is older than three minutes, we force the thread to reconnect. For this we need the thread to be non-blocking, which I solved by polling the socket for new bytes before reading.

I'll just dump the outline of my suggestion here until I am involved enough to fork...

```
private class Receiver implements Runnable {

  private volatile boolean shouldStop = false;
  private volatile long lastPacket = System.currentTimeMillis();

  private Receiver() { }
  void stop() { shouldStop = true; }

  @Override
  public void run() {
    while (!shouldStop) {
      Packet packet;
      Packet.Type cmd;
      try {
        boolean check = conn.socket.isConnected();
        int count = conn.in.available();
        if (check && count > 0) {
          packet = cipherPair.receiveEncoded(conn.in);
          cmd = Packet.Type.parse(packet.cmd);
          if (cmd == null) {
            continue;
          }
        } else {
          if (System.currentTimeMillis() - lastPacket > 180000 && !shouldStop) {
            LOGGER.info(String.format("No payload received for three minutes... reconnecting..."));
            reconnect();
          }
          Thread.sleep(1000);
          continue;
        }
      } catch (IOException | GeneralSecurityException | InterruptedException ex) {
        // Handle exception...
      }
      lastPacket = System.currentTimeMillis();
      switch (cmd) {
        // Handle command....
      }
    }
  }

}
```

**Comment by devgianlu** [comment]
The idea is pretty nice, a similar approach would be to detect when the last ping has been received as it happens every two minutes and the payload itself is a timestamp.

When a ping is received, schedule to reconnect in 2 minutes (+5 seconds) if another ping isn't received in time. If it has been received, abort and schedule again. 

This will surely work, but right now there are some problems with the actual reconnection process which isn't very reliable as I've never had a proper way to test it.

**Comment by tylkie** [comment]
That would be a more elegant approach indeed. Using a sleeping thread induces a one second delay for the first command after being idle... and nobody likes sleeping threads anyway.

For my situation the above change did the trick for now, as the socket acutally never times out and no exceptions are thrown. The device reappears on spotify connect where it did not before the change. Just tested that.

On the other hand, if the socket throws an exception as for Kevin, it is not that trivial. A lot of working threads seem to terminate along the exceptions thrown. My best bet for a test scenario would be to pull the network plug, dropping incoming packets or hardcoding a socket timeout exception.

**Comment by devgianlu** [comment]
I've implemented this new reconnection mechanism as part of #105. That does not include a fix for this particular issue reported by @kkeijzer as it won't (reliably) keep the player state and such.

**Comment by kkeijzer** [comment]
I think it would already help if `librespot-java` would just exit if a timeout is detected, and not sit idle without any error code.

I have a little music streamer single board computer connected to my DAC, running Debian buster, `librespot-java` and some other software like `cmus`, which I use for Shoutcast and such.

For `librespot-java`, I have created a systemd user unit:

```
kevin@lithium:~$ cat ~/.config/systemd/user/librespot-java.service

[Unit]
Description=Spotify Connect client
After=network.target

[Service]
Type=simple
WorkingDirectory=/home/kevin/.local/opt/librespot-java
ExecStart=/usr/bin/java -jar /home/kevin/.local/opt/librespot-java/librespot-core-jar-with-dependencies.jar
Restart=on-failure
SuccessExitStatus=143

[Install]
WantedBy=default.target
```

The `Restart` option would just respawn `librespot-java` in case of failure. However, the Java process should of course communicate that to the init system, which does not happen now.

But combined with systemd, I don't think all the restart logic really has to be in `librespot-java`.

**Comment by devgianlu** [comment]
That's true, just exiting the program might be better in some cases. Different exit codes could be used for different errors and the thing would turn out pretty well.

BUT, I'd really like to have a perfect system that can recover from any situation, just like the original client does.

**Comment by devgianlu** [comment]
https://github.com/librespot-org/librespot-java/pull/120#issuecomment-519686481

**Comment by devgianlu** [comment]
Today I witnessed a successfull reconnection, I'm quite impressed:
```
2019-08-11 16:14:28 TRACE CdnManager:261 - Chunk 24/31 completed, cdn: audio4-fa.scdn.co, cached: true, stream: {fileId: 2F74AE017826101CEA1E2083CEADEA2EE413550F}
2019-08-11 16:14:34 TRACE CdnManager:261 - Chunk 25/31 completed, cdn: audio4-fa.scdn.co, cached: true, stream: {fileId: 2F74AE017826101CEA1E2083CEADEA2EE413550F}
2019-08-11 16:14:41 TRACE CdnManager:261 - Chunk 26/31 completed, cdn: audio4-fa.scdn.co, cached: true, stream: {fileId: 2F74AE017826101CEA1E2083CEADEA2EE413550F}
2019-08-11 16:14:47 TRACE CdnManager:261 - Chunk 27/31 completed, cdn: audio4-fa.scdn.co, cached: true, stream: {fileId: 2F74AE017826101CEA1E2083CEADEA2EE413550F}
2019-08-11 16:14:54 TRACE CdnManager:261 - Chunk 28/31 completed, cdn: audio4-fa.scdn.co, cached: true, stream: {fileId: 2F74AE017826101CEA1E2083CEADEA2EE413550F}
2019-08-11 16:14:55 FATAL Session:747 - Failed reading packet!
java.io.EOFException
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:202)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:170)
	at xyz.gianlu.librespot.crypto.CipherPair.receiveEncoded(CipherPair.java:60)
	at xyz.gianlu.librespot.core.Session$Receiver.run(Session.java:739)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019-08-11 16:14:56 INFO  Session:255 - Connected successfully!
2019-08-11 16:14:57 INFO  Session:510 - Re-authenticated as ********!
2019-08-11 16:14:57 TRACE Session:766 - Handled Ping {payload: 5D5022E1}
2019-08-11 16:14:57 INFO  Session:803 - Skipping SecretBlock
2019-08-11 16:14:57 INFO  Session:783 - Received LicenseVersion: 1, 1.0.1-IT
2019-08-11 16:14:57 INFO  Session:776 - Received CountryCode: IT
2019-08-11 16:14:57 INFO  Session:803 - Skipping ProductInfo
2019-08-11 16:14:57 INFO  Session:803 - Skipping LegacyWelcome
2019-08-11 16:14:57 INFO  Session:803 - Skipping UnknownData_AllZeros
2019-08-11 16:14:58 DEBUG Session:786 - Received 0x10: XXXXXXXXXXXXXXXXXXXXXXXXXX
2019-08-11 16:14:58 TRACE Session:772 - Handled PongAck {payload: 5D5022E1}
2019-08-11 16:14:58 INFO  Session:742 - Skipping unknown command {cmd: 0x75, payload: 000000}
```

**Comment by devgianlu** [comment]
I've refactored the reconnection logic (again), should be better. See #134
