### ISSUE TITLE
One time error when fresh installed

### ISSUE THREAD

**Issue by spocon** [librespot-org/librespot-java#117]
**Describe the bug**
When i installed spocon the first time on a fresh system i found this exception in the logs. After restarting the service , it disappears
```
sudo service spocon restart 
```

Can we fix that programmatical?

```
Jul 22 18:33:19 raspberrypi java[3646]: 2019-07-22 18:33:19 INFO  ZeroconfServer:312 - Accepted new user. {deviceId: 89r0unagc4zn6tnj12z8n2zmy2e8ccyx9r7r1i7w}
Jul 22 18:33:21 raspberrypi java[3646]: 2019-07-22 18:33:21 INFO  Session:244 - Connected successfully!
Jul 22 18:33:21 raspberrypi java[3646]: 2019-07-22 18:33:21 DEBUG TimeProvider:20 - Corrected time offset, delta: 0s
Jul 22 18:33:21 raspberrypi java[3646]: 2019-07-22 18:33:21 TRACE Session:745 - Handled Ping {payload: 5D35E551}
Jul 22 18:33:21 raspberrypi java[3646]: 2019-07-22 18:33:21 INFO  Session:782 - Skipping SecretBlock
Jul 22 18:33:21 raspberrypi java[3646]: 2019-07-22 18:33:21 INFO  Session:762 - Received LicenseVersion: 1, 1.0.1-SE
Jul 22 18:33:21 raspberrypi java[3646]: 2019-07-22 18:33:21 INFO  Session:755 - Received CountryCode: SE
Jul 22 18:33:21 raspberrypi java[3646]: 2019-07-22 18:33:21 INFO  Session:782 - Skipping ProductInfo
Jul 22 18:33:21 raspberrypi java[3646]: 2019-07-22 18:33:21 INFO  Session:782 - Skipping LegacyWelcome
Jul 22 18:33:21 raspberrypi java[3646]: 2019-07-22 18:33:21 INFO  Session:782 - Skipping UnknownData_AllZeros
Jul 22 18:33:21 raspberrypi java[3646]: 2019-07-22 18:33:21 DEBUG Session:765 - Received 0x10: A853454542A7AB010C26378E040C2A9932A7146C
Jul 22 18:33:21 raspberrypi java[3646]: 2019-07-22 18:33:21 TRACE Session:751 - Handled PongAck {payload: 5D35E551}
Jul 22 18:33:21 raspberrypi java[3646]: 2019-07-22 18:33:21 INFO  Session:721 - Skipping unknown command {cmd: 0x75, payload: 000000}
Jul 22 18:33:24 raspberrypi java[3646]: 2019-07-22 18:33:24 DEBUG TokenProvider:37 - Token expired or not suitable, requesting again. {scope: playlist-read, token: null}
Jul 22 18:33:24 raspberrypi java[3646]: 2019-07-22 18:33:24 TRACE MercuryClient:131 - Send Mercury request, seq: 1, uri: hm://keymaster/token/authenticated?scope=playlist-read&client_id=XXXXXXXXXX
Jul 22 18:33:24 raspberrypi java[3646]: 2019-07-22 18:33:24 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 1, flags: 1, parts: 2
Jul 22 18:33:27 raspberrypi java[3646]: 2019-07-22 18:33:27 INFO  Session:260 - Authenticated as XXXXXXXXX!
Jul 22 18:33:28 raspberrypi java[3646]: 2019-07-22 18:33:28 DEBUG DealerClient:54 - Dealer connected! {host: guc-dealer.spotify.com}
Jul 22 18:33:30 raspberrypi java[3646]: 2019-07-22 18:33:30 INFO  DeviceStateHandler:139 - Updated state. {reason: NEW_DEVICE}
Jul 22 18:33:30 raspberrypi java[3646]: 2019-07-22 18:33:30 INFO  StateWrapper:205 - Notified new device (us)!
Jul 22 18:33:30 raspberrypi java[3646]: 2019-07-22 18:33:30 DEBUG Player:112 - Received command: Transfer
Jul 22 18:33:30 raspberrypi java[3646]: 2019-07-22 18:33:30 DEBUG Player:69 - Loading context (transfer), uri: spotify:station:user:XXXXXXXXX:playlist:1IFOsfOQmojufND8VlHGVp
Jul 22 18:33:31 raspberrypi java[3646]: 2019-07-22 18:33:31 INFO  DeviceStateHandler:139 - Updated state. {reason: PLAYER_STATE_CHANGED}
Jul 22 18:33:32 raspberrypi java[3646]: 2019-07-22 18:33:32 INFO  DeviceStateHandler:139 - Updated state. {reason: PLAYER_STATE_CHANGED}
Jul 22 18:33:32 raspberrypi java[3646]: 2019-07-22 18:33:32 WARN  DeviceStateHandler:124 - Message left unhandled! {uri: hm://connect-state/v1/cluster, rawPayloads: [CsuyAwjY3Z/UwS0SKDg5cjB1bmFnYzR
Jul 22 18:33:32 raspberrypi java[3646]: IXCgV0aXRsZRIOQWxsIEkgV2FubmEgRG8iSgoQaW1hZ2VfeGxhcmdlX3VybBI2c3BvdGlmeTppbWFnZTo3ODg0ODExMjI5YmFjMTg1MTRjMTY2YjE1ZjFmZTNlOGFjNGFlYzYxIhIKCGR1cmF0aW9uEgYxOTQ
Jul 22 18:33:32 raspberrypi java[3646]: 2019-07-22 18:33:32 WARN  DeviceStateHandler:124 - Message left unhandled! {uri: hm://connect-state/v1/cluster, rawPayloads: [CsuyAwjR35/UwS0SKDg5cjB1bmFnYzR
Jul 22 18:33:32 raspberrypi java[3646]: IXCgV0aXRsZRIOQWxsIEkgV2FubmEgRG8iSgoQaW1hZ2VfeGxhcmdlX3VybBI2c3BvdGlmeTppbWFnZTo3ODg0ODExMjI5YmFjMTg1MTRjMTY2YjE1ZjFmZTNlOGFjNGFlYzYxIhIKCGR1cmF0aW9uEgYxOTQ
Jul 22 18:33:32 raspberrypi java[3646]: 2019-07-22 18:33:32 DEBUG CdnManager:93 - Fetched CDN url for A76349FE3D37AA32B37776E751490A5758C6120F: http://audio4-fa.scdn.co/audio/a76349fe3d37aa32b37776
Jul 22 18:33:33 raspberrypi java[3646]: 2019-07-22 18:33:33 TRACE CdnManager:270 - Chunk 0/33 completed, cdn: audio4-fa.scdn.co, cached: false, stream: {fileId: A76349FE3D37AA32B37776E751490A5758C6
Jul 22 18:33:33 raspberrypi java[3646]: 2019-07-22 18:33:33 TRACE CdnManager:270 - Chunk 0/33 completed, cdn: audio4-fa.scdn.co, cached: true, stream: {fileId: A76349FE3D37AA32B37776E751490A5758C61
Jul 22 18:33:33 raspberrypi java[3646]: 2019-07-22 18:33:33 TRACE NormalizationData:29 - Loaded normalization data, track_gain: -9,64, track_peak: 1,29, album_gain: -9,64, album_peak: 1,29
Jul 22 18:33:33 raspberrypi java[3646]: 2019-07-22 18:33:33 INFO  TrackHandler:80 - Loaded track, name: 'Tears In Your Eyes', artists: 'Nora En Pure', gid: 9527D090357A40F292752C8E18E4D4FF
Jul 22 18:33:33 raspberrypi java[3646]: 2019-07-22 18:33:33 TRACE CdnManager:270 - Chunk 1/33 completed, cdn: audio4-fa.scdn.co, cached: false, stream: {fileId: A76349FE3D37AA32B37776E751490A5758C6
Jul 22 18:33:33 raspberrypi java[3646]: 2019-07-22 18:33:33 TRACE CdnManager:270 - Chunk 3/33 completed, cdn: audio4-fa.scdn.co, cached: false, stream: {fileId: A76349FE3D37AA32B37776E751490A5758C6
Jul 22 18:33:33 raspberrypi java[3646]: 2019-07-22 18:33:33 TRACE CdnManager:270 - Chunk 2/33 completed, cdn: audio4-fa.scdn.co, cached: false, stream: {fileId: A76349FE3D37AA32B37776E751490A5758C6
Jul 22 18:33:34 raspberrypi java[3646]: 2019-07-22 18:33:34 FATAL Player:217 - Failed loading track, gid: 9527D090357A40F292752C8E18E4D4FF
Jul 22 18:33:34 raspberrypi java[3646]: xyz.gianlu.librespot.player.LinesHolder$MixerException: Couldn't find a suitable mixer, openLine: interface SourceDataLine supporting format PCM_SIGNED 44100
Jul 22 18:33:34 raspberrypi java[3646]:         at xyz.gianlu.librespot.player.LinesHolder.findSupportingMixersFor(LinesHolder.java:32)
Jul 22 18:33:34 raspberrypi java[3646]:         at xyz.gianlu.librespot.player.LinesHolder.getLineFor(LinesHolder.java:64)
Jul 22 18:33:34 raspberrypi java[3646]:         at xyz.gianlu.librespot.player.codecs.VorbisCodec.initializeSound(VorbisCodec.java:123)
Jul 22 18:33:34 raspberrypi java[3646]:         at xyz.gianlu.librespot.player.codecs.VorbisCodec.<init>(VorbisCodec.java:51)
Jul 22 18:33:34 raspberrypi java[3646]:         at xyz.gianlu.librespot.player.PlayerRunner.<init>(PlayerRunner.java:27)
Jul 22 18:33:34 raspberrypi java[3646]:         at xyz.gianlu.librespot.player.TrackHandler.createRunner(TrackHandler.java:55)
Jul 22 18:33:34 raspberrypi java[3646]:         at xyz.gianlu.librespot.player.TrackHandler.loadRunner(TrackHandler.java:88)
Jul 22 18:33:34 raspberrypi java[3646]:         at xyz.gianlu.librespot.player.TrackHandler.load(TrackHandler.java:82)
Jul 22 18:33:34 raspberrypi java[3646]:         at xyz.gianlu.librespot.player.TrackHandler.access$600(TrackHandler.java:29)
Jul 22 18:33:34 raspberrypi java[3646]:         at xyz.gianlu.librespot.player.TrackHandler$Looper.run(TrackHandler.java:232)
Jul 22 18:33:34 raspberrypi java[3646]:         at java.base/java.lang.Thread.run(Thread.java:834)
```

**Version/Commit**
branch new-spotify-api

**Comment by devgianlu** [comment]
Could it be that the service was initially started with a lower permission level so that it couldn't find the mixer?

**Comment by spocon** [comment]
I can check that

**Comment by spocon** [comment]
ok , i know why this happens now. during the install project im creating a user and add him to the group "audio" . but in order to get access to the audio group you usually refresh the user permissions bei login out and login in again. i have to find a way to fix this.

Closing this because its not a java problem
