### ISSUE TITLE
ClassCastException when attempting to play a track

### ISSUE THREAD

**Issue by jscholes** [librespot-org/librespot-java#122]
**Describe the bug**
An exception is thrown inside the track-handler thread when attempting to play any track (just after track data loading starts).  The issue occurs regardless of whether useCdn is set to true or false inside the player.tracks section of config.toml, and with all values of preferredAudioQuality.

    Exception in thread "track-handler-580907333" java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float

**To Reproduce**
After a session has successfully been established by librespot-java, switch playback to the newly created Connect device from another Spotify app.  Attempt to play any track.

**Expected behavior**
The track begins to play (or the available mixers are logged).

**Screenshots/Stracktraces/Logs**

    2019-08-11 22:13:28 TRACE AudioFileStreaming:120 - Track size: 10484928
    2019-08-11 22:13:28 TRACE AudioFileStreaming:122 - Track has 80 chunks.
    2019-08-11 22:13:28 TRACE AudioFileStreaming:146 - Chunk 0/80 completed, cached: false, fileId: 4F257E9B417EB222AB722344DA9064F316D48908
    2019-08-11 22:13:28 TRACE NormalizationData:29 - Loaded normalization data, track_gain: -5.50, track_peak: 1.01, album_gain: -7.15, album_peak: 1.05
    2019-08-11 22:13:28 INFO  TrackHandler:80 - Loaded track, name: 'January Man', artists: 'Christy Moore', gid: 2A6916F5C45D47E7AA3A1B1F2C83721B
    Exception in thread "track-handler-580907333" java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float
            at xyz.gianlu.librespot.FileConfiguration.normalisationPregain(FileConfiguration.java:154)
            at xyz.gianlu.librespot.player.NormalizationData.getFactor(NormalizationData.java:49)
            at xyz.gianlu.librespot.player.codecs.Codec.<init>(Codec.java:38)
            at xyz.gianlu.librespot.player.codecs.VorbisCodec.<init>(VorbisCodec.java:44)
            at xyz.gianlu.librespot.player.PlayerRunner.<init>(PlayerRunner.java:27)
            at xyz.gianlu.librespot.player.TrackHandler.createRunner(TrackHandler.java:55)
            at xyz.gianlu.librespot.player.TrackHandler.loadRunner(TrackHandler.java:88)
            at xyz.gianlu.librespot.player.TrackHandler.load(TrackHandler.java:82)
            at xyz.gianlu.librespot.player.TrackHandler.access$600(TrackHandler.java:29)
            at xyz.gianlu.librespot.player.TrackHandler$Looper.run(TrackHandler.java:230)
            at java.lang.Thread.run(Unknown Source)
    2019-08-11 22:13:28 TRACE AudioFileStreaming:146 - Chunk 2/80 completed, cached: false, fileId: 4F257E9B417EB222AB722344DA9064F316D48908
    2019-08-11 22:13:28 TRACE AudioFileStreaming:146 - Chunk 1/80 completed, cached: false, fileId: 4F257E9B417EB222AB722344DA9064F316D48908
    2019-08-11 22:13:28 TRACE AudioFileStreaming:146 - Chunk 3/80 completed, cached: false, fileId: 4F257E9B417EB222AB722344DA9064F316D48908

**Version/Commit**
Release 0.6.1 from GitHub
Windows 10
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)

**Comment by devgianlu** [comment]
This has already been fixed with #114. I should probably make a new release.

**Comment by jscholes** [comment]
Oh, awesome!  Thanks.
