### ISSUE TITLE
How do I load this page?!

### ISSUE THREAD

**Issue by leafy7382** [librespot-org/librespot-java#130]
Starting up and ran into this error in the log

```
2019-09-11 12:12:38 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 5, flags: 1, parts: 2
Exception in thread "handle-packet-25709859" java.lang.IllegalStateException: How do I load this page?!
        at xyz.gianlu.librespot.player.StateWrapper$TracksKeeper.updateWithPage(StateWrapper.java:494)
        at xyz.gianlu.librespot.player.StateWrapper$TracksKeeper.access$600(StateWrapper.java:402)
        at xyz.gianlu.librespot.player.StateWrapper$TracksKeeper$1.response(StateWrapper.java:510)
        at xyz.gianlu.librespot.player.StateWrapper$TracksKeeper$1.response(StateWrapper.java:504)
        at xyz.gianlu.librespot.mercury.MercuryClient.lambda$send$2(MercuryClient.java:96)
        at xyz.gianlu.librespot.mercury.MercuryClient.handle(MercuryClient.java:210)
        at xyz.gianlu.librespot.core.PacketsManager$Looper.lambda$run$0(PacketsManager.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by devgianlu** [comment]
Do you have the full log? Also, what were you trying to load and from where (application)?

**Comment by leafy7382** [comment]
I do, but the previous logs seems to be irrelevant to this error. Any settings to get more info?
This is starting up librespot-java and connect via the Android Spotify app, playing back this album https://open.spotify.com/album/4oqJ13EemIRGsK7u5JIJef?si=2uu_FQIMT3mFDGkfifGFnw
