### ISSUE TITLE
Session isn't authenticated!

### ISSUE THREAD

**Issue by leafy7382** [librespot-org/librespot-java#137]
Started instance (spotify-new-api)  and tried connecting via Mac client 1.1.15.448.g00fba0e3, instance crashed with following log:

```
2019-09-17 12:26:28 INFO  Utils:134 - Successfully removed cryptography restrictions.
2019-09-17 12:26:28 INFO  ApResolver:68 - Loaded aps into pool: {accesspoint=[gae2-accesspoint-a-z0gc.ap.spotify.com:4070, gae2-accesspoint-a-27sc.ap.spotify.com:443, gae2-accesspoint-a-kkxz.ap.spotify.com:80, gae2-accesspoint-a-q9mn.ap.spotify.com:4070, gae2-accesspoint-a-03sg.ap.spotify.com:443, gae2-accesspoint-a-nw0s.ap.spotify.com:80, guc3-accesspoint-a-xqkr.ap.spotify.com:4070, guc3-accesspoint-a-dwcs.ap.spotify.com:443, guc3-accesspoint-a-hbt3.ap.spotify.com:80], dealer=[gae-dealer.spotify.com:443, guc-dealer.spotify.com:443, gew-dealer.spotify.com:443], spclient=[gae-spclient.spotify.com:443, guc-spclient.spotify.com:443, gew-spclient.spotify.com:443]}
2019-09-17 12:26:28 INFO  ZeroconfServer:338 - Zeroconf HTTP server started successfully on port 12292!
2019-09-17 12:26:28 TRACE ZeroconfServer:184 - Adding addresses of wlan0 {displayName: wlan0, mac: B827EB526B2D}
2019-09-17 12:26:28 DEBUG ZeroconfServer:111 - Registering service on [/192.168.86.20]
2019-09-17 12:26:28 INFO  ZeroconfServer:130 - SpotifyConnect service registered successfully!
2019-09-17 12:26:30 TRACE ZeroconfServer:382 - Handling request: GET / HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/111500448 OSX/0 (MacBookPro11,2), Host=192.168.86.20, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
2019-09-17 12:26:30 WARN  ZeroconfServer:431 - Couldn't handle request: GET / HTTP/1.1
tail: unrecognized file system type 0x794c7630 for 'info.log'. please report this to bug-coreutils@gnu.org. reverting to polling
2019-09-17 12:26:39 TRACE ZeroconfServer:382 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/111500448 OSX/0 (MacBookPro11,2), Host=192.168.86.20, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
2019-09-17 12:26:41 TRACE ZeroconfServer:382 - Handling request: POST / HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/111500448 OSX/0 (MacBookPro11,2), Host=192.168.86.20, Accept-Encoding=gzip, Content-Length=700, Content-Type=application/x-www-form-urlencoded}
2019-09-17 12:26:42 DEBUG TimeProvider:70 - Loaded time offset from NTP: 19ms
2019-09-17 12:26:42 INFO  Session:104 - Created new session! {deviceId: ixhu4ppb6mx1etopiw40rfsabjo4yzz043d0qye8, ap: guc3-accesspoint-a-hbt3.ap.spotify.com/35.190.245.60}
2019-09-17 12:26:42 INFO  ZeroconfServer:312 - Accepted new user from leafy-macbookpro2. {deviceId: ixhu4ppb6mx1etopiw40rfsabjo4yzz043d0qye8}
2019-09-17 12:26:43 INFO  Session:252 - Connected successfully!
2019-09-17 12:26:44 TRACE Session:781 - Handled Ping {payload: 5D80D104}
2019-09-17 12:26:44 INFO  Session:818 - Skipping SecretBlock
2019-09-17 12:26:44 INFO  Session:798 - Received LicenseVersion: 1, 1.0.0-TW
2019-09-17 12:26:44 INFO  Session:791 - Received CountryCode: TW
2019-09-17 12:26:44 INFO  Session:818 - Skipping ProductInfo
2019-09-17 12:26:44 INFO  Session:818 - Skipping LegacyWelcome
2019-09-17 12:26:44 DEBUG TokenProvider:37 - Token expired or not suitable, requesting again. {scope: playlist-read, token: null}
2019-09-17 12:26:44 TRACE MercuryClient:131 - Send Mercury request, seq: 1, uri: hm://keymaster/token/authenticated?scope=playlist-read&client_id=65b708073fc0480ea92a077233ca87bd&device_id=ixhu4ppb6mx1etopiw40rfsabjo4yzz043d0qye8, method: GET
2019-09-17 12:26:44 INFO  Session:818 - Skipping UnknownData_AllZeros
2019-09-17 12:26:44 DEBUG Session:801 - Received 0x10: D009F18A9B55C75825D37A33E81A3ABB17EAC12E
2019-09-17 12:26:44 TRACE Session:787 - Handled PongAck {payload: 5D80D104}
2019-09-17 12:26:45 INFO  Session:757 - Skipping unknown command {cmd: 0x75, payload: 000000}
2019-09-17 12:26:45 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 1, flags: 1, parts: 2
2019-09-17 12:26:45 DEBUG DealerClient:57 - Dealer connected! {host: gae-dealer.spotify.com}
2019-09-17 12:26:45 INFO  LineHelper:61 - Available mixers: 'ALSA [default]', 'ALSA [plughw:0,0]', 'ALSA [plughw:0,1]', 'sndrpihifiberry [plughw:1,0]'
Exception in thread "dealer-looper" java.lang.IllegalStateException: Session isn't authenticated!
	at xyz.gianlu.librespot.core.Session.player(Session.java:455)
	at xyz.gianlu.librespot.connectstate.DeviceStateHandler.putState(DeviceStateHandler.java:191)
	at xyz.gianlu.librespot.connectstate.DeviceStateHandler.updateState(DeviceStateHandler.java:158)
	at xyz.gianlu.librespot.player.StateWrapper.ready(StateWrapper.java:266)
	at xyz.gianlu.librespot.connectstate.DeviceStateHandler.notifyReady(DeviceStateHandler.java:84)
	at xyz.gianlu.librespot.connectstate.DeviceStateHandler.onMessage(DeviceStateHandler.java:119)
	at xyz.gianlu.librespot.dealer.DealerClient.lambda$handleMessage$4(DealerClient.java:216)
	at xyz.gianlu.librespot.dealer.DealerClient$Looper.run(DealerClient.java:269)
	at java.lang.Thread.run(Thread.java:745)
2019-09-17 12:26:45 INFO  Session:277 - Authenticated as 11127544113!
```

**Comment by devgianlu** [comment]
I've pushed a possible fix, I did a couple of tests, but I am not sure this works perfectly. I'll let you close this issue when you feel like the issue is gone.

**Comment by leafy7382** [comment]
Tested 6f44c38e57fef868baedb92e6224ee4dd254bda2 and it went without issue.
