### ISSUE TITLE
Exception in thread "session-packet-receiver" java.nio.BufferUnderflowException

### ISSUE THREAD

**Issue by leafy7382** [librespot-org/librespot-java#141]
this is on the latest commit for new API

```
volumio@volumio:~$ cat info.log 
2019-10-04 12:23:51 INFO  Utils:138 - Successfully removed cryptography restrictions.
2019-10-04 12:23:52 INFO  ApResolver:68 - Loaded aps into pool: {accesspoint=[gae2-accesspoint-a-5l2c.ap.spotify.com:4070, gae2-accesspoint-a-h7bk.ap.spotify.com:443, gae2-accesspoint-a-hjn5.ap.spotify.com:80, gae2-accesspoint-a-p7cg.ap.spotify.com:4070, gae2-accesspoint-a-wns7.ap.spotify.com:443, gae2-accesspoint-a-h9b0.ap.spotify.com:80, guc3-accesspoint-a-tdp3.ap.spotify.com:4070, guc3-accesspoint-a-9f81.ap.spotify.com:443, gew1-accesspoint-a-6nxw.ap.spotify.com:80], dealer=[gae-dealer.spotify.com:443, gew-dealer.spotify.com:443, guc-dealer.spotify.com:443], spclient=[gae-spclient.spotify.com:443, guc-spclient.spotify.com:443, gew-spclient.spotify.com:443]}
2019-10-04 12:23:52 INFO  ZeroconfServer:338 - Zeroconf HTTP server started successfully on port 18541!
2019-10-04 12:23:52 TRACE ZeroconfServer:184 - Adding addresses of wlan0 {displayName: wlan0, mac: B827EB526B2D}
2019-10-04 12:23:52 DEBUG ZeroconfServer:111 - Registering service on [/192.168.86.20]
2019-10-04 12:23:52 INFO  ZeroconfServer:130 - SpotifyConnect service registered successfully!
2019-10-04 12:23:55 TRACE ZeroconfServer:382 - Handling request: GET / HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.25 Android/29 (Pixel 2), Host=192.168.86.20, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
2019-10-04 12:23:55 WARN  ZeroconfServer:431 - Couldn't handle request: GET / HTTP/1.1
2019-10-04 12:23:56 TRACE ZeroconfServer:382 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.25 Android/29 (Pixel 2), Host=192.168.86.20, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
2019-10-04 12:23:59 TRACE ZeroconfServer:382 - Handling request: POST / HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.25 Android/29 (Pixel 2), Host=192.168.86.20, Accept-Encoding=gzip, Content-Length=633, Content-Type=application/x-www-form-urlencoded}
2019-10-04 12:24:00 DEBUG TimeProvider:70 - Loaded time offset from NTP: 0ms
2019-10-04 12:24:01 INFO  Session:104 - Created new session! {deviceId: 9jx0tcn0uh9ik9wkx0tu6t3pk9du358pcdplijrl, ap: guc3-accesspoint-a-tdp3.ap.spotify.com/104.154.127.219} 
2019-10-04 12:24:01 INFO  ZeroconfServer:312 - Accepted new user from K0Mx0750. {deviceId: 9jx0tcn0uh9ik9wkx0tu6t3pk9du358pcdplijrl}
2019-10-04 12:24:02 INFO  Session:252 - Connected successfully!
2019-10-04 12:24:02 INFO  LineHelper:61 - Available mixers: 'ALSA [default]', 'ALSA [plughw:0,0]', 'ALSA [plughw:0,1]', 'sndrpihifiberry [plughw:1,0]'
2019-10-04 12:24:02 TRACE Session:818 - Handled Ping {payload: 5D9739E2}
2019-10-04 12:24:02 INFO  Session:855 - Skipping SecretBlock
Exception in thread "session-packet-receiver" java.nio.BufferUnderflowException
        at java.nio.Buffer.nextGetIndex(Buffer.java:500)
        at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:135)
        at xyz.gianlu.librespot.core.Session$Receiver.run(Session.java:833)
2019-10-04 12:24:02 DEBUG TokenProvider:37 - Token expired or not suitable, requesting again. {scope: playlist-read, token: null}
        at java.lang.Thread.run(Thread.java:745)
2019-10-04 12:24:02 TRACE MercuryClient:131 - Send Mercury request, seq: 1, uri: hm://keymaster/token/authenticated?scope=playlist-read&client_id=65b708073fc0480ea92a077233ca87bd&device_id=9jx0tcn0uh9ik9wkx0tu6t3pk9du358pcdplijrl, method: GET
Exception in thread "zeroconf-client-18701821" java.lang.NullPointerException
        at xyz.gianlu.librespot.mercury.MercuryClient.sendSync(MercuryClient.java:80)
        at xyz.gianlu.librespot.core.TokenProvider.get(TokenProvider.java:38)
        at xyz.gianlu.librespot.dealer.DealerClient.connect(DealerClient.java:50)
        at xyz.gianlu.librespot.core.Session.authenticate(Session.java:279)
        at xyz.gianlu.librespot.core.ZeroconfServer.handleAddUser(ZeroconfServer.java:315)
        at xyz.gianlu.librespot.core.ZeroconfServer.access$100(ZeroconfServer.java:35)
        at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.handle(ZeroconfServer.java:412)
        at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.lambda$run$1(ZeroconfServer.java:348)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by devgianlu** [comment]
Looks like a data corruption error because the payload itself contains the data length. Will add some debugging for good measure.
