### ISSUE TITLE
Exception in thread "dealer-looper" java.lang.IllegalStateException: Couldn't find current track!

### ISSUE THREAD

**Issue by leafy7382** [librespot-org/librespot-java#143]
librespot-new-api latest

```
2019-10-06 01:20:57 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 1, flags: 1, parts: 2
2019-10-06 01:20:57 INFO  Session:284 - Authenticated as 11127544113!
2019-10-06 01:20:58 DEBUG DealerClient:254 - Dealer connected! {host: gae-dealer.spotify.com}
2019-10-06 01:20:58 INFO  DeviceStateHandler:205 - Put state. {ts: 1570324858505, reason: NEW_DEVICE, request: device { device_info { can_play: true volume: 65536 name: "librespot-java" capabilities { can_be_player: true gaia_eq_connect_id: true supports_logout: true is_observable: true volume_steps: 64 supported_types: "audio/episode" supported_types: "audio/track" command_acks: true supports_playlist_v2: true is_controllable: true supports_transfer_command: true supports_command_request: true } device_software_version: "librespot-java 0.6.2" device_type: SPEAKER spirc_version: "3.2.6" device_id: "4c37x2tabdw7af4kpkaz6bsurk9vdq2sxh35lo4u" } player_state { context_restrictions { } playback_speed: 1.0 position_as_of_timestamp: 0 options { shuffling_context: false repeating_context: false repeating_track: false } suppressions { } } } member_type: CONNECT_STATE put_state_reason: NEW_DEVICE has_been_playing_for_ms: 0 client_side_timestamp: 1570324858066}
2019-10-06 01:20:58 INFO  StateWrapper:267 - Notified new device (us)!
2019-10-06 01:21:19 INFO  Session:379 - Closed session. {deviceId: 4c37x2tabdw7af4kpkaz6bsurk9vdq2sxh35lo4u, ap: gae2-accesspoint-a-z0gc.ap.spotify.com/104.199.241.5}
2019-10-06 01:21:19 TRACE ZeroconfServer:308 - Closed previous session to accept new. {deviceId: 4c37x2tabdw7af4kpkaz6bsurk9vdq2sxh35lo4u}
2019-10-06 01:21:19 DEBUG TimeProvider:70 - Loaded time offset from NTP: -1ms
2019-10-06 01:21:19 INFO  Session:104 - Created new session! {deviceId: 4c37x2tabdw7af4kpkaz6bsurk9vdq2sxh35lo4u, ap: gae2-accesspoint-a-mpnd.ap.spotify.com/104.199.241.1}
2019-10-06 01:21:19 INFO  ZeroconfServer:312 - Accepted new user from K0Mx0750. {deviceId: 4c37x2tabdw7af4kpkaz6bsurk9vdq2sxh35lo4u}
2019-10-06 01:21:19 INFO  Session:252 - Connected successfully!
2019-10-06 01:21:19 INFO  LineHelper:61 - Available mixers: 'ALSA [default]', 'ALSA [plughw:0,0]', 'ALSA [plughw:0,1]', 'sndrpihifiberry [plughw:1,0]'
2019-10-06 01:21:19 DEBUG TokenProvider:37 - Token expired or not suitable, requesting again. {scope: playlist-read, token: null}
2019-10-06 01:21:19 TRACE Session:818 - Handled Ping {payload: 5D99418F}
2019-10-06 01:21:19 TRACE MercuryClient:131 - Send Mercury request, seq: 1, uri: hm://keymaster/token/authenticated?scope=playlist-read&client_id=65b708073fc0480ea92a077233ca87bd&device_id=4c37x2tabdw7af4kpkaz6bsurk9vdq2sxh35lo4u, method: GET
2019-10-06 01:21:19 INFO  Session:859 - Skipping SecretBlock
2019-10-06 01:21:19 INFO  Session:838 - Received LicenseVersion: 0
2019-10-06 01:21:19 INFO  Session:828 - Received CountryCode: TW
2019-10-06 01:21:19 INFO  Session:859 - Skipping ProductInfo
2019-10-06 01:21:19 INFO  Session:859 - Skipping LegacyWelcome
2019-10-06 01:21:19 INFO  Session:859 - Skipping UnknownData_AllZeros
2019-10-06 01:21:19 DEBUG Session:842 - Received 0x10: 6780E932E53BDB0DC1B49E3420F00E99A9396CA0
2019-10-06 01:21:19 INFO  Session:794 - Skipping unknown command {cmd: 0x75, payload: 000000}
2019-10-06 01:21:19 TRACE Session:824 - Handled PongAck {payload: 5D99418F}
2019-10-06 01:21:19 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 1, flags: 1, parts: 2
2019-10-06 01:21:19 INFO  Session:284 - Authenticated as 11127544113!
2019-10-06 01:21:20 DEBUG DealerClient:254 - Dealer connected! {host: guc-dealer.spotify.com}
2019-10-06 01:21:21 INFO  DeviceStateHandler:205 - Put state. {ts: 1570324881207, reason: NEW_DEVICE, request: device { device_info { can_play: true volume: 65536 name: "librespot-java" capabilities { can_be_player: true gaia_eq_connect_id: true supports_logout: true is_observable: true volume_steps: 64 supported_types: "audio/episode" supported_types: "audio/track" command_acks: true supports_playlist_v2: true is_controllable: true supports_transfer_command: true supports_command_request: true } device_software_version: "librespot-java 0.6.2" device_type: SPEAKER spirc_version: "3.2.6" device_id: "4c37x2tabdw7af4kpkaz6bsurk9vdq2sxh35lo4u" } player_state { context_restrictions { } playback_speed: 1.0 position_as_of_timestamp: 0 options { shuffling_context: false repeating_context: false repeating_track: false } suppressions { } } } member_type: CONNECT_STATE put_state_reason: NEW_DEVICE has_been_playing_for_ms: 0 client_side_timestamp: 1570324880553}
2019-10-06 01:21:21 INFO  StateWrapper:267 - Notified new device (us)!
2019-10-06 01:21:22 DEBUG Player:135 - Received command: Transfer
2019-10-06 01:21:22 DEBUG Player:92 - Loading context (transfer), uri: spotify:playlist:37i9dQZF1DX86u71Yvk3lm
2019-10-06 01:21:22 DEBUG DeviceStateHandler:186 - Device is now active. {ts: 1570324882178}
2019-10-06 01:21:22 TRACE MercuryClient:131 - Send Mercury request, seq: 2, uri: hm://context-resolve/v1/spotify:playlist:37i9dQZF1DX86u71Yvk3lm, method: GET
2019-10-06 01:21:22 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 2, flags: 1, parts: 2
Exception in thread "dealer-looper" java.lang.IllegalStateException: Couldn't find current track!
  at xyz.gianlu.librespot.player.StateWrapper$TracksKeeper.initializeFrom(StateWrapper.java:905)
  at xyz.gianlu.librespot.player.StateWrapper.transfer(StateWrapper.java:432)
  at xyz.gianlu.librespot.player.Player.transferState(Player.java:95)
  at xyz.gianlu.librespot.player.Player.command(Player.java:142)
  at xyz.gianlu.librespot.connectstate.DeviceStateHandler.notifyCommand(DeviceStateHandler.java:99)
  at xyz.gianlu.librespot.connectstate.DeviceStateHandler.onRequest(DeviceStateHandler.java:162)
  at xyz.gianlu.librespot.dealer.DealerClient.lambda$handleRequest$1(DealerClient.java:82)
  at xyz.gianlu.librespot.dealer.DealerClient$Looper.run(DealerClient.java:205)
  at java.lang.Thread.run(Thread.java:745)
2019-10-06 01:21:32 WARN  Session:810 - Socket timed out. Reconnecting...
2019-10-06 01:23:02 WARN  Session:810 - Socket timed out. Reconnecting...
2019-10-06 01:23:19 TRACE Session:818 - Handled Ping {payload: 5D994207}
2019-10-06 01:23:19 TRACE Session:824 - Handled PongAck {payload: 5D994207}
```

**Comment by devgianlu** [comment]
The issue here is that the transfer command does not contain the context therefore librespot fetches it making searching for the current track uid useless.

Are you able to reproduce this? How?

**Comment by leafy7382** [comment]
I left the instance running and came back to reconnect the next day, and this happens. I don't see it today but will try to see if it happens again.

**Comment by leafy7382** [comment]
Doesn't happen anymore
