### ISSUE TITLE
Reconnection failed

### ISSUE THREAD

**Issue by leafy7382** [librespot-org/librespot-java#144]
new-api latest

```
2019-10-08 20:47:41 WARN  DealerClient:268 - Did not receive ping in 3 seconds. Reconnecting...
2019-10-08 20:47:41 TRACE DealerClient:174 - Scheduled reconnection attempt in 10 seconds...
2019-10-08 20:47:51 DEBUG TokenProvider:37 - Token expired or not suitable, requesting again. {scope: playlist-read, token: StoredToken{expiresIn=3600, accessToken='BQBuRzcrvu5Ujtb2RAzkdV795bktyfT-CoTD5YuIN8yhY5CD8cyqjqdLIB7da_xiJQR0Wx10m-RFhNWvThplklO_DwfNNnzrrWsj0pKSj8Gc31-JP0si27cjhlwwA2U-o1S_iFBBjoSPE_GNSpXDH8sxmSkcEaHf-5y-7mdgdIKoO8W-W4e9tq5XeB3AQtnFsclCIUNnUQsIlsw', scopes=[playlist-read], timestamp=1570560997446}}
2019-10-08 20:47:51 TRACE MercuryClient:131 - Send Mercury request, seq: 11, uri: hm://keymaster/token/authenticated?scope=playlist-read&client_id=65b708073fc0480ea92a077233ca87bd&device_id=egub7v2yt2uklg2lytd9enio8hmh6x1wdytxyzcp, method: GET
2019-10-08 20:47:53 FATAL Session:799 - Failed reading packet!
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.DataInputStream.readFully(DataInputStream.java:195)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at xyz.gianlu.librespot.crypto.CipherPair.receiveEncoded(CipherPair.java:60)
	at xyz.gianlu.librespot.core.Session$Receiver.run(Session.java:791)
	at java.lang.Thread.run(Thread.java:745)
2019-10-08 20:47:55 WARN  Session:810 - Socket timed out. Reconnecting...
2019-10-08 20:47:56 INFO  Session:252 - Connected successfully!
Exception in thread "session-packet-receiver" java.lang.NegativeArraySizeException
	at xyz.gianlu.librespot.core.Session.connect(Session.java:169)
	at xyz.gianlu.librespot.core.Session.reconnect(Session.java:534)
	at xyz.gianlu.librespot.core.Session.access$700(Session.java:48)
	at xyz.gianlu.librespot.core.Session$Receiver.run(Session.java:800)
	at java.lang.Thread.run(Thread.java:745)
2019-10-08 20:48:41 WARN  DealerClient:305 - An exception occurred. Reconnecting...
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.InputStreamSource.read(Okio.kt:102)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:159)
	at okio.RealBufferedSource.request(RealBufferedSource.kt:62)
	at okio.RealBufferedSource.require(RealBufferedSource.kt:55)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:68)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:247)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:181)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by leafy7382** [comment]
No longer happens
