### ISSUE TITLE
NullPointerExcetion in StateWrapper.java

### ISSUE THREAD

**Issue by mtesseract** [librespot-org/librespot-java#146]
**Describe the bug**

librespot-java throws an NPE when initiating playback:

```
Exception in thread "handle-packet-15158385" java.lang.NullPointerException
        at xyz.gianlu.librespot.player.StateWrapper.getCurrentTrack(StateWrapper.java:292)
        at xyz.gianlu.librespot.player.Player.loadTrack(Player.java:389)
        at xyz.gianlu.librespot.player.Player.handleLoad(Player.java:383)
        at xyz.gianlu.librespot.player.Player.handleFrame(Player.java:89)
        at xyz.gianlu.librespot.player.Player.frame(Player.java:193)
        at xyz.gianlu.librespot.spirc.SpotifyIrc$SpircListener.event(SpotifyIrc.java:199)
        at xyz.gianlu.librespot.mercury.MercuryClient$InternalSubListener.dispatch(MercuryClient.java:328)
        at xyz.gianlu.librespot.mercury.MercuryClient.handle(MercuryClient.java:200)
        at xyz.gianlu.librespot.core.PacketsManager$Looper.lambda$run$0(PacketsManager.java:64)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Seems to be related to the following function
```
        synchronized PlayableId currentlyPlaying() {
            return tracks.get(playingIndex).id();
        }
```

I am not a Java expert, but I have the feeling, that calling .get() on a List is dangerous.

**To Reproduce**

Start librespot-java (I am using USER_PASS authoriation).
Retrieve the device_id.
Execute e.g.

```
curl -v -H "Authorization: Bearer $TOKEN" -XPUT "https://api.spotify.com/v1/me/player/play?device_id=$DEVICE_ID" -d '{"uris": ["spotify:track:5j6EomySX9T740tmNaB9kF"]}'
```

**Expected behavior**

Play the track given in the `uris` array.

**Screenshots/Stracktraces/Logs**

```
2019-10-26 22:02:04 INFO  Session:98 - Created new session! {deviceId: ..., ap: ...} 
2019-10-26 22:02:06 INFO  Session:242 - Connected successfully!
2019-10-26 22:02:06 DEBUG TimeProvider:20 - Corrected time offset, delta: 0s
2019-10-26 22:02:06 TRACE Session:741 - Handled Ping {payload: 5DB4A63E}
2019-10-26 22:02:06 INFO  Session:782 - Skipping SecretBlock
2019-10-26 22:02:06 INFO  Session:761 - Received LicenseVersion: 0
2019-10-26 22:02:06 INFO  Session:751 - Received CountryCode: DE
2019-10-26 22:02:06 INFO  Session:782 - Skipping ProductInfo
2019-10-26 22:02:06 INFO  Session:782 - Skipping LegacyWelcome
2019-10-26 22:02:06 INFO  Session:782 - Skipping UnknownData_AllZeros
2019-10-26 22:02:06 DEBUG Session:765 - Received 0x10: 70B87726DB193F990CC5AA5EAC84F8EE70714E79
2019-10-26 22:02:06 TRACE Session:747 - Handled PongAck {payload: 5DB4A63E}
2019-10-26 22:02:06 INFO  Session:723 - Skipping unknown command {cmd: 0x75, payload: 000000}
2019-10-26 22:02:11 TRACE SpotifyIrc:105 - Send frame, type: kMessageTypeHello
2019-10-26 22:02:11 TRACE MercuryClient:131 - Send Mercury request, seq: 1, uri: hm://remote/3/user/$USER/, method: POST
2019-10-26 22:02:11 TRACE MercuryClient:173 - Handling packet, cmd: MercuryReq, seq: 1, flags: 1, parts: 1
2019-10-26 22:02:11 TRACE SpotifyIrc:119 - Frame sent successfully, type: kMessageTypeHello
2019-10-26 22:02:11 INFO  Session:258 - Authenticated as $USER!
2019-10-26 22:02:42 TRACE MercuryClient:173 - Handling packet, cmd: MercuryEvent, seq: -365621701095981056, flags: 1, parts: 2
2019-10-26 22:02:42 TRACE SpotifyIrc:195 - Handling frame, type: kMessageTypeLoad, ident: webapi-3a95fedd0c764b41a5c3dc3cd7634ccd
2019-10-26 22:02:42 TRACE Player:187 - Frame has context_player_state: {"endpoint":"play","context":{"pages":[{"tracks":[{"uri":"spotify:track:5j6EomySX9T740tmNaB9kF"}]}],"restrictions":{}},"play_origin":{},"options":{"skip_to":{},"player_options_override":{},"suppressions":{},"prefetch_level":"none","audio_stream":"default"},"play_options":{"reason":"interactive","operation":"replace","trigger":"immediately"},"logging_params":{}}
2019-10-26 22:02:43 DEBUG Player:363 - Loading context, uri: null
Exception in thread "handle-packet-7386859" java.lang.NullPointerException
	at xyz.gianlu.librespot.player.StateWrapper.getCurrentTrack(StateWrapper.java:292)
	at xyz.gianlu.librespot.player.Player.loadTrack(Player.java:389)
	at xyz.gianlu.librespot.player.Player.handleLoad(Player.java:383)
	at xyz.gianlu.librespot.player.Player.handleFrame(Player.java:89)
	at xyz.gianlu.librespot.player.Player.frame(Player.java:193)
	at xyz.gianlu.librespot.spirc.SpotifyIrc$SpircListener.event(SpotifyIrc.java:199)
	at xyz.gianlu.librespot.mercury.MercuryClient$InternalSubListener.dispatch(MercuryClient.java:328)
	at xyz.gianlu.librespot.mercury.MercuryClient.handle(MercuryClient.java:200)
	at xyz.gianlu.librespot.core.PacketsManager$Looper.lambda$run$0(PacketsManager.java:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Version/Commit**
commit 002a772693daab6fb831e1fc907950d98dc7bd20

**Comment by devgianlu** [comment]
That's a special issue. I had no idea that the client could receive a play request without a context uri. Are you able to test with #105?

**Comment by mtesseract** [comment]
According to my first tests I cannot reproduce the NPE with #105.
Thanks.
