### ISSUE TITLE
Network spike player problem

### ISSUE THREAD

**Issue by xMordax** [librespot-org/librespot-java#163]
**Describe the bug**
Spike in my network caused the Spotify client to throw an exception and stop playing the track. Had to reconnect to the Librespo-java Spotify connect to play it again.
Log:
```
 2019-12-29 23:23:21 TRACE CdnManager:261 - Chunk 29/40 completed, cdn: audio4-akp-spotify-com.akamaized.net, cached: false, stream: {fileId: 35C63FD3F0E95A4CCF563833396E56033FF3A5EF}
 2019-12-29 23:23:36 FATAL CdnManager:299 - Failed requesting chunk from network, index: 30, retried: false
 java.net.SocketTimeoutException: timeout
         at okio.SocketAsyncTimeout.newTimeoutException(Okio.kt:159)
         at okio.AsyncTimeout.exit$jvm(AsyncTimeout.kt:203)
         at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:163)
         at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:349)
         at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:222)
         at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.kt:210)
         at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:181)
         at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:105)
         at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:82)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:37)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
         at okhttp3.RealCall.execute(RealCall.kt:66)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.request(CdnManager.java:314)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.request(CdnManager.java:307)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:296)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.access$1200(CdnManager.java:190)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:366)
         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
         at java.base/java.lang.Thread.run(Thread.java:834)
 Caused by: java.net.SocketTimeoutException: Read timed out
         at java.base/java.net.SocketInputStream.socketRead0(Native Method)
         at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
         at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
         at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
         at okio.InputStreamSource.read(Okio.kt:102)
         at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:159)
         ... 28 more
 2019-12-29 23:23:45 DEBUG Player:366 - Playback halted on retrieving chunk 30.
 2019-12-29 23:23:46 FATAL CdnManager:299 - Failed requesting chunk from network, index: 31, retried: false
 java.net.UnknownHostException: audio4-akp-spotify-com.akamaized.net: Temporary failure in name resolution
         at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
         at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
         at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
         at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
         at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
         at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
         at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
         at okhttp3.Dns$Companion$SYSTEM$1.lookup(Dns.kt:48)
         at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:158)
         at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:123)
         at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
         at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:199)
         at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
         at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
         at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
         at okhttp3.RealCall.execute(RealCall.kt:66)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.request(CdnManager.java:314)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.request(CdnManager.java:307)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:296)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.access$1200(CdnManager.java:190)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:366)
         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
         at java.base/java.lang.Thread.run(Thread.java:834)
 2019-12-29 23:23:46 FATAL CdnManager:299 - Failed requesting chunk from network, index: 30, retried: true
 java.net.UnknownHostException: audio4-akp-spotify-com.akamaized.net
         at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
         at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
         at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
         at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
         at okhttp3.Dns$Companion$SYSTEM$1.lookup(Dns.kt:48)
         at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:158)
         at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:123)
         at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
         at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:199)
         at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
         at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
         at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
         at okhttp3.RealCall.execute(RealCall.kt:66)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.request(CdnManager.java:314)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.request(CdnManager.java:307)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:296)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:301)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.access$1200(CdnManager.java:190)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:366)
         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
         at java.base/java.lang.Thread.run(Thread.java:834)
 2019-12-29 23:23:46 FATAL CdnManager:299 - Failed requesting chunk from network, index: 32, retried: false
 java.net.UnknownHostException: audio4-akp-spotify-com.akamaized.net
         at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
         at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
         at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
         at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
         at okhttp3.Dns$Companion$SYSTEM$1.lookup(Dns.kt:48)
         at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:158)
         at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:123)
         at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
         at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:199)
         at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
         at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
         at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
         at okhttp3.RealCall.execute(RealCall.kt:66)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.request(CdnManager.java:314)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.request(CdnManager.java:307)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:296)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.access$1200(CdnManager.java:190)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:366)
         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
         at java.base/java.lang.Thread.run(Thread.java:834)
 2019-12-29 23:23:46 FATAL CdnManager:299 - Failed requesting chunk from network, index: 33, retried: false
 java.net.UnknownHostException: audio4-akp-spotify-com.akamaized.net
         at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
         at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
         at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
         at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
         at okhttp3.Dns$Companion$SYSTEM$1.lookup(Dns.kt:48)
         at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:158)
         at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:123)
         at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
         at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:199)
         at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
         at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
         at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
         at okhttp3.RealCall.execute(RealCall.kt:66)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.request(CdnManager.java:314)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.request(CdnManager.java:307)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:296)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.access$1200(CdnManager.java:190)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:366)
         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
         at java.base/java.lang.Thread.run(Thread.java:834)
 2019-12-29 23:23:46 FATAL CdnManager:299 - Failed requesting chunk from network, index: 32, retried: true
 java.net.UnknownHostException: audio4-akp-spotify-com.akamaized.net
         at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
         at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
         at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
         at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
         at okhttp3.Dns$Companion$SYSTEM$1.lookup(Dns.kt:48)
         at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:158)
         at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:123)
         at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
         at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:199)
         at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
         at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
         at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
         at okhttp3.RealCall.execute(RealCall.kt:66)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.request(CdnManager.java:314)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.request(CdnManager.java:307)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:296)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:301)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.access$1200(CdnManager.java:190)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:366)
         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
         at java.base/java.lang.Thread.run(Thread.java:834)
 2019-12-29 23:23:46 FATAL CdnManager:299 - Failed requesting chunk from network, index: 31, retried: true
 java.net.UnknownHostException: audio4-akp-spotify-com.akamaized.net
         at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
         at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
         at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
         at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
         at okhttp3.Dns$Companion$SYSTEM$1.lookup(Dns.kt:48)
         at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:158)
         at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:123)
         at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
         at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:199)
         at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
         at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
         at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
         at okhttp3.RealCall.execute(RealCall.kt:66)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.request(CdnManager.java:314)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.request(CdnManager.java:307)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:296)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:301)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.access$1200(CdnManager.java:190)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:366)
         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
         at java.base/java.lang.Thread.run(Thread.java:834)
 2019-12-29 23:23:46 FATAL CdnManager:299 - Failed requesting chunk from network, index: 33, retried: true
 java.net.UnknownHostException: audio4-akp-spotify-com.akamaized.net
         at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
         at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
         at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
         at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
         at okhttp3.Dns$Companion$SYSTEM$1.lookup(Dns.kt:48)
         at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:158)
         at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:123)
         at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
         at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:199)
         at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
         at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
         at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
         at okhttp3.RealCall.execute(RealCall.kt:66)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.request(CdnManager.java:314)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.request(CdnManager.java:307)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:296)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:301)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.access$1200(CdnManager.java:190)
         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:366)
         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
         at java.base/java.lang.Thread.run(Thread.java:834)
```

**To Reproduce**
Hard since you need bad internet connection but if possible, it should stop the player

**Expected behavior**
Should stop playing track.

**Version/Commit**
19b313e2c774d9fd8347c06902463d7b31d45fbc

**Comment by devgianlu** [comment]
When that happens we could:
- Retry infinitely until the request successes
- Stop the playback

Both shouldn't be very difficult to implement, will work on it next year.

**Comment by devgianlu** [comment]
I figured that the error reporting of this issue was broken meaning that the client wasn't aware of the fact that the chunk loading failed. I've fixed that and improved the overall retry strategy.

You can toggle the behavior with `player.stopPlaybackOnChunkError` (default false): if true, the client will stop the playback after one retry only, else it will retry a maximum of 128 times with an `log10(retryN)` seconds interval.

@xMordax Let me know if this works for you.

**Comment by devgianlu** [comment]
@xMordax How is it going with this?

**Comment by xMordax** [comment]
Never had spikes since... may close this ticket, if it happens again Ill create a new one
