### ISSUE TITLE
add playlist metadata retrieve

### ISSUE THREAD

**Issue by kmahyyg** [librespot-org/librespot-java#168]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**

Add playlist api for api server, so that I don't need to request playlist metadata myself.

**Describe alternatives you've considered**

No,it's easy to implement on your base currently.

**Additional context**

There might need to enhance the exception handle(unrelated to this problem):

```
2020-01-14 17:41:11 DEBUG MercuryClient:208 - Couldn't dispatch Mercury event {seq: 8762xxxxxxxxxxxxxxxxxxxxx4, uri: hm://pusher/v1/connections/Zxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, code: 200, payload: []}
2020-01-14 17:41:11 DEBUG Session:852 - Received 0x10: BBF0xxxxxxxxxxxxxxxxxxxxxxxxxxx
2020-01-14 17:41:11 INFO  Session:805 - Skipping unknown command {cmd: 0x75, payload: 000000}
2020-01-14 17:42:01 FATAL Session:810 - Failed reading packet!
java.io.EOFException
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:202)
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:170)
        at xyz.gianlu.librespot.crypto.CipherPair.receiveEncoded(CipherPair.java:60)
        at xyz.gianlu.librespot.core.Session$Receiver.run(Session.java:802)
        at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by devgianlu** [comment]
I did not include that API endpoint because Spotify already provides one: https://developer.spotify.com/documentation/web-api/reference/tracks/get-track/

Regarding the other issue, please make sure you are running the latest release (or commit) and then open a new issue.

**Comment by kmahyyg** [comment]
I'm not trying to get a track, I'm trying to get metadata of a playlist.

**Comment by kmahyyg** [comment]
By the way, I ensure I'm running latest stable build.

If I need to use Spotify official API again, it is really not elegant about implementing a software.

**Comment by devgianlu** [comment]
> I'm not trying to get a track, I'm trying to get metadata of a playlist.

What do you mean by metadata? The API from Spotify already provides a lot of information.

**Comment by devgianlu** [comment]
What was I thinking, this endpoint is already available in the API: `POST \metadata\{type}\{uri}`, see the [README](https://github.com/librespot-org/librespot-java/tree/dev/api).

**Comment by kmahyyg** [comment]
the feature request is : `POST \metadata\{type}\{uri}` add `playlist` to `{type}`

**Comment by devgianlu** [comment]
How didn't I get this all the time?! Sorry.

**Comment by devgianlu** [comment]
> the feature request is : POST \metadata\{type}\{uri} add playlist to {type}

Done! Sorry for the misunderstanding.

**Comment by kmahyyg** [comment]
A huge thanks to you.
