### ISSUE TITLE
Hostname not verified when downloading chunks

### ISSUE THREAD

**Issue by devgianlu** [librespot-org/librespot-java#180]
**Describe the bug**
When listening a `SSLPeerUnverifiedException` may be thrown while trying to download some chunks.

**Screenshots/Stracktraces/Logs**
```
Mar 07 10:19:19 server bash[32608]: 2020-03-07 10:19:19 FATAL CdnManager:293 - Failed requesting chunk from network, index: 24
Mar 07 10:19:19 server bash[32608]: javax.net.ssl.SSLPeerUnverifiedException: Hostname audio-sp-fra2-13.spotifycdn.net not verified:
Mar 07 10:19:19 server bash[32608]:     certificate: sha256/EAIhHxMRr1xoDXpmusbs97+ccVCfgbdNzWo4768PkQg=
Mar 07 10:19:19 server bash[32608]:     DN: CN=*.spotify.edgecdn.host, OU=Domain Control Validated
Mar 07 10:19:19 server bash[32608]:     subjectAltNames: [*.spotify.edgecdn.host, spotify.edgecdn.host]
Mar 07 10:19:19 server bash[32608]:         at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:360)
Mar 07 10:19:19 server bash[32608]:         at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:308)
Mar 07 10:19:19 server bash[32608]:         at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:182)
Mar 07 10:19:19 server bash[32608]:         at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:238)
Mar 07 10:19:19 server bash[32608]:         at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:111)
Mar 07 10:19:19 server bash[32608]:         at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:79)
Mar 07 10:19:19 server bash[32608]:         at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:163)
Mar 07 10:19:19 server bash[32608]:         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
Mar 07 10:19:19 server bash[32608]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
Mar 07 10:19:19 server bash[32608]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
Mar 07 10:19:19 server bash[32608]:         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
Mar 07 10:19:19 server bash[32608]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
Mar 07 10:19:19 server bash[32608]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
Mar 07 10:19:19 server bash[32608]:         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
Mar 07 10:19:19 server bash[32608]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
Mar 07 10:19:19 server bash[32608]:         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
Mar 07 10:19:19 server bash[32608]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
Mar 07 10:19:19 server bash[32608]:         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
Mar 07 10:19:19 server bash[32608]:         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:194)
Mar 07 10:19:19 server bash[32608]:         at okhttp3.RealCall.execute(RealCall.kt:67)
Mar 07 10:19:19 server bash[32608]:         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.request(CdnManager.java:307)
Mar 07 10:19:19 server bash[32608]:         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.request(CdnManager.java:300)
Mar 07 10:19:19 server bash[32608]:         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:290)
Mar 07 10:19:19 server bash[32608]:         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer.access$1400(CdnManager.java:186)
Mar 07 10:19:19 server bash[32608]:         at xyz.gianlu.librespot.player.feeders.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:359)
Mar 07 10:19:19 server bash[32608]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Mar 07 10:19:19 server bash[32608]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Mar 07 10:19:19 server bash[32608]:         at java.base/java.lang.Thread.run(Thread.java:834)
```

**Version/Commit**
78ed89231f359e8762fb96c1d44b5cac506a1a88

**Comment by devgianlu** [comment]
This was probably an issue with the Java configuration on my device. Fixed by adding a couple of CAs to the cacerts keystore.
