### ISSUE TITLE
Exception when selecting the device, maybe related to crossfading

### ISSUE THREAD

**Issue by funtax** [librespot-org/librespot-java#187]
**Describe the bug**
I have no idea what happened. I had Spotify in stopped mode and selected my receiver.
Then the exception occurred and the process crashed.

I was not yet able to reproduce it, so I assume it's maybe a race-condition.

**To Reproduce**
Selected device inside Spoitfy while having the player stopped.
I have configured a crossfading of 10 seconds, pretty sure this might cause the troubles.

**Expected behavior**
No exception, player should be selected.

**Screenshots/Stracktraces/Logs**
FATAL EXCEPTION: player-runner-looper-1032471
    java.lang.IllegalStateException
        at xyz.gianlu.librespot.player.StateWrapper.setState(StateWrapper.java:103)
        at xyz.gianlu.librespot.player.StateWrapper.setBuffering(StateWrapper.java:98)
        at xyz.gianlu.librespot.player.Player.startedLoading(Player.java:242)
        at xyz.gianlu.librespot.player.PlayerRunner$TrackHandler.load(PlayerRunner.java:581)
        at xyz.gianlu.librespot.player.PlayerRunner$TrackHandler.access$800(PlayerRunner.java:520)
        at xyz.gianlu.librespot.player.PlayerRunner$Looper.run(PlayerRunner.java:427)
        at java.lang.Thread.run(Thread.java:784)

**Version/Commit**
Current dev-version.

**Comment by devgianlu** [comment]
A race condition on `#setState` should not be possible. I think what happened here is that the client went inactive while crossfading leaving some floating `TrackHandler`s. Not quite sure.

I've moved some methods, but I don't think that was the issue.

**Comment by funtax** [comment]
I have not faced this issue again in the last versions. Maybe it's solved now, otherwise I will open a new ticket.
