### ISSUE TITLE
exception in thread "zeroconf-client-xxxxxxx" java.lang.IllegalStateException: Failed opening line!

### ISSUE THREAD

**Issue by hemboorgur** [librespot-org/librespot-java#198]
I've recently started playing around with a Raspberry Pi, so this might be a total noob error...
But I wanted to make my Raspberry Pi a Spotify Connect device. First I tried to use the normal Librespot and Raspotify but I had a bad time with it because the audio kept being corrupted. So I removed it from the Raspberry Pi and tried this. 
Maybe I should say how I installed it first, because it wasn't the default way...
The way I did it was thru SSH and SAMBA
First I installed the .jar file on my computer and copied it too the Raspberry Pi thru local network sharing (SAMBA).
After that I ran the command via SSH on the Raspberry Pi.
But I keep running into the same weird error...
Every time I try to start the service by SSH-ing into the Raspberry Pi and running the command `java -jar librespot-core-jar-with-dependencies.jar`, it start off fine and shows me it as a speaker in Spotify. But when I try to connect the 'fun' starts...
First it starts to show me this...

```
020-04-06 14:10:24 INFO  Session:107 - Created new session! {deviceId: xxx, ap: guc3-accesspoint-b-9c2r.ap.spotify.com:443, proxy: false} 
2020-04-06 14:10:24 INFO  ZeroconfServer:329 - Accepted new user from xxx. {xxx}
2020-04-06 14:10:25 INFO  Session:277 - Connected successfully!
2020-04-06 14:10:25 INFO  CacheManager:71 - There are 0 cached entries.
2020-04-06 14:10:25 INFO  LineHelper:61 - Available mixers: 'PulseAudio Mixer', 'ALSA [default]', 'ALSA [plughw:0,0]', 'ALSA [plughw:0,1]'
Exception in thread "zeroconf-client-4639249" java.lang.IllegalStateException: Failed opening line!
	at xyz.gianlu.librespot.player.PlayerRunner.<init>(PlayerRunner.java:70)
	at xyz.gianlu.librespot.player.Player.<init>(Player.java:62)
	at xyz.gianlu.librespot.core.Session.authenticate(Session.java:297)
	at xyz.gianlu.librespot.core.ZeroconfServer.handleAddUser(ZeroconfServer.java:332)
	at xyz.gianlu.librespot.core.ZeroconfServer.access$100(ZeroconfServer.java:38)
	at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.handleRequest(ZeroconfServer.java:396)
	at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.handle(ZeroconfServer.java:471)
	at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.lambda$run$1(ZeroconfServer.java:379)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.sound.sampled.LineUnavailableException
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openImpl(PulseAudioMixer.java:714)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:588)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:584)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.open(PulseAudioMixer.java:579)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:94)
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:75)
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:90)
	at xyz.gianlu.librespot.player.PlayerRunner$Output.acquireLine(PlayerRunner.java:303)
	at xyz.gianlu.librespot.player.PlayerRunner$Output.<init>(PlayerRunner.java:282)
	at xyz.gianlu.librespot.player.PlayerRunner.<init>(PlayerRunner.java:68)
	... 10 more
```

(I'm just putting x's because I don't know what's sensitive information and what isn't)
After this shows up it won't let me connect to it ofcourse, but after it times out and I try to connect again, I get another error...

```
2020-04-06 14:12:30 WARN  Session:975 - Socket timed out. Reconnecting...
2020-04-06 14:12:31 INFO  Session:277 - Connected successfully!
2020-04-06 14:12:32 INFO  Session:598 - Re-authenticated as iyj9f4gktpsxms58ov0snylmk!
2020-04-06 14:12:32 FATAL ZeroconfServer:404 - Failed handling getInfo!
java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
	at xyz.gianlu.librespot.core.ZeroconfServer.handleGetInfo(ZeroconfServer.java:243)
	at xyz.gianlu.librespot.core.ZeroconfServer.access$200(ZeroconfServer.java:38)
	at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.handleRequest(ZeroconfServer.java:402)
	at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.handle(ZeroconfServer.java:471)
	at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.lambda$run$1(ZeroconfServer.java:379)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-04-06 14:12:32 FATAL ZeroconfServer:404 - Failed handling getInfo!
java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
	at xyz.gianlu.librespot.core.ZeroconfServer.handleGetInfo(ZeroconfServer.java:243)
	at xyz.gianlu.librespot.core.ZeroconfServer.access$200(ZeroconfServer.java:38)
	at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.handleRequest(ZeroconfServer.java:402)
	at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.handle(ZeroconfServer.java:471)
	at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.lambda$run$1(ZeroconfServer.java:379)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-04-06 14:12:32 DEBUG ZeroconfServer:268 - Dropped connection attempt because user is already connected. {username: xxx}
2020-04-06 14:12:32 DEBUG ZeroconfServer:268 - Dropped connection attempt because user is already connected. {username: xxx}
2020-04-06 14:12:32 INFO  Session:1023 - Skipping SecretBlock
2020-04-06 14:12:32 INFO  Session:1002 - Received LicenseVersion: 0
2020-04-06 14:12:32 INFO  Session:992 - Received CountryCode: NL
2020-04-06 14:12:32 INFO  Session:1023 - Skipping ProductInfo
2020-04-06 14:12:32 INFO  Session:1023 - Skipping LegacyWelcome
2020-04-06 14:12:32 INFO  Session:1023 - Skipping UnknownData_AllZeros
2020-04-06 14:12:32 TRACE MercuryClient:176 - Handling packet, cmd: MercuryEvent, seq: 5619155328819003392, flags: 1, parts: 1
2020-04-06 14:12:32 DEBUG MercuryClient:209 - Couldn't dispatch Mercury event {seq: 5619155328819003392, uri: hm://pusher/v1/connections/NmVhMTBiNjllZjMxYjkxOGI2Y2E4NWE3NzQzMWQ3YmIyNDNmY2RlOCtBUCt0Y3A6Ly9nZXcxLWFjY2Vzc3BvaW50LWItNnNqZy5nZXcxLnNwb3RpZnkubmV0OjUwMTUrMDU2QUJEQTQ3REFDQTk4N0M5NzE5RERFRjc3Q0FCOUM2NTRDNUQ4NkZBRjFFRTczMDk5QjE0OEM1MTEyN0QzQg%3D%3D, code: 200, payload: []}
2020-04-06 14:12:33 DEBUG Session:1006 - Received 0x10: EF49FD25C5ED27955CC896DA0C5AE2A8AE4E318E
2020-04-06 14:12:33 INFO  Session:957 - Skipping unknown command {cmd: 0x75, payload: 000000}
2020-04-06 14:17:37 DEBUG ZeroconfServer:268 - Dropped connection attempt because user is already connected. {username: xxx}
```

(sometimes it's only from this part: (2020-04-06 14:12:32 INFO  Session:1023 - Skipping SecretBlock) till the end)

Sooo... Did I commit a rookie mistake or is this an actual thing?
Please help me with this because I would love to listen to my music on my speakers wirelessly.

**Comment by devgianlu** [comment]
Please have a look at https://github.com/spocon/spocon/issues/12

**Comment by hemboorgur** [comment]
Thanks for the help!!!
This indeed helped with the connectivity problems.
But now my sound is yet again corrupted...
Do you know how to solve that too?
btw should do I have to close this issue now?

**Comment by devgianlu** [comment]
What does it mean that the sound is corrupted?

**Comment by hemboorgur** [comment]
I don't really know how to describe it, but the music I was listening to - Dua Lipa-Be The One - now sounds like a heavy metal track.
The sound is completly warped and is also slower then it should be.

**Comment by hemboorgur** [comment]
I'm looking thru the issues on spocon and librespot-java but haven't any solutions yet...

**Comment by devgianlu** [comment]
Not really an expert of Linux sound stuff. 

@spocon Can you help on this one?

**Comment by hemboorgur** [comment]
So after half a day I tried alot.
I've tried with and without pulseaudio, I've tried to see if it was underpowered or something, I've tried different speakers, even Bluetooth ones. But no result, still the same corrupted audio.
The only thing I haven't tried is a USB audio card but I don't have one and I can't order one either for some time due to COVID but I'm not sure if that will help.
Plz let me know if any of you found something.
I'll keep you updated.
Btw should I keep this issue open until solved or should I close this one and start another, because it's not the original issue, please let me know.

**Comment by spocon** [comment]
Please try this. I recognized in your first comment output an exception which I found a fix in a blog

https://nealvs.wordpress.com/2017/08/11/java-sound-on-a-raspberry-pi-with-openjdk/

**Comment by devgianlu** [comment]
Shouldn't the options in the pulse configuration be uncommented?

**Comment by hemboorgur** [comment]
Hey, sorry I was offline for awhile.
What does uncommented mean?

**Comment by devgianlu** [comment]
> What does uncommented mean?

I think that the leading semicolon excludes the line from the configuration.

**Comment by hemboorgur** [comment]
Nothing worked, I tried several times but with no luck...

**Comment by spocon** [comment]
> If you don't have a config.toml or default.toml file, you should do the following steps
> 
>     1. create new file "config.toml" and copy the content from here:
>        https://github.com/librespot-org/librespot-java/blob/dev/core/src/main/resources/default.toml
> 
>     2. change `mixerSearchKeywords = ""` to `mixerSearchKeywords = "ALSA"`
> 
> 
> 3.1 copy your new file in the same folder than your jar file
> 
> 3.2 run `java -jar librespot-core-jar-with-dependencies.jar --conf-file=./config.toml`

Have you tried this?

**Comment by hemboorgur** [comment]
let me try no3 again, last time that didnt go smoothly

**Comment by hemboorgur** [comment]
Okay wellllll, I did it again and for the first time I was actually able to connect to the librespot-java speakers instead of the spocon speakers and it played my music...
But... The audio still didn't change.
I'm thinking about opening its case to see if I can find an abnormality near the audio jack and HDMI because this is getting absurd. Do you guys think this might be an hardware issue or could it be something else yet again?
I'm sorry to keep bothering you guys but it's really strange, isn't it?

**Comment by devgianlu** [comment]
I think it's a software issue, but rather strange because I know people are using this with Rasperry Pis without any configuration change. Did you remember changing any audio parameter? 

If you don't have anything important on it, I'd suggest reinstalling everything as a last resort.

**Comment by hemboorgur** [comment]
Hmm, do you mean just reinstalling everything?
I dont remember changing anything significantly but I'll check all my settings when I get a change to.

**Comment by hemboorgur** [comment]
Hello there, so I have an update the sound works perfectly rn after I plugged in my HDMI cable to look around in retropie's own settings...
I will reboot it again to see if it changes depending on if the HDMI is in or not.
I hope it didn't just randomly behaved well or that I found the solution.
Well ig we'll know in a moment...

**Comment by hemboorgur** [comment]
I have found the problem, finally.
The sound turns crazy when there is no HDMI connected and it's just the power cord and the 3.5mm audio jack.
Any way to fix this weird bug in the Raspberry Pi's system?

**Comment by hemboorgur** [comment]
Okay well finally we found the cause of the problem and now it's fixed.
This 'bug' is caused by... well something...
It fixed by plugging in a HDMI cable before boot to a display that is on and active.
After booting you can take it out without it changing how the sound 'sounds'.
The thing I've noticed that makes the change is when before you boot there is a static noise when your 3.5mm jack is plugged in and your speakers on.
If there is a static noise, the sound will be weird, and if there isn't static, all is fine.
I've 'cheated' around this by plugging a dead, old, small GPU that doesn't get detected by my PC into my PC and plugging an HDMI cable from it to the Raspberry Pi.
So far of the 7/8 tests I ran like this, it correctly passed the sound thru to my speakers.
Yeah.... weird.
Anyhow it's fixed now, I wanna thank you guys for helping me and I'll close this issue ones and for all.
Again thank you for your time and helping me with this.

**Comment by devgianlu** [comment]
Wow, that was a strange issue. Glad you fixed it in the end. Did you discover the solution by yourself or found something online?

**Comment by hemboorgur** [comment]
Actually it was accidental, I wanted to have a look in the systems settings and file manager before I would reinstall everything.
And yeah that's when it magically worked all of a sudden...
