### ISSUE TITLE
Auto-Disconnect Client after Inactivity

### ISSUE THREAD

**Issue by benturnberg** [librespot-org/librespot-java#210]
**Is your feature request related to a problem? Please describe.**
Sometimes I forget to manually disconnect from Spotify Connect and leave my LAN, then come back to find I can't reconnect (librespot says I'm already connected). Similar to #134 . This is not so problematic for me (I can log on to the server and restart the librespot applet), but it means that other members of the household will depend on me to do that for them if (when) they forget to disconnect, leave, come back and want to reconnect.

**Describe the solution you'd like**
I'd like to see a feature whereby the librespot applet disconnects connected clients after a period of inactivity (i.e. no music playing).

**Describe alternatives you've considered**
My current workaround is to schedule the restart of librespot every day at 4am.

**Additional context**
N/A

**Comment by devgianlu** [comment]
I guess you are using Zeroconf and never noticed that there is no proper check on whether the session is active. Would be nice if I could figure out after how much time Spotify considers the session expired.

Or this could be another connectivity issue. Do you see something related to reconnection between the first time you connect and when you come back?

**Comment by benturnberg** [comment]
That's right - I'm using Zeroconf (sorry, should have included that). The line which I'm seeing when I attempt to reconnect is from Zeroconf: "Dropped connection attempt because user is already connected", which I am getting around in one of two ways - reconnect using a different (device and) account if there's one handy, or kill the java process and restart it. Didn't notice about the lack of session active check, and I guess both that and not knowing Spotify's session expiry time makes implementing this more difficult.

I'm not really across the code, so this may come across as ignorant, but I was thinking of some kind of check as to whether song data / chunks are being received or not in order to establish whether there's an active session which is actually playing music... and if not, after a parameterised amount of time, optionally disconnect the active client?

**Comment by benturnberg** [comment]
Not to muddy the water, but just experienced this, where there was an initial failure to connect (first connection after starting), then a reconnect success which I didn't see on the iPhone client, then failure to reconnect:

`2020-04-19 12:36:38 INFO  Utils:108 - Successfully removed cryptography restrictions.
2020-04-19 12:36:38 INFO  ApResolver:66 - Loaded aps into pool: {accesspoint=[gae2-accesspoint-b-m5z3.ap.spotify.com:4070, gae2-accesspoint-b-1k2m.ap.spotify.com:443, gae2-accesspoint-b-3px2.ap.spotify.com:80, gae2-accesspoint-b-0nkg.ap.spotify.com:4070, gae2-accesspoint-b-33jn.ap.spotify.com:443, gae2-accesspoint-b-h2dz.ap.spotify.com:80, guc3-accesspoint-b-m208.ap.spotify.com:4070, gew1-accesspoint-b-mw6m.ap.spotify.com:443, gew1-accesspoint-b-91rz.ap.spotify.com:80], dealer=[gae-dealer.spotify.com:443, gew-dealer.spotify.com:443, guc-dealer.spotify.com:443], spclient=[gae-spclient.spotify.com:443, guc-spclient.spotify.com:443, gew-spclient.spotify.com:443]}
2020-04-19 12:36:39 INFO  ZeroconfServer:369 - Zeroconf HTTP server started successfully on port [port]!
2020-04-19 12:46:53 INFO  Zeroconf:470 - Announced service: Service{alias='[alias]', service='spotify-connect', port=[port], text={VERSION=1.0, CPath=/, Stack=SP}, addresses=[/a.b.c.d, /E.F.G.H], domain='.local', protocol='tcp', host='[host]'}
2020-04-19 13:27:02 TRACE ZeroconfServer:433 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.53 iOS/13.4.1 (iPhone11,2), Host=a.b.c.d, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
2020-04-19 13:27:02 TRACE ZeroconfServer:433 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.53 iOS/13.4.1 (iPhone11,2), Host=E.F.G.H, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
2020-04-19 13:27:08 TRACE ZeroconfServer:433 - Handling request: GET /?action=getInfo&version=2.7.1 HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.53 iOS/13.4.1 (iPhone11,2), Host=E.F.G.H, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
2020-04-19 13:27:12 TRACE ZeroconfServer:433 - Handling request: GET /?action=getInfo&version=2.7.1 HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.53 iOS/13.4.1 (iPhone11,2), Host=E.F.G.H, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
2020-04-19 13:27:20 TRACE ZeroconfServer:433 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.53 iOS/13.4.1 (iPhone11,2), Host=a.b.c.d, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
2020-04-19 13:27:20 TRACE ZeroconfServer:433 - Handling request: GET /?action=getInfo HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.53 iOS/13.4.1 (iPhone11,2), Host=E.F.G.H, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
2020-04-19 13:27:22 TRACE ZeroconfServer:433 - Handling request: GET /?action=getInfo&version=2.7.1 HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.53 iOS/13.4.1 (iPhone11,2), Host=a.b.c.d, Accept-Encoding=gzip, Content-Type=application/x-www-form-urlencoded}
2020-04-19 13:27:24 TRACE ZeroconfServer:433 - Handling request: POST / HTTP/1.1, headers: {Keep-Alive=0, Connection=keep-alive, User-Agent=Spotify/8.5.53 iOS/13.4.1 (iPhone11,2), Host=a.b.c.d, Accept-Encoding=gzip, Content-Length=667, Content-Type=application/x-www-form-urlencoded}
2020-04-19 13:27:24 DEBUG TimeProvider:73 - Loaded time offset from NTP: 616ms
2020-04-19 13:27:25 INFO  Session:107 - Created new session! {deviceId: [device id], ap: gae2-accesspoint-b-m5z3.ap.spotify.com:4070, proxy: false}
2020-04-19 13:27:25 INFO  ZeroconfServer:329 - Accepted new user from [device]. {deviceId: [device id]}
2020-04-19 13:27:25 INFO  Session:277 - Connected successfully!
2020-04-19 13:27:26 FATAL ZeroconfServer:398 - Failed handling addUser!
java.io.FileNotFoundException: .\cache\journal.dat (Access is denied)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(Unknown Source)
        at java.io.RandomAccessFile.<init>(Unknown Source)
        at xyz.gianlu.librespot.cache.CacheJournal.<init>(CacheJournal.java:34)
        at xyz.gianlu.librespot.cache.CacheManager.<init>(CacheManager.java:46)
        at xyz.gianlu.librespot.core.Session.authenticate(Session.java:295)
        at xyz.gianlu.librespot.core.ZeroconfServer.handleAddUser(ZeroconfServer.java:332)
        at xyz.gianlu.librespot.core.ZeroconfServer.access$100(ZeroconfServer.java:38)
        at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.handleRequest(ZeroconfServer.java:396)
        at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.handle(ZeroconfServer.java:471)
        at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.lambda$run$1(ZeroconfServer.java:379)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
2020-04-19 13:29:30 WARN  Session:975 - Socket timed out. Reconnecting...
2020-04-19 13:29:31 INFO  Session:277 - Connected successfully!
2020-04-19 13:29:31 INFO  Session:598 - Re-authenticated as [username]!
2020-04-19 13:29:31 DEBUG ZeroconfServer:268 - Dropped connection attempt because user is already connected. {username: [username]}
2020-04-19 13:29:31 DEBUG ZeroconfServer:268 - Dropped connection attempt because user is already connected. {username: [username]}
2020-04-19 13:29:31 DEBUG ZeroconfServer:268 - Dropped connection attempt because user is already connected. {username: [username]}
2020-04-19 13:29:31 INFO  Session:1023 - Skipping SecretBlock
2020-04-19 13:29:31 INFO  Session:1002 - Received LicenseVersion: 0
2020-04-19 13:29:31 INFO  Session:992 - Received CountryCode: AU
2020-04-19 13:29:31 INFO  Session:1023 - Skipping ProductInfo
2020-04-19 13:29:31 INFO  Session:1023 - Skipping LegacyWelcome
2020-04-19 13:29:32 INFO  Session:1023 - Skipping UnknownData_AllZeros
2020-04-19 13:29:32 TRACE MercuryClient:176 - Handling packet, cmd: MercuryEvent, seq: 99997284011343872, flags: 1, parts: 1
2020-04-19 13:29:32 DEBUG Session:1006 - Received 0x10: 75266817823F1B38787AC35CA5D2B94B7050EE3F
2020-04-19 13:29:32 INFO  Session:957 - Skipping unknown command {cmd: 0x75, payload: 000000}
2020-04-19 13:29:32 DEBUG MercuryClient:209 - Couldn't dispatch Mercury event {seq: 99997284011343872, uri: [uri] code: 200, payload: []}
2020-04-19 13:29:45 DEBUG ZeroconfServer:268 - Dropped connection attempt because user is already connected. {username: [username]}
2020-04-19 13:29:47 DEBUG ZeroconfServer:268 - Dropped connection attempt because user is already connected. {username: [username]}`

**Comment by devgianlu** [comment]
I've made some changes to allow reconnection from the same username if the device is not active (which hopefully is toggled). You can build from `dev`.

**Comment by benturnberg** [comment]
Awesome, thank you. Will take a look.

**Comment by benturnberg** [comment]
Quickly compiled and tested - seems to be working (though haven't tested extensively). Thanks again!

**Comment by devgianlu** [comment]
Close the issue whenever you think it is working properly.

**Comment by funtax** [comment]
@devgianlu Are you sure this code is "correct"?
For me it look like either there's a "return" required as before, or the else-block has to be adjusted:
`if (hasActiveSession() && System.currentTimeMillis() - connectionTime > TimeUnit.SECONDS.toMillis(60)) {
            if (session.username().equals(username)) {
                LOGGER.debug(String.format("Dropped connection attempt because user is already connected. {username: %s}", session.username()));
            } else {
                session.close();
                LOGGER.trace(String.format("Closed previous session to accept new. {deviceId: %s}", session.deviceId()));
            }
        }`

**Comment by devgianlu** [comment]
@funtax You are right.

**Comment by funtax** [comment]
@devgianlu Are you sure we should report "activeUser" only in case there's an active playback? I checked the getInfo of my Sonos and a Pioneer AVR and both reported my username as "activeUser" even the devices have no active playback.

Don't know :)

**Comment by devgianlu** [comment]
That's news to me because I don't have any Spotify Connect device to test it with. Will change it tomorrow.

**Comment by funtax** [comment]
![Pioneer-getInfo](https://user-images.githubusercontent.com/419376/79804386-348f5b80-8364-11ea-9baa-03182b653bb3.jpg)
![Sonos-getInfo](https://user-images.githubusercontent.com/419376/79804390-3527f200-8364-11ea-8c9a-36d1c4776411.jpg)

**Comment by funtax** [comment]
![Pioneer-getInfo](https://user-images.githubusercontent.com/419376/79804519-7c15e780-8364-11ea-8356-90e4450e1f8a.jpg)
![Sonos-getInfo](https://user-images.githubusercontent.com/419376/79804524-7cae7e00-8364-11ea-9208-18f45431e3fa.jpg)

**Comment by devgianlu** [comment]
@benturnberg Did you experience any issue with this?

**Comment by benturnberg** [comment]
No issues so far. Will close this - thanks again.
