### ISSUE TITLE
Double connect 

### ISSUE THREAD

**Issue by paulbastian** [librespot-org/librespot-java#229]
Hello again :)
I was testing the newest SNAPSHOT and the following behaviour occured.
It seems like incoming commands are handled twice?
At some point nothing is happening when I try to connect with my phone, so I aborted with CTRL-C

```
java -jar librespot-core-1.4.0-20200512.163827-25-jar-with-dependencies.jar 
2020-05-13 19:47:22,811 INFO  Utils:73 - Cryptography restrictions removal not needed.
2020-05-13 19:47:23,434 INFO  ApResolver:68 - Loaded aps into pool: {accesspoint=[gew1-accesspoint-b-dvv4.ap.spotify.com:4070, gew1-accesspoint-b-dmwz.ap.spotify.com:443, gew1-accesspoint-c-mxmn.ap.spotify.com:80, gew1-accesspoint-b-wpqk.ap.spotify.com:4070, gew1-accesspoint-b-fvcr.ap.spotify.com:443, gew1-accesspoint-b-wcs6.ap.spotify.com:80, guc3-accesspoint-b-sv6r.ap.spotify.com:4070, guc3-accesspoint-b-fqrg.ap.spotify.com:443, gae2-accesspoint-b-1thz.ap.spotify.com:80], dealer=[gew-dealer.spotify.com:443, gae-dealer.spotify.com:443, guc-dealer.spotify.com:443], spclient=[gew-spclient.spotify.com:443, guc-spclient.spotify.com:443, gae-spclient.spotify.com:443]}
2020-05-13 19:47:25,149 INFO  ZeroconfServer:371 - Zeroconf HTTP server started successfully on port 9210!
2020-05-13 19:47:26,926 INFO  Zeroconf:473 - Announced Service{alias='librespot-java', service='spotify-connect', port=9210, text={VERSION=1.0, CPath=/, Stack=SP}, addresses=[/192.168.2.201], domain='.local', protocol='tcp', host='soundpi1'}.
2020-05-13 19:47:42,416 DEBUG TimeProvider:74 - Loaded time offset from NTP: 13ms
2020-05-13 19:47:47,183 DEBUG TimeProvider:74 - Loaded time offset from NTP: 13ms
2020-05-13 19:47:49,170 INFO  Session:125 - Created new session! {deviceId: 6c04f5df9d2acb6ff1374cf1a234bede69866ce1, ap: gae2-accesspoint-b-1thz.ap.spotify.com:80, proxy: false} 
2020-05-13 19:47:49,170 INFO  Session:125 - Created new session! {deviceId: 6c04f5df9d2acb6ff1374cf1a234bede69866ce1, ap: gew1-accesspoint-b-wcs6.ap.spotify.com:80, proxy: false} 
2020-05-13 19:47:49,172 INFO  ZeroconfServer:312 - Accepted new user from SM-G965F. {deviceId: 6c04f5df9d2acb6ff1374cf1a234bede69866ce1}
2020-05-13 19:47:49,172 INFO  ZeroconfServer:312 - Accepted new user from SM-G965F. {deviceId: 6c04f5df9d2acb6ff1374cf1a234bede69866ce1}
^C2020-05-13 19:48:21,141 INFO  Session:431 - Closing session. {deviceId: 6c04f5df9d2acb6ff1374cf1a234bede69866ce1}
2020-05-13 19:48:21,146 INFO  Session:495 - Closed session. {deviceId: 6c04f5df9d2acb6ff1374cf1a234bede69866ce1} 
2020-05-13 19:48:21,147 FATAL ZeroconfServer:400 - Failed handling addUser!
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_242]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_242]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_242]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_242]
	at java.net.SocketInputStream.read(SocketInputStream.java:224) ~[?:1.8.0_242]
	at java.io.DataInputStream.readInt(DataInputStream.java:387) ~[?:1.8.0_242]
	at xyz.gianlu.librespot.core.Session.connect(Session.java:240) ~[librespot-core-1.4.0-20200512.163827-25-jar-with-dependencies.jar:1.4.0-SNAPSHOT]
	at xyz.gianlu.librespot.core.ZeroconfServer.handleAddUser(ZeroconfServer.java:314) ~[librespot-core-1.4.0-20200512.163827-25-jar-with-dependencies.jar:1.4.0-SNAPSHOT]
	at xyz.gianlu.librespot.core.ZeroconfServer.access$100(ZeroconfServer.java:39) ~[librespot-core-1.4.0-20200512.163827-25-jar-with-dependencies.jar:1.4.0-SNAPSHOT]
	at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.handleRequest(ZeroconfServer.java:398) ~[librespot-core-1.4.0-20200512.163827-25-jar-with-dependencies.jar:1.4.0-SNAPSHOT]
	at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.handle(ZeroconfServer.java:473) ~[librespot-core-1.4.0-20200512.163827-25-jar-with-dependencies.jar:1.4.0-SNAPSHOT]
	at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.lambda$run$1(ZeroconfServer.java:381) ~[librespot-core-1.4.0-20200512.163827-25-jar-with-dependencies.jar:1.4.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
2020-05-13 19:48:21,152 FATAL ZeroconfServer:400 - Failed handling addUser!
java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_242]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_242]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_242]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_242]
	at java.net.SocketInputStream.read(SocketInputStream.java:224) ~[?:1.8.0_242]
	at java.io.DataInputStream.readInt(DataInputStream.java:387) ~[?:1.8.0_242]
	at xyz.gianlu.librespot.core.Session.connect(Session.java:240) ~[librespot-core-1.4.0-20200512.163827-25-jar-with-dependencies.jar:1.4.0-SNAPSHOT]
	at xyz.gianlu.librespot.core.ZeroconfServer.handleAddUser(ZeroconfServer.java:314) ~[librespot-core-1.4.0-20200512.163827-25-jar-with-dependencies.jar:1.4.0-SNAPSHOT]
	at xyz.gianlu.librespot.core.ZeroconfServer.access$100(ZeroconfServer.java:39) ~[librespot-core-1.4.0-20200512.163827-25-jar-with-dependencies.jar:1.4.0-SNAPSHOT]
	at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.handleRequest(ZeroconfServer.java:398) ~[librespot-core-1.4.0-20200512.163827-25-jar-with-dependencies.jar:1.4.0-SNAPSHOT]
	at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.handle(ZeroconfServer.java:473) ~[librespot-core-1.4.0-20200512.163827-25-jar-with-dependencies.jar:1.4.0-SNAPSHOT]
	at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.lambda$run$1(ZeroconfServer.java:381) ~[librespot-core-1.4.0-20200512.163827-25-jar-with-dependencies.jar:1.4.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

```

Thanks for your help, I appreciate your dedication to this project

**Comment by devgianlu** [comment]
I really can't understand why the request is sent twice. I've made yet another tweak as I am unable to test it (let me know). 

I hope I don't have to make an horrible workaround with the connection time and refuse all requests after let's say 5 seconds.

**Comment by devgianlu** [comment]
Should be fixed now.

**Comment by paulbastian** [comment]
This seems to have done the job, signaling he recognized the double attempt: `wamvxztrfpcomxphv6401as55 is already trying to connect.`

Full log:
```
java -jar librespot-core-1.4.0-20200515.174438-31-jar-with-dependencies.jar 
2020-05-15 18:10:36,856 INFO  Utils:73 - Cryptography restrictions removal not needed.
2020-05-15 18:10:39,185 INFO  ApResolver:68 - Loaded aps into pool: {accesspoint=[gew1-accesspoint-b-1ts2.ap.spotify.com:4070, gew1-accesspoint-b-glrq.ap.spotify.com:443, gew1-accesspoint-b-slc1.ap.spotify.com:80, gew1-accesspoint-b-qzj5.ap.spotify.com:4070, gew1-accesspoint-b-kkvw.ap.spotify.com:443, gew1-accesspoint-b-5rqx.ap.spotify.com:80, guc3-accesspoint-b-x5m6.ap.spotify.com:4070, guc3-accesspoint-b-9459.ap.spotify.com:443, guc3-accesspoint-b-1m34.ap.spotify.com:80], dealer=[gew-dealer.spotify.com:443, guc-dealer.spotify.com:443, gae-dealer.spotify.com:443], spclient=[gew-spclient.spotify.com:443, guc-spclient.spotify.com:443, gae-spclient.spotify.com:443]}
2020-05-15 18:10:40,906 INFO  ZeroconfServer:413 - Zeroconf HTTP server started successfully on port 8421!
2020-05-15 18:10:42,673 INFO  Zeroconf:473 - Announced Service{alias='librespot-java', service='spotify-connect', port=8421, text={VERSION=1.0, CPath=/, Stack=SP}, addresses=[/192.168.2.201], domain='.local', protocol='tcp', host='soundpi1'}.
2020-05-15 18:20:47,142 DEBUG TimeProvider:74 - Loaded time offset from NTP: 15ms
2020-05-15 18:20:50,043 INFO  ZeroconfServer:280 - wamvxztrfpcomxphv6401as55 is already trying to connect.
2020-05-15 18:20:53,873 INFO  Session:125 - Created new session! {deviceId: bfead30cf536b8e16c86c4959beff31a4734ff73, ap: guc3-accesspoint-b-1m34.ap.spotify.com:80, proxy: false} 
2020-05-15 18:20:53,875 INFO  ZeroconfServer:345 - Accepted new user from SM-G965F. {deviceId: bfead30cf536b8e16c86c4959beff31a4734ff73}
2020-05-15 18:20:56,950 INFO  Session:323 - Connected successfully!
2020-05-15 18:20:57,762 INFO  CacheManager:72 - There are 9 cached entries.
2020-05-15 18:20:57,953 INFO  Session:1205 - Skipping SecretBlock
2020-05-15 18:20:57,957 INFO  Session:1177 - Received LicenseVersion: 0
2020-05-15 18:20:57,961 INFO  Session:1167 - Received CountryCode: DE
2020-05-15 18:20:58,252 INFO  Session:1205 - Skipping LegacyWelcome
2020-05-15 18:20:58,256 INFO  Session:1205 - Skipping UnknownData_AllZeros
2020-05-15 18:20:58,270 DEBUG Session:1181 - Received 0x10: 07102E901E55F8CA2587377C68DF374DB3549569
2020-05-15 18:20:58,274 INFO  Session:1132 - Skipping unknown command {cmd: 0x75, payload: 000000}
2020-05-15 18:20:58,294 DEBUG EventService:48 - Event sent. {body: 812|1|en, result: 200}
2020-05-15 18:20:58,295 DEBUG MercuryClient:216 - Couldn't dispatch Mercury event {seq: -4216993229893009408, uri: hm://pusher/v1/connections/YmZlYWQzMGNmNTM2YjhlMTZjODZjNDk1OWJlZmYzMWE0NzM0ZmY3MytBUCt0Y3A6Ly9ndWMzLWFjY2Vzc3BvaW50LWItMW0zNC5ndWMzLnNwb3RpZnkubmV0OjUwMDIrNzEyMjNGNUU3MURFNzM5MkQwNzBDNTZEOEExMEEwNjA4NUM3RkExRUQ4Q0Y0RDcyNjU0N0UzRTcxMDc5NDMwNA%3D%3D, code: 200, payload: []}
2020-05-15 18:20:59,635 DEBUG TokenProvider:49 - Token expired or not suitable, requesting again. {scopes: [playlist-read], oldToken: null}
2020-05-15 18:21:00,004 DEBUG TokenProvider:53 - Updated token successfully! {scopes: [playlist-read], newToken: StoredToken{expiresIn=3600, accessToken='BQBQHowPJ2[truncated]', scopes=[playlist-read], timestamp=1589566860016}}
2020-05-15 18:21:00,199 INFO  Session:356 - Authenticated as wamvxztrfpcomxphv6401as55!
2020-05-15 18:21:05,395 DEBUG DealerClient:316 - Dealer connected! {host: gae-dealer.spotify.com}
2020-05-15 18:21:05,622 DEBUG DeviceStateHandler:133 - Updated Spotify-Connection-Id: YmZlYWQzMGNmNTM2YjhlMTZjODZjNDk1OWJlZmYzMWE0NzM0ZmY3MytkZWFsZXIrdGNwOi8vZ2FlMi1kZWFsZXItYi00dGQ4LmdhZTIuc3BvdGlmeS5uZXQ6NTcwMCtCMzE0MTUzODIyNjM5OTAyMDlDNTMxMzlCQ0Y2MDY4MkMxQzA1OUIyQUY1RTUyOUJGQTQzNDg4NkZBMEEwMjU5
2020-05-15 18:21:05,819 INFO  StateWrapper:305 - Notified new device (us)!
2020-05-15 18:21:09,537 INFO  DeviceStateHandler:251 - Put state. {ts: 1589566865782, connId: YmZlYW[truncated], reason: NEW_DEVICE}
```
