### ISSUE TITLE
Reconnecting multiple times and unknown command 0x75

### ISSUE THREAD

**Issue by paulbastian** [librespot-org/librespot-java#230]
Hello again:)
I am running the latest release here 1.31.
After fixing the sound mixer issues with java-headful I am running into the next problem:
Initial connection seems successful, then however the log says that the token expired and he tried connecting again, this occurs several times and also results in a NullPointerException once, then also an unknown command with code 0x75 is incoming.
It seems he switched but it seems buggy on the phone, and no sound happening.
Could you have a look at the log, any thing I could do to help?

```
java -jar librespot-core-jar-with-dependencies.jar 
2020-05-13 19:48:39,559 [main] INFO  Utils:73 - Cryptography restrictions removal not needed.
2020-05-13 19:48:40,261 [main] INFO  ApResolver:66 - Loaded aps into pool: {accesspoint=[gew1-accesspoint-b-k55w.ap.spotify.com:4070, gew1-accesspoint-b-pfkc.ap.spotify.com:443, gew1-accesspoint-b-7tlq.ap.spotify.com:80, gew1-accesspoint-b-c19m.ap.spotify.com:4070, gew1-accesspoint-b-9gvw.ap.spotify.com:443, gew1-accesspoint-c-dtl1.ap.spotify.com:80, guc3-accesspoint-b-x9qk.ap.spotify.com:4070, guc3-accesspoint-b-76zr.ap.spotify.com:443, guc3-accesspoint-b-rczk.ap.spotify.com:80], dealer=[gew-dealer.spotify.com:443, guc-dealer.spotify.com:443, gae-dealer.spotify.com:443], spclient=[gew-spclient.spotify.com:443, guc-spclient.spotify.com:443, gae-spclient.spotify.com:443]}
2020-05-13 19:48:42,001 [main] INFO  ZeroconfServer:383 - Zeroconf HTTP server started successfully on port 50836!
2020-05-13 19:48:43,661 [main] INFO  Zeroconf:456 - Announced service: Service{alias='librespot-java', service='spotify-connect', port=50836, text={VERSION=1.0, CPath=/, Stack=SP}, addresses=[/192.168.2.201], domain='.local', protocol='tcp', host='soundpi1'}
2020-05-13 19:48:50,709 [zeroconf-client-2252113] DEBUG TimeProvider:73 - Loaded time offset from NTP: 14ms
2020-05-13 19:48:57,322 [zeroconf-client-2252113] INFO  Session:122 - Created new session! {deviceId: 832e8bcb2b381a13f3eedf26ada19a32e0f7dfd4, ap: gew1-accesspoint-b-9gvw.ap.spotify.com:443, proxy: false} 
2020-05-13 19:48:57,327 [zeroconf-client-2252113] INFO  ZeroconfServer:343 - Accepted new user from SM-G965F. {deviceId: 832e8bcb2b381a13f3eedf26ada19a32e0f7dfd4}
2020-05-13 19:49:00,094 [zeroconf-client-2252113] INFO  Session:320 - Connected successfully!
2020-05-13 19:49:00,692 [cache-maintenance] INFO  CacheManager:71 - There are 8 cached entries.
2020-05-13 19:49:02,251 [zeroconf-client-2252113] INFO  LineHelper:61 - Available mixers: 'default [default]'
2020-05-13 19:49:03,925 [session-packet-receiver] INFO  Session:1155 - Skipping SecretBlock
2020-05-13 19:49:03,932 [session-packet-receiver] INFO  Session:1127 - Received LicenseVersion: 0
2020-05-13 19:49:03,936 [session-packet-receiver] INFO  Session:1117 - Received CountryCode: DE
2020-05-13 19:49:03,955 [zeroconf-client-2252113] DEBUG TokenProvider:48 - Token expired or not suitable, requesting again. {scopes: [playlist-read], oldToken: null}
2020-05-13 19:49:04,430 [session-packet-receiver] INFO  Session:1155 - Skipping LegacyWelcome
2020-05-13 19:49:04,434 [session-packet-receiver] INFO  Session:1155 - Skipping UnknownData_AllZeros
2020-05-13 19:49:04,508 [session-packet-receiver] DEBUG Session:1131 - Received 0x10: 64BFAE500C1F6A3EE9C312ECACDEA0DF94211A46
2020-05-13 19:49:04,515 [session-packet-receiver] INFO  Session:1082 - Skipping unknown command {cmd: 0x75, payload: 000000}
2020-05-13 19:49:04,547 [handle-packet-28204611] DEBUG MercuryClient:209 - Couldn't dispatch Mercury event {seq: 7925816374683762688, uri: hm://pusher/v1/connections/ODMyZThiY2IyYjM4MWExM2YzZWVkZjI2YWRhMTlhMzJlMGY3ZGZkNCtBUCt0Y3A6Ly9nZXcxLWFjY2Vzc3BvaW50LWItOWd2dy5nZXcxLnNwb3RpZnkubmV0OjUwMDMrRTY2RjYwQUIwN0MxQjlBMTk4RDc1RDE3NzlGOThDNkVFNEY2QTUzRjdGODgzQjJGM0UzRTgyM0FCNzY4QUNENA%3D%3D, code: 200, payload: []}
2020-05-13 19:49:04,557 [zeroconf-client-2252113] DEBUG TokenProvider:52 - Updated token successfully! {scopes: [playlist-read], newToken: StoredToken{expiresIn=3600, accessToken='BQBcA2kAYb5EicGuD29d8C8mA4puDMp5ZW74bu0ZvMsyzgNSwmVCbLYESjvnQzwQ-hMCWK3ZunImZ5FAFSY2xv-DBd0pjqXh_7MLOiygyhcF0UKG1VuenWqJtKJzPs2PU2W6_zc3sfw53dx4MDyFxQSeFB3n5HPBSBQLecQraQ-pWAKZzU5-sUkvHf7i1R3va8ylw5aKCUxKHzvZr3hsWTpSOl5tFfS5WQ', scopes=[playlist-read], timestamp=1589399344567}}
2020-05-13 19:49:06,577 [zeroconf-client-2252113] INFO  Session:351 - Authenticated as wamvxztrfpcomxphv6401as55!
2020-05-13 19:49:10,467 [zeroconf-client-2252113] DEBUG TimeProvider:73 - Loaded time offset from NTP: 13ms
2020-05-13 19:49:10,524 [OkHttp https://guc-dealer.spotify.com/...] DEBUG DealerClient:315 - Dealer connected! {host: guc-dealer.spotify.com}
2020-05-13 19:49:10,612 [dealer-worker] DEBUG DeviceStateHandler:134 - Updated Spotify-Connection-Id: ODMyZThiY2IyYjM4MWExM2YzZWVkZjI2YWRhMTlhMzJlMGY3ZGZkNCtkZWFsZXIrdGNwOi8vZ3VjMy1kZWFsZXItYi0yM2ptLmd1YzMuc3BvdGlmeS5uZXQ6NTcwMCs0QTBDOUFBMjQ2MENFREYwRDAxOEUzNDNGNDQ1RDUwRkMyMTJGM0QxRUI0QTI4OUQzRDNBQzREOEFDMjI3NUE2
2020-05-13 19:49:10,823 [dealer-worker] INFO  StateWrapper:267 - Notified new device (us)!
2020-05-13 19:49:12,107 [zeroconf-client-2252113] INFO  Session:122 - Created new session! {deviceId: 832e8bcb2b381a13f3eedf26ada19a32e0f7dfd4, ap: guc3-accesspoint-b-rczk.ap.spotify.com:80, proxy: false} 
2020-05-13 19:49:12,112 [zeroconf-client-2252113] INFO  ZeroconfServer:343 - Accepted new user from SM-G965F. {deviceId: 832e8bcb2b381a13f3eedf26ada19a32e0f7dfd4}
2020-05-13 19:49:14,253 [zeroconf-client-2252113] INFO  Session:320 - Connected successfully!
2020-05-13 19:49:14,564 [cache-maintenance] INFO  CacheManager:71 - There are 8 cached entries.
2020-05-13 19:49:14,654 [zeroconf-client-2252113] INFO  LineHelper:61 - Available mixers: 'default [default]'
2020-05-13 19:49:15,272 [dealer-worker] DEBUG Player:182 - Received command: Transfer
2020-05-13 19:49:15,285 [put-state-worker] INFO  DeviceStateHandler:244 - Put state. {ts: 1589399350778, connId: ODMyZT[truncated], reason: NEW_DEVICE, request: <available for TRACE only>}
Exception in thread "zeroconf-client-7802905" 2020-05-13 19:49:16,320 [zeroconf-client-2252113] DEBUG TokenProvider:48 - Token expired or not suitable, requesting again. {scopes: [playlist-read], oldToken: null}
java.lang.NullPointerException
	at xyz.gianlu.librespot.player.Player.isActive(Player.java:733)
	at xyz.gianlu.librespot.core.Session.isActive(Session.java:607)2020-05-13 19:49:16,325 [session-packet-receiver] INFO  Session:1155 - Skipping SecretBlock

	at xyz.gianlu.librespot.core.ZeroconfServer.hasActiveSession(ZeroconfServer.java:235)
	at xyz.gianlu.librespot.core.ZeroconfServer.access$300(ZeroconfServer.java:39)
	at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.handle(ZeroconfServer.java:446)
	at xyz.gianlu.librespot.core.ZeroconfServer$HttpRunner.lambda$run$1(ZeroconfServer.java:393)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-05-13 19:49:16,334 [session-packet-receiver] INFO  Session:1127 - Received LicenseVersion: 0
2020-05-13 19:49:16,339 [session-packet-receiver] INFO  Session:1117 - Received CountryCode: DE
2020-05-13 19:49:16,599 [session-packet-receiver] INFO  Session:1155 - Skipping LegacyWelcome
2020-05-13 19:49:16,603 [session-packet-receiver] INFO  Session:1155 - Skipping UnknownData_AllZeros
2020-05-13 19:49:16,617 [session-packet-receiver] DEBUG Session:1131 - Received 0x10: AC90BFF1C332C74D709D20895A796A9F5C93C111
2020-05-13 19:49:16,623 [session-packet-receiver] INFO  Session:1082 - Skipping unknown command {cmd: 0x75, payload: 000000}
2020-05-13 19:49:16,628 [handle-packet-14933166] DEBUG MercuryClient:209 - Couldn't dispatch Mercury event {seq: -8867835056408756224, uri: hm://pusher/v1/connections/ODMyZThiY2IyYjM4MWExM2YzZWVkZjI2YWRhMTlhMzJlMGY3ZGZkNCtBUCt0Y3A6Ly9ndWMzLWFjY2Vzc3BvaW50LWItcmN6ay5ndWMzLnNwb3RpZnkubmV0OjUwMjQrMzRCQTBCNDE5NUM5RTYzODRBOUVGRDE1NzZDRUUzNzcwOUFCNTVENTU2RDlBNjExQkEwMDMyOEFERjhEQzQ4MA%3D%3D, code: 200, payload: []}
2020-05-13 19:49:16,737 [zeroconf-client-2252113] DEBUG TokenProvider:52 - Updated token successfully! {scopes: [playlist-read], newToken: StoredToken{expiresIn=3600, accessToken='BQCaYeiBJN_vz3CqUvP7ub-BmjRC_tlgTdJk6lde6_BTip3hAWssFhobpYwxTaCcRVbFZzAKICb1471VE-yxD5848F_rOjpbrNcwLjxhYEDU9TyK7MBqHKxDLKEuG3RWRC2845vy-xKythpJLyx4OgVIQa4vBwORWbtLe28wlRa3RQNmDX8IEAEr_rRRh6QG17s5jHvxkM72MvqI4nG69S6k9Ha5WjSP4w', scopes=[playlist-read], timestamp=1589399356747}}
2020-05-13 19:49:16,748 [dealer-worker] DEBUG Player:136 - Loading context (transfer), uri: spotify:playlist:37i9dQZF1DZ06evO4x1tHd
2020-05-13 19:49:16,772 [zeroconf-client-2252113] INFO  Session:351 - Authenticated as wamvxztrfpcomxphv6401as55!
2020-05-13 19:49:16,911 [dealer-worker] DEBUG DeviceStateHandler:192 - Device is now active. {ts: 1589399356923}
2020-05-13 19:49:17,967 [dealer-worker] DEBUG DealerClient:107 - Handled request. {key: 1f7db503-85ba-4b84-8144-e15f040d5181, result: SUCCESS}
2020-05-13 19:49:19,892 [OkHttp https://guc-dealer.spotify.com/...] DEBUG DealerClient:315 - Dealer connected! {host: guc-dealer.spotify.com}
2020-05-13 19:49:20,003 [dealer-worker] DEBUG DeviceStateHandler:134 - Updated Spotify-Connection-Id: ODMyZThiY2IyYjM4MWExM2YzZWVkZjI2YWRhMTlhMzJlMGY3ZGZkNCtkZWFsZXIrdGNwOi8vZ3VjMy1kZWFsZXItYi02Mzh6Lmd1YzMuc3BvdGlmeS5uZXQ6NTcwMCs0NEI0NTY3RUNDNDc4MUE1QTk5NzZBNUQwMjAxNDJEOUNEMkUyN0E0NDc2NzlDQzhDODc4QTU4ODM1NEI3QjM1
2020-05-13 19:49:20,022 [dealer-worker] INFO  StateWrapper:267 - Notified new device (us)!
2020-05-13 19:49:22,322 [put-state-worker] INFO  DeviceStateHandler:244 - Put state. {ts: 1589399357763, connId: ODMyZT[truncated], reason: PLAYER_STATE_CHANGED, request: <available for TRACE only>}
2020-05-13 19:49:23,069 [put-state-worker] INFO  DeviceStateHandler:244 - Put state. {ts: 1589399360023, connId: ODMyZT[truncated], reason: NEW_DEVICE, request: <available for TRACE only>}
2020-05-13 19:49:23,235 [dealer-worker] DEBUG DeviceStateHandler:159 - Received cluster update at 1589399363245: <available for TRACE only>
2020-05-13 19:49:26,825 [put-state-worker] INFO  DeviceStateHandler:244 - Put state. {ts: 1589399357900, connId: ODMyZT[truncated], reason: PLAYER_STATE_CHANGED, request: <available for TRACE only>}
2020-05-13 19:49:34,203 [dealer-worker] DEBUG DeviceStateHandler:159 - Received cluster update at 1589399374214: <available for TRACE only>
2020-05-13 19:49:41,062 [dealer-worker] DEBUG DeviceStateHandler:159 - Received cluster update at 1589399381073: <available for TRACE only>
2020-05-13 19:49:42,547 [player-runner-looper] INFO  PlayerRunner:592 - Loaded track, name: 'Atoms For Peace (Four Tet Remix)', artists: 'Thom Yorke, Four Tet', gid: 504F452A2E6E448983CABB1A3A49F33B
2020-05-13 19:49:42,572 [player-runner-looper] DEBUG CrossfadeController:84 - Loaded intervals. {start: null, end: null}
2020-05-13 19:49:43,913 [dealer-worker] DEBUG DeviceStateHandler:159 - Received cluster update at 1589399383923: <available for TRACE only>
2020-05-13 19:49:44,569 [cdn-async-14087317] DEBUG Player:384 - Playback halted on retrieving chunk 31.
2020-05-13 19:49:45,351 [put-state-worker] INFO  DeviceStateHandler:244 - Put state. {ts: 1589399383533, connId: ODMyZT[truncated], reason: PLAYER_STATE_CHANGED, request: <available for TRACE only>}
2020-05-13 19:49:47,322 [put-state-worker] INFO  DeviceStateHandler:244 - Put state. {ts: 1589399384648, connId: ODMyZT[truncated], reason: PLAYER_STATE_CHANGED, request: <available for TRACE only>}
2020-05-13 19:50:23,355 [dealer-worker] DEBUG DeviceStateHandler:159 - Received cluster update at 1589399423366: <available for TRACE only>
^C2020-05-13 19:50:23,522 [Thread-0] INFO  Session:426 - Closing session. {deviceId: 832e8bcb2b381a13f3eedf26ada19a32e0f7dfd4} 
2020-05-13 19:50:23,566 [Thread-0] DEBUG DealerClient:303 - Did not dispatch connection invalidated: null != xyz.gianlu.librespot.dealer.DealerClient$ConnectionHolder@155cbf3
2020-05-13 19:50:23,576 [Thread-0] INFO  Session:480 - Closed session. {deviceId: 832e8bcb2b381a13f3eedf26ada19a32e0f7dfd4} 
2020-05-13 19:50:23,957 [Thread-0] INFO  Zeroconf:483 - Unannounced service. Service{alias='librespot-java', service='spotify-connect', port=50836, text={VERSION=1.0, CPath=/, Stack=SP}, addresses=[/192.168.2.201], domain='.local', protocol='tcp', host='soundpi1'}
```

**Comment by devgianlu** [comment]
Everything looks fine here except for the NPE. Closing.
