### ISSUE TITLE
USER_PASS fails without network - java.net.UnknownHostException: apresolve.spotify.com

### ISSUE THREAD

**Issue by freelancer1845** [librespot-org/librespot-java#237]
**Describe the bug**
I'm using the USER_PASS option. The application fails if internet is N/A.
In my case I'm starting the jar using a systemd service on a raspberry pi. The pi is connected using wifi. Sometimes the wifi connection isn't immediately available resulting in the UnkownHostException given below.

My current solution is to wait for network-online.target and restart service if it fails.

**To Reproduce**
Start the jar without internet.

**Expected behavior**
I don't know if you want to add a retry mechanism. Maybe this is the expected behavior...

(Maybe a log entry that connection to the spotify api failed)

The output of the systemd service is given below.

**Screenshots/Stracktraces/Logs**
```
● spotify.service - Spotify Connect Service using librespot-java implementation
   Loaded: loaded (/etc/systemd/system/spotify.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-06-11 11:25:45 BST; 1min 27s ago
  Process: 357 ExecStart=/usr/bin/java -jar /home/pi/librespot-binary/librespot-core-jar-with-dependencies.jar (code=exited, status=1/FAILURE)
 Main PID: 357 (code=exited, status=1/FAILURE)

Jun 11 11:25:42 rp-4-0 systemd[1]: Started Spotify Connect Service using librespot-java implementation.
Jun 11 11:25:45 rp-4-0 java[357]: Exception in thread "main" java.net.UnknownHostException: apresolve.spotify.com
Jun 11 11:25:45 rp-4-0 java[357]:         at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
Jun 11 11:25:45 rp-4-0 java[357]:         at java.base/java.net.Socket.connect(Socket.java:609)
Jun 11 11:25:45 rp-4-0 java[357]:         at java.base/java.net.Socket.connect(Socket.java:558)
Jun 11 11:25:45 rp-4-0 java[357]:         at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
Jun 11 11:25:45 rp-4-0 java[357]:         at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
Jun 11 11:25:45 rp-4-0 java[357]:         at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
Jun 11 11:25:45 rp-4-0 java[357]:         at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
Jun 11 11:25:45 rp-4-0 java[357]:         at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
Jun 11 11:25:45 rp-4-0 java[357]:         at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
Jun 11 11:25:45 rp-4-0 java[357]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1248)
Jun 11 11:25:45 rp-4-0 java[357]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
Jun 11 11:25:45 rp-4-0 java[357]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
Jun 11 11:25:45 rp-4-0 java[357]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
Jun 11 11:25:45 rp-4-0 java[357]:         at xyz.gianlu.librespot.core.ApResolver.request(ApResolver.java:52)
Jun 11 11:25:45 rp-4-0 java[357]:         at xyz.gianlu.librespot.core.ApResolver.fillPool(ApResolver.java:30)
Jun 11 11:25:45 rp-4-0 java[357]:         at xyz.gianlu.librespot.core.Session.from(Session.java:190)
Jun 11 11:25:45 rp-4-0 java[357]:         at xyz.gianlu.librespot.core.Session$Builder.create(Session.java:954)
Jun 11 11:25:45 rp-4-0 java[357]:         at xyz.gianlu.librespot.Main.main(Main.java:30)
Jun 11 11:25:45 rp-4-0 systemd[1]: spotify.service: Main process exited, code=exited, status=1/FAILURE
```

**Systemd file without any fix**
```
[Unit]
Description=Spotify Connect Service using librespot-java implementation

[Service]
Type=simple
ExecStart=/usr/bin/java -jar /home/pi/librespot-binary/librespot-core-jar-with-dependencies.jar
User=pi
WorkingDirectory=/home/pi/librespot-binary

[Install]
WantedBy=multi-user.target
```
**Version/Commit**
1.3.1

**Comment by devgianlu** [comment]
You can solve this issue by checking that the connection is available before starting the service. Something like this will do:

```
ExecStartPre=/bin/sh -c 'until ping -c1 spotify.com; do sleep 5; done;'
```

[source](https://github.com/spocon/spocon/blob/master/Ansible/roles/spocon/templates/spocon.service)

**Comment by freelancer1845** [comment]
Ah that looks good. Thanks for the source too :)

It's just that for me executing the jar felt like running a service that would take care of things like that itself (unstable internet connection). That's why I created the issue initially. 

But I guess allowing an unstable internet connection would need more work than just catching startup errors?

If helpful/wanted I'd like to contribute

**Comment by devgianlu** [comment]
> But I guess allowing an unstable internet connection would need more work than just catching startup errors?

Connection problems are already handled (more or less properly) once the first connection has been established. I think it is not that useful to add code to retry an operation that crashes the program, you could add a retry mechanism externally.
