### ISSUE TITLE
NPE in player-audio-sink (AudioSink.java)

### ISSUE THREAD

**Issue by ktzouno** [librespot-org/librespot-java#238]
Hello, this NPE occurred when disconnected a usb-interface from RPi. I tried to re-produce it 2-3 times, but didn't occur again.

```
Jun 14 09:49:31 raspberrypi java[5843]: 2020-06-14 09:49:31,728 FATAL Log4JUncaughtExceptionHandler:15 - [player-audio-sink]
Jun 14 09:49:31 raspberrypi java[5843]: java.lang.NullPointerException: null
Jun 14 09:49:31 raspberrypi java[5843]:         at xyz.gianlu.librespot.player.mixing.AudioSink$Output.write(AudioSink.java:229) ~[librespot-core-jar-with-dependencies.jar:1.4.0-SNAPSHOT]
Jun 14 09:49:31 raspberrypi java[5843]:         at xyz.gianlu.librespot.player.mixing.AudioSink.run(AudioSink.java:152) ~[librespot-core-jar-with-dependencies.jar:1.4.0-SNAPSHOT]
Jun 14 09:49:31 raspberrypi java[5843]:         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

Version: compiled from source - latest `dev` branch.

**Comment by devgianlu** [comment]
A simple null-check should do the job.
