### ISSUE TITLE
Failed fetching audio key when loading new track

### ISSUE THREAD

**Issue by Justus-G** [librespot-org/librespot-java#268]
**Bug description**
Can't play certain tracks, seems to be random. The exception shown down below is being thrown. ("Failed fetching audio key")
The .jar is running inside a docker container with passthrough of "/dev/snd" from the docker host for being able to output sound to the external USB soundcard, if this is any relevant.

**Expected behavior**
Expected that the selected song would play instantly.

**Stracktraces/Logs**

```
2020-11-27 11:14:45,503 TRACE CdnManager:261 - Chunk 64/65 completed, cached: false, stream: {fileId: 00649BCB75A7F9FAA38A7CD645FA662CA62F8C3B}
2020-11-27 11:14:56,078 TRACE PlayerQueueEntry:76 - Created new PlayerQueueEntry{01a9567ec3e025a584f30f254138e37d}."
2020-11-27 11:14:56,078 TRACE PlayerSession:146 - PlayerQueueEntry{01a9567ec3e025a584f30f254138e37d} started loading."
2020-11-27 11:14:56,079 TRACE PlayerQueue:66 - PlayerQueueEntry{01a9567ec3e025a584f30f254138e37d} added to queue."
2020-11-27 11:14:56,081 DEBUG CrossfadeController:176 - Changed fade out. {curr: FadeInterval{start=204529, duration=3000, interpolator=xyz.gianlu.librespot.player.crossfade.LinearDecreasingInterpolator@73711e96}, custom: false, why: TRACK_DONE, id: 012bb8fca79715e9c1cfa9d34e545619}"
2020-11-27 11:14:56,082 DEBUG CrossfadeController:176 - Changed fade out. {curr: FadeInterval{start=204529, duration=3000, interpolator=xyz.gianlu.librespot.player.crossfade.LinearDecreasingInterpolator@73711e96}, custom: false, why: TRACK_DONE, id: 012bb8fca79715e9c1cfa9d34e545619}"
2020-11-27 11:14:56,083 DEBUG PlayerSession:267 - PlayerQueueEntry{01a9567ec3e025a584f30f254138e37d} has been added to the output. {sessionId: <sessionID>, pos: 0, reason: TRACK_DONE}"
2020-11-27 11:14:56,092 TRACE MercuryClient:138 - Send Mercury request, seq: 8, uri: hm://event-service/v1/events, method: POST"
2020-11-27 11:14:56,120 TRACE PlayerQueueEntry:76 - Created new PlayerQueueEntry{012822ee9a91a55fd089a9dfe7129f96}."
2020-11-27 11:14:56,121 TRACE PlayerQueue:66 - PlayerQueueEntry{012822ee9a91a55fd089a9dfe7129f96} added to queue."
2020-11-27 11:14:56,122 TRACE PlayerSession:146 - PlayerQueueEntry{012822ee9a91a55fd089a9dfe7129f96} started loading."
2020-11-27 11:14:56,122 DEBUG PlayerQueueEntry:209 - PlayerQueueEntry{01a9567ec3e025a584f30f254138e37d} has been removed from output."
2020-11-27 11:14:56,123 DEBUG PlayerSession:267 - PlayerQueueEntry{012822ee9a91a55fd089a9dfe7129f96} has been added to the output. {sessionId: <sessionID>, pos: 0, reason: TRACK_DONE}"
2020-11-27 11:14:56,180 TRACE MercuryClient:181 - Handling packet, cmd: MercuryReq, seq: 8, flags: 1, parts: 1"
2020-11-27 11:14:56,180 DEBUG EventService:35 - Event sent. {body: 558|1|01a9567ec3e025a584f30f254138e37d|<sessionID>|1606475696086, result: 200}"
2020-11-27 11:14:56,182 TRACE MercuryClient:138 - Send Mercury request, seq: 9, uri: hm://event-service/v1/events, method: POST"
2020-11-27 11:14:56,268 TRACE MercuryClient:181 - Handling packet, cmd: MercuryReq, seq: 9, flags: 1, parts: 1"
2020-11-27 11:14:56,269 DEBUG EventService:35 - Event sent. {body: 558|1|012822ee9a91a55fd089a9dfe7129f96|<sessionID>|1606475696140, result: 200}"
2020-11-27 11:14:56,718 TRACE MercuryClient:138 - Send Mercury request, seq: 10, uri: hm://event-service/v1/events, method: POST"
2020-11-27 11:14:56,804 TRACE MercuryClient:181 - Handling packet, cmd: MercuryReq, seq: 10, flags: 1, parts: 1"
2020-11-27 11:14:56,805 DEBUG EventService:35 - Event sent. {body: 274|3|2|2|e2f1e8220fe66cf509b9bd576d9d9e2981ed2e79|spotify:track:7v7teR4FtyiZzkc1tX2a4V|1|2|2, result: 200}"
2020-11-27 11:14:56,807 TRACE MercuryClient:138 - Send Mercury request, seq: 11, uri: hm://event-service/v1/events, method: POST"
2020-11-27 11:14:56,839 INFO  DeviceStateHandler:249 - Put state. {ts: 1606475696085, connId: OTNjY...3QkVD, reason: PLAYER_STATE_CHANGED, request: device { device_info { can_play: true volume: 65536 name: \"Esszimmer\" capabilities { can_be_player: true gaia_eq_connect_id: true supports_logout: true is_observable: true volume_steps: 64 supported_types: \"audio/episode\" supported_types: \"audio/track\" command_acks: true supports_playlist_v2: true is_controllable: true supports_transfer_command: true supports_command_request: true supports_gzip_pushes: true } device_software_version: \"librespot-java 1.5.2\" device_type: AVR spirc_version: \"3.2.6\" device_id: \"93cc3e67cf2d87bf7e933fa129488d3310b74d69\" } player_state { timestamp: 1606475696136 ...
2020-11-27 11:14:56,892 TRACE MercuryClient:181 - Handling packet, cmd: MercuryReq, seq: 11, flags: 1, parts: 1"
2020-11-27 11:14:56,893 DEBUG EventService:35 - Event sent. {body: 274|3|2|2|e632bed678c87d3ba0c19683a706cbde1bd5cf09|spotify:track:7xmNhQnKjSU7gQdwfds6mZ|1|2|2, result: 200}"
2020-11-27 11:14:57,249 FATAL AudioKeyManager:116 - Audio key error, code: 1"
2020-11-27 11:14:57,344 FATAL AudioKeyManager:116 - Audio key error, code: 1"
2020-11-27 11:14:57,345 TRACE PlayerQueueEntry:255 - PlayerQueueEntry{01a9567ec3e025a584f30f254138e37d} terminated at loading."
xyz.gianlu.librespot.audio.AudioKeyManager$AesKeyException: Failed fetching audio key! {gid: F67D8315D25A455B86CE2003359B8599, fileId: E2F1E8220FE66CF509B9BD576D9D9E2981ED2E79}"
	at xyz.gianlu.librespot.audio.AudioKeyManager.getAudioKey(AudioKeyManager.java:62) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.AudioKeyManager.getAudioKey(AudioKeyManager.java:61) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.AudioKeyManager.getAudioKey(AudioKeyManager.java:38) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.cdn.CdnFeedHelper.loadTrack(CdnFeedHelper.java:39) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.cdn.CdnFeedHelper.loadTrack(CdnFeedHelper.java:51) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.PlayableContentFeeder.loadStream(PlayableContentFeeder.java:118) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.PlayableContentFeeder.loadTrack(PlayableContentFeeder.java:145) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.PlayableContentFeeder.loadTrack(PlayableContentFeeder.java:93) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.PlayableContentFeeder.load(PlayableContentFeeder.java:62) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.load(PlayerQueueEntry.java:94) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.run(PlayerQueueEntry.java:251) [librespot-player-1.5.2.jar:1.5.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
2020-11-27 11:14:57,539 FATAL AudioKeyManager:116 - Audio key error, code: 1"
2020-11-27 11:14:57,688 FATAL AudioKeyManager:116 - Audio key error, code: 1"
2020-11-27 11:14:57,689 DEBUG PlayerQueueEntry:209 - PlayerQueueEntry{012822ee9a91a55fd089a9dfe7129f96} has been removed from output."
2020-11-27 11:14:57,690 TRACE PlayerQueueEntry:76 - Created new PlayerQueueEntry{01a51a57be2bbac223d478e88198d2b4}."
2020-11-27 11:14:57,692 TRACE PlayerQueueEntry:255 - PlayerQueueEntry{012822ee9a91a55fd089a9dfe7129f96} terminated at loading."
xyz.gianlu.librespot.audio.AudioKeyManager$AesKeyException: Failed fetching audio key! {gid: F7AE60563EE44E0C9ED4629B52E39739, fileId: E632BED678C87D3BA0C19683A706CBDE1BD5CF09}"
	at xyz.gianlu.librespot.audio.AudioKeyManager.getAudioKey(AudioKeyManager.java:62) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.AudioKeyManager.getAudioKey(AudioKeyManager.java:61) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.AudioKeyManager.getAudioKey(AudioKeyManager.java:38) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.cdn.CdnFeedHelper.loadTrack(CdnFeedHelper.java:39) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.cdn.CdnFeedHelper.loadTrack(CdnFeedHelper.java:51) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.PlayableContentFeeder.loadStream(PlayableContentFeeder.java:118) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.PlayableContentFeeder.loadTrack(PlayableContentFeeder.java:145) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.PlayableContentFeeder.loadTrack(PlayableContentFeeder.java:93) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.PlayableContentFeeder.load(PlayableContentFeeder.java:62) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.load(PlayerQueueEntry.java:94) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.run(PlayerQueueEntry.java:251) [librespot-player-1.5.2.jar:1.5.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
2020-11-27 11:14:57,692 TRACE PlayerQueue:91 - PlayerQueueEntry{012822ee9a91a55fd089a9dfe7129f96} swapped with PlayerQueueEntry{01a51a57be2bbac223d478e88198d2b4}."
2020-11-27 11:14:57,693 DEBUG PlayerSession:267 - PlayerQueueEntry{01a51a57be2bbac223d478e88198d2b4} has been added to the output. {sessionId: <sessionID>, pos: 0, reason: TRACK_DONE}"
2020-11-27 11:14:57,693 TRACE PlayerSession:146 - PlayerQueueEntry{01a51a57be2bbac223d478e88198d2b4} started loading."
2020-11-27 11:14:57,735 INFO  DeviceStateHandler:249 - Put state. {ts: 1606475696127, connId: OTNjY...3QkVD, reason: PLAYER_STATE_CHANGED, request: device { device_info { can_play: true volume: 65536 name: \"Esszimmer\" capabilities { can_be_player: true gaia_eq_connect_id: true supports_logout: true is_observable: true volume_steps: 64 supported_types: \"audio/episode\" supported_types: \"audio/track\" command_acks: true supports_playlist_v2: true is_controllable: true supports_transfer_command: true supports_command_request: true supports_gzip_pushes: true } device_software_version: \"librespot-java 1.5.2\" device_type: AVR spirc_version: \"3.2.6\" device_id: \"93cc3e67cf2d87bf7e933fa129488d3310b74d69\" } player_state { timestamp: 1606475696136 ...
2020-11-27 11:14:58,287 TRACE MercuryClient:138 - Send Mercury request, seq: 12, uri: hm://event-service/v1/events, method: POST"
2020-11-27 11:14:58,330 TRACE MercuryClient:181 - Handling packet, cmd: MercuryReq, seq: 12, flags: 1, parts: 1"
2020-11-27 11:14:58,331 DEBUG EventService:35 - Event sent. {body: 274|3|2|2|e632bed678c87d3ba0c19683a706cbde1bd5cf09|spotify:track:7xmNhQnKjSU7gQdwfds6mZ|1|2|2, result: 200}"
2020-11-27 11:14:58,395 DEBUG PlayerQueueEntry:305 - Player time offset is 606. {id: 012bb8fca79715e9c1cfa9d34e545619}"
2020-11-27 11:14:58,396 TRACE MixingLine:169 - Toggle first channel: false"
2020-11-27 11:14:58,396 DEBUG PlayerQueueEntry:209 - PlayerQueueEntry{012bb8fca79715e9c1cfa9d34e545619} has been removed from output."
2020-11-27 11:14:58,406 TRACE MercuryClient:138 - Send Mercury request, seq: 13, uri: hm://event-service/v1/events, method: POST"
2020-11-27 11:14:58,411 TRACE PlayerQueueEntry:325 - PlayerQueueEntry{012bb8fca79715e9c1cfa9d34e545619} terminated."
2020-11-27 11:14:58,489 TRACE MercuryClient:181 - Handling packet, cmd: MercuryReq, seq: 13, flags: 1, parts: 1"
2020-11-27 11:14:58,490 DEBUG EventService:35 - Event sent. {body: 12|37|0|93cc3e67cf2d87bf7e933fa129488d3310b74d69|012bb8fca79715e9c1cfa9d34e545619|00000000000000000000000000000000|playlist-owned-by-self-non-collaborative|clickrow|playlist-owned-by-self-non-collaborative|trackdone|8606880|8475808|206923|206923|207529|2|6000|0|0|1|6463|0|-1|context|420|0|0|0|0|0|206923|206923|0|176400|spotify:user:<username>:playlist:<playlistID>|vorbis|99e64976b4424a56b80d459fc60986b4||0|1606475494550|0|context|spotify:app:playlist|1.1.46|com.spotify|crossfade|none|9cdaf4138d990dd0cd57b1a47b523f700aa438c6|na|none, result: 200}"
2020-11-27 11:14:58,496 TRACE MercuryClient:138 - Send Mercury request, seq: 14, uri: hm://event-service/v1/events, method: POST"
2020-11-27 11:14:58,583 TRACE MercuryClient:181 - Handling packet, cmd: MercuryReq, seq: 14, flags: 1, parts: 1"
2020-11-27 11:14:58,588 DEBUG EventService:35 - Event sent. {body: 10|20|00649bcb75a7f9faa38a7cd645fa662ca62f8c3b|012bb8fca79715e9c1cfa9d34e545619|0|0|0|0|0|0|8606880|8475808|music|-1|-1|-1|-1.000000|-1|-1.000000|-1|-1|-1|-1.000000|-1|-1|-1|-1|-1.000000|-1|0.000000|-1.000000|||unknown|0|0|0|0|0|interactive|0|176400|0|0, result: 200}"
2020-11-27 11:14:58,589 TRACE MercuryClient:138 - Send Mercury request, seq: 15, uri: hm://event-service/v1/events, method: POST"
2020-11-27 11:14:58,677 TRACE MercuryClient:181 - Handling packet, cmd: MercuryReq, seq: 15, flags: 1, parts: 1"
2020-11-27 11:14:58,678 DEBUG EventService:35 - Event sent. {body: 372|1|012bb8fca79715e9c1cfa9d34e545619|spotify:track:4Gp4blkZugUeG37z0fvzwM|0|[[6463,206923]], result: 200}"
2020-11-27 11:14:58,768 FATAL AudioKeyManager:116 - Audio key error, code: 1"
2020-11-27 11:14:58,863 FATAL AudioKeyManager:116 - Audio key error, code: 1"
2020-11-27 11:14:58,864 DEBUG PlayerQueueEntry:209 - PlayerQueueEntry{01a51a57be2bbac223d478e88198d2b4} has been removed from output."
2020-11-27 11:14:58,865 FATAL Player:602 - Failed loading track."
xyz.gianlu.librespot.audio.AudioKeyManager$AesKeyException: Failed fetching audio key! {gid: F7AE60563EE44E0C9ED4629B52E39739, fileId: E632BED678C87D3BA0C19683A706CBDE1BD5CF09}"
	at xyz.gianlu.librespot.audio.AudioKeyManager.getAudioKey(AudioKeyManager.java:62) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.AudioKeyManager.getAudioKey(AudioKeyManager.java:61) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.AudioKeyManager.getAudioKey(AudioKeyManager.java:38) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.cdn.CdnFeedHelper.loadTrack(CdnFeedHelper.java:39) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.cdn.CdnFeedHelper.loadTrack(CdnFeedHelper.java:51) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.PlayableContentFeeder.loadStream(PlayableContentFeeder.java:118) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.PlayableContentFeeder.loadTrack(PlayableContentFeeder.java:145) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.PlayableContentFeeder.loadTrack(PlayableContentFeeder.java:93) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.PlayableContentFeeder.load(PlayableContentFeeder.java:62) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.load(PlayerQueueEntry.java:94) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.run(PlayerQueueEntry.java:251) [librespot-player-1.5.2.jar:1.5.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
2020-11-27 11:14:58,896 TRACE PlayerQueue:113 - PlayerQueueEntry{01a51a57be2bbac223d478e88198d2b4} removed from queue."
2020-11-27 11:14:58,899 TRACE PlayerQueueEntry:255 - PlayerQueueEntry{01a51a57be2bbac223d478e88198d2b4} terminated at loading."
xyz.gianlu.librespot.audio.AudioKeyManager$AesKeyException: Failed fetching audio key! {gid: F7AE60563EE44E0C9ED4629B52E39739, fileId: E632BED678C87D3BA0C19683A706CBDE1BD5CF09}"
	at xyz.gianlu.librespot.audio.AudioKeyManager.getAudioKey(AudioKeyManager.java:62) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.AudioKeyManager.getAudioKey(AudioKeyManager.java:61) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.AudioKeyManager.getAudioKey(AudioKeyManager.java:38) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.cdn.CdnFeedHelper.loadTrack(CdnFeedHelper.java:39) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.cdn.CdnFeedHelper.loadTrack(CdnFeedHelper.java:51) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.PlayableContentFeeder.loadStream(PlayableContentFeeder.java:118) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.PlayableContentFeeder.loadTrack(PlayableContentFeeder.java:145) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.PlayableContentFeeder.loadTrack(PlayableContentFeeder.java:93) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.audio.PlayableContentFeeder.load(PlayableContentFeeder.java:62) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.load(PlayerQueueEntry.java:94) ~[librespot-player-1.5.2.jar:1.5.2]
	at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.run(PlayerQueueEntry.java:251) [librespot-player-1.5.2.jar:1.5.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
2020-11-27 11:14:59,302 INFO  DeviceStateHandler:249 - Put state. {ts: 1606475696137, connId: OTNjY...3QkVD, reason: PLAYER_STATE_CHANGED, request: device { device_info { can_play: true volume: 65536 name: \"Esszimmer\" capabilities { can_be_player: true gaia_eq_connect_id: true supports_logout: true is_observable: true volume_steps: 64 supported_types: \"audio/episode\" supported_types: \"audio/track\" command_acks: true supports_playlist_v2: true is_controllable: true supports_transfer_command: true supports_command_request: true supports_gzip_pushes: true } device_software_version: \"librespot-java 1.5.2\" device_type: AVR spirc_version: \"3.2.6\" device_id: \"93cc3e67cf2d87bf7e933fa129488d3310b74d69\" } player_state { timestamp: 1606475696136 ...
2020-11-27 11:15:00,088 INFO  DeviceStateHandler:249 - Put state. {ts: 1606475697697, connId: OTNjY...3QkVD, reason: PLAYER_STATE_CHANGED, request: device { device_info { can_play: true volume: 65536 name: \"Esszimmer\" capabilities { can_be_player: true gaia_eq_connect_id: true supports_logout: true is_observable: true volume_steps: 64 supported_types: \"audio/episode\" supported_types: \"audio/track\" command_acks: true supports_playlist_v2: true is_controllable: true supports_transfer_command: true supports_command_request: true supports_gzip_pushes: true } device_software_version: \"librespot-java 1.5.2\" device_type: AVR spirc_version: \"3.2.6\" device_id: \"93cc3e67cf2d87bf7e933fa129488d3310b74d69\" } player_state { timestamp: 1606475696136 ...
2020-11-27 11:15:00,856 INFO  DeviceStateHandler:249 - Put state. {ts: 1606475698896, connId: OTNjY...3QkVD, reason: PLAYER_STATE_CHANGED, request: device { device_info { can_play: true volume: 65536 name: \"Esszimmer\" capabilities { can_be_player: true gaia_eq_connect_id: true supports_logout: true is_observable: true volume_steps: 64 supported_types: \"audio/episode\" supported_types: \"audio/track\" command_acks: true supports_playlist_v2: true is_controllable: true supports_transfer_command: true supports_command_request: true supports_gzip_pushes: true } device_software_version: \"librespot-java 1.5.2\" device_type: AVR spirc_version: \"3.2.6\" device_id: \"93cc3e67cf2d87bf7e933fa129488d3310b74d69\" } player_state { timestamp: 1606475696136 ...
```

**Version**
A self-built but unchanged version 1.5.2.

**Comment by Justus-G** [comment]
did not occurr anymore, propably had to do with #269 and is fixed now.
