### ISSUE TITLE
Failure for Podcast episode AddToQueue

### ISSUE THREAD

**Issue by Zageron** [librespot-org/librespot-java#285]
**Describe the bug**

**To Reproduce**
Right click on a podcast episode, click Add to Queue.

**Expected behavior**
Podcast episode should be added to queue.

**Screenshots/Stracktraces/Logs**
```zsh
Jan 01 01:24:17 spotipi java[6660]: 2021-01-01 01:24:17,019 DEBUG Player:293 - Received command: SetQueue
Jan 01 01:24:17 spotipi java[6660]: 2021-01-01 01:24:17,038 ERROR DealerClient:112 - Failed handling request. {key: 8f589598-a245-4dc8-b57b-5aab3fec6b22}
Jan 01 01:24:17 spotipi java[6660]: java.lang.IndexOutOfBoundsException: Index 521 out of bounds for length 26
Jan 01 01:24:17 spotipi java[6660]:         at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
Jan 01 01:24:17 spotipi java[6660]:         at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
Jan 01 01:24:17 spotipi java[6660]:         at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
Jan 01 01:24:17 spotipi java[6660]:         at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
Jan 01 01:24:17 spotipi java[6660]:         at java.util.ArrayList.get(ArrayList.java:459) ~[?:?]
Jan 01 01:24:17 spotipi java[6660]:         at xyz.gianlu.librespot.player.StateWrapper$TracksKeeper.updatePrevNextTracks(StateWrapper.java:933) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:17 spotipi java[6660]:         at xyz.gianlu.librespot.player.StateWrapper$TracksKeeper.setQueue(StateWrapper.java:1027) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:17 spotipi java[6660]:         at xyz.gianlu.librespot.player.StateWrapper.setQueue(StateWrapper.java:604) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:17 spotipi java[6660]:         at xyz.gianlu.librespot.player.Player.handleSetQueue(Player.java:437) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:17 spotipi java[6660]:         at xyz.gianlu.librespot.player.Player.command(Player.java:333) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:17 spotipi java[6660]:         at xyz.gianlu.librespot.player.state.DeviceStateHandler.notifyCommand(DeviceStateHandler.java:110) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:17 spotipi java[6660]:         at xyz.gianlu.librespot.player.state.DeviceStateHandler.onRequest(DeviceStateHandler.java:176) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:17 spotipi java[6660]:         at xyz.gianlu.librespot.dealer.DealerClient.lambda$handleRequest$1(DealerClient.java:107) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:17 spotipi java[6660]:         at xyz.gianlu.librespot.common.AsyncWorker.lambda$new$0(AsyncWorker.java:20) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:17 spotipi java[6660]:         at xyz.gianlu.librespot.common.AsyncProcessor.lambda$submit$1(AsyncProcessor.java:40) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:17 spotipi java[6660]:         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
Jan 01 01:24:17 spotipi java[6660]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Jan 01 01:24:17 spotipi java[6660]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Jan 01 01:24:17 spotipi java[6660]:         at java.lang.Thread.run(Thread.java:834) [?:?]
Jan 01 01:24:18 spotipi java[6660]: 2021-01-01 01:24:18,721 TRACE CdnManager:261 - Chunk 17/60 completed, cached: false, stream: {fileId: F100BFF16C65790CC7CE75E3815F09074D196C72}
Jan 01 01:24:22 spotipi java[6660]: 2021-01-01 01:24:22,853 TRACE CdnManager:261 - Chunk 18/60 completed, cached: false, stream: {fileId: F100BFF16C65790CC7CE75E3815F09074D196C72}
Jan 01 01:24:27 spotipi java[6660]: 2021-01-01 01:24:27,022 TRACE CdnManager:261 - Chunk 19/60 completed, cached: false, stream: {fileId: F100BFF16C65790CC7CE75E3815F09074D196C72}
Jan 01 01:24:31 spotipi java[6660]: 2021-01-01 01:24:31,054 TRACE CdnManager:261 - Chunk 20/60 completed, cached: false, stream: {fileId: F100BFF16C65790CC7CE75E3815F09074D196C72}
Jan 01 01:24:34 spotipi java[6660]: 2021-01-01 01:24:34,894 TRACE CdnManager:261 - Chunk 21/60 completed, cached: false, stream: {fileId: F100BFF16C65790CC7CE75E3815F09074D196C72}
Jan 01 01:24:35 spotipi java[6660]: 2021-01-01 01:24:35,696 TRACE DealerClient:97 - Received request. {mid: hm://connect-state/v1/player/command, key: dee4b941-2fa6-45ce-8528-eee6af23d5ec, pid: 999023945, sender: daabfe9546970a2fb6a60fd412e854af9caf1653, command: {"endpoint":"add_to_queue","track":{"uri":"spotify:episode:2ZblYJMnX8lhLGPFZrGega","metadata":{"is_queued":"true","media.manifest_id":"","podcast.title":"The Leviathan Chronicles","podcast.uri":"spotify:show:9a4cca544cc44a8f95340d69464fe46e"}},"options":{"override_restrictions":false,"only_for_local_device":false,"system_initiated":false},"logging_params":{"command_initiated_time":1609464274084}}}
```

**Version/Commit**
Release 1.5.3

**Comment by Zageron** [comment]
Likewise:

```zsh
Jan 01 01:24:35 spotipi java[6660]: 2021-01-01 01:24:35,697 DEBUG Player:293 - Received command: AddToQueue
Jan 01 01:24:35 spotipi java[6660]: 2021-01-01 01:24:35,703 ERROR DealerClient:112 - Failed handling request. {key: dee4b941-2fa6-45ce-8528-eee6af23d5ec}
Jan 01 01:24:35 spotipi java[6660]: java.lang.IndexOutOfBoundsException: Index 521 out of bounds for length 26
Jan 01 01:24:35 spotipi java[6660]:         at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
Jan 01 01:24:35 spotipi java[6660]:         at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
Jan 01 01:24:35 spotipi java[6660]:         at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
Jan 01 01:24:35 spotipi java[6660]:         at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
Jan 01 01:24:35 spotipi java[6660]:         at java.util.ArrayList.get(ArrayList.java:459) ~[?:?]
Jan 01 01:24:35 spotipi java[6660]:         at xyz.gianlu.librespot.player.StateWrapper$TracksKeeper.updatePrevNextTracks(StateWrapper.java:933) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:35 spotipi java[6660]:         at xyz.gianlu.librespot.player.StateWrapper$TracksKeeper.addToQueue(StateWrapper.java:997) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:35 spotipi java[6660]:         at xyz.gianlu.librespot.player.StateWrapper.addToQueue(StateWrapper.java:596) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:35 spotipi java[6660]:         at xyz.gianlu.librespot.player.Player.handleAddToQueue(Player.java:445) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:35 spotipi java[6660]:         at xyz.gianlu.librespot.player.Player.command(Player.java:330) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:35 spotipi java[6660]:         at xyz.gianlu.librespot.player.state.DeviceStateHandler.notifyCommand(DeviceStateHandler.java:110) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:35 spotipi java[6660]:         at xyz.gianlu.librespot.player.state.DeviceStateHandler.onRequest(DeviceStateHandler.java:176) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:35 spotipi java[6660]:         at xyz.gianlu.librespot.dealer.DealerClient.lambda$handleRequest$1(DealerClient.java:107) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:35 spotipi java[6660]:         at xyz.gianlu.librespot.common.AsyncWorker.lambda$new$0(AsyncWorker.java:20) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:35 spotipi java[6660]:         at xyz.gianlu.librespot.common.AsyncProcessor.lambda$submit$1(AsyncProcessor.java:40) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 01:24:35 spotipi java[6660]:         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
Jan 01 01:24:35 spotipi java[6660]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Jan 01 01:24:35 spotipi java[6660]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Jan 01 01:24:35 spotipi java[6660]:         at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by devgianlu** [comment]
@Zageron Can you send the part where you connect for the first time? A full log.

**Comment by devgianlu** [comment]
@Zageron

**Comment by devgianlu** [comment]
Closing for inactivity.
