### ISSUE TITLE
Transfer Failure

### ISSUE THREAD

**Issue by Zageron** [librespot-org/librespot-java#286]
**Describe the bug**
Attempted to connect to librespot-java, after a fresh reboot, from an active/paused session on my PC.
Note that from this state simply double clicking another song, or even the same song, and then attempting to connect functions!

**To Reproduce**
- Start Spotify on PC.
- Reboot raspberry. (Wait for startup)
- Try to select 'SpotiPi' in desktop spotify.
- Observe crash.

**Expected behavior**
- Should transfer active session appropriately.

**Screenshots/Stracktraces/Logs**
```zsh
Jan 01 02:03:19 spotipi java[597]: 2021-01-01 02:03:19,476 DEBUG Player:293 - Received command: Transfer
Jan 01 02:03:19 spotipi java[597]: 2021-01-01 02:03:19,507 DEBUG Player:365 - Loading context (transfer), uri: spotify:station:album:0jMdvHngDq93H361gAh9aS
Jan 01 02:03:19 spotipi java[597]: 2021-01-01 02:03:19,537 TRACE StateWrapper:1084 - Initialized current track index to 3.
Jan 01 02:03:19 spotipi java[597]: 2021-01-01 02:03:19,551 DEBUG Player:225 - Loading session, id: hCFjLxpnpos9O+1eIIHhQQ, play: false
Jan 01 02:03:19 spotipi java[597]: 2021-01-01 02:03:19,552 TRACE PlayerQueue:141 - Queue has been cleared.
Jan 01 02:03:19 spotipi java[597]: 2021-01-01 02:03:19,554 INFO  PlayerSession:53 - Created new session. {id: hCFjLxpnpos9O+1eIIHhQQ}
Jan 01 02:03:19 spotipi java[597]: 2021-01-01 02:03:19,556 TRACE MercuryClient:140 - Send Mercury request, seq: 5, uri: hm://event-service/v1/events, method: POST
Jan 01 02:03:19 spotipi java[597]: 2021-01-01 02:03:19,558 DEBUG Player:253 - Loading track, id: null, session: hCFjLxpnpos9O+1eIIHhQQ, playback: null, play: false
Jan 01 02:03:19 spotipi java[597]: 2021-01-01 02:03:19,561 ERROR DealerClient:112 - Failed handling request. {key: 4712e02a-ee8f-454e-8d91-aa37c77921c5}
Jan 01 02:03:19 spotipi java[597]: java.lang.IllegalStateException: null
Jan 01 02:03:19 spotipi java[597]:         at xyz.gianlu.librespot.player.StateWrapper.getCurrentPlayableOrThrow(StateWrapper.java:558) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 02:03:19 spotipi java[597]:         at xyz.gianlu.librespot.player.Player.loadTrack(Player.java:254) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 02:03:19 spotipi java[597]:         at xyz.gianlu.librespot.player.Player.loadSession(Player.java:239) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 02:03:19 spotipi java[597]:         at xyz.gianlu.librespot.player.Player.handleTransferState(Player.java:370) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 02:03:19 spotipi java[597]:         at xyz.gianlu.librespot.player.Player.command(Player.java:300) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 02:03:19 spotipi java[597]:         at xyz.gianlu.librespot.player.state.DeviceStateHandler.notifyCommand(DeviceStateHandler.java:110) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 02:03:19 spotipi java[597]:         at xyz.gianlu.librespot.player.state.DeviceStateHandler.onRequest(DeviceStateHandler.java:176) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 02:03:19 spotipi java[597]:         at xyz.gianlu.librespot.dealer.DealerClient.lambda$handleRequest$1(DealerClient.java:107) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 02:03:19 spotipi java[597]:         at xyz.gianlu.librespot.common.AsyncWorker.lambda$new$0(AsyncWorker.java:20) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 02:03:19 spotipi java[597]:         at xyz.gianlu.librespot.common.AsyncProcessor.lambda$submit$1(AsyncProcessor.java:40) ~[librespot-java-api-v1.5.3.jar:1.5.3]
Jan 01 02:03:19 spotipi java[597]:         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
Jan 01 02:03:19 spotipi java[597]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Jan 01 02:03:19 spotipi java[597]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Jan 01 02:03:19 spotipi java[597]:         at java.lang.Thread.run(Thread.java:834) [?:?]
Jan 01 02:03:19 spotipi java[597]: 2021-01-01 02:03:19,891 TRACE MercuryClient:183 - Handling packet, cmd: MercuryReq, seq: 5, flags: 1, parts: 1
Jan 01 02:03:19 spotipi java[597]: 2021-01-01 02:03:19,894 DEBUG EventService:35 - Event sent. {body: 557|3|hCFjLxpnpos9O+1eIIHhQQ|spotify:station:album:0jMdvHngDq93H361gAh9aS|spotify:station:album:0jMdvHngDq93H361gAh9aS|1609466600483||40|, result: 200}
```

**Version/Commit**
Release 1.5.3

**Comment by devgianlu** [comment]
This issue should be as of #281.
