### ISSUE TITLE
could not connect

### ISSUE THREAD

**Issue by wdehoog** [librespot-org/librespot-java#294]
**Describe the bug**
Connecting to the player from an android phone fails.

**To Reproduce**
Connect

**Expected behavior**
Be connected

**Screenshots/Stracktraces/Logs**
2021-01-10 21:21:12,209 DEBUG Player:293 - Received command: Transfer
2021-01-10 21:21:12,227 DEBUG Player:365 - Loading context (transfer), uri: spotify:playlist:4gCjobA8WglT94shpVlWJZ
2021-01-10 21:21:12,247 TRACE StateWrapper:1084 - Initialized current track index to 12.
2021-01-10 21:21:12,259 DEBUG Player:225 - Loading session, id: xxxxxxxxxxxxxxxxxxxxx, play: false
2021-01-10 21:21:12,261 TRACE PlayerQueue:141 - Queue has been cleared.
2021-01-10 21:21:12,264 INFO  PlayerSession:53 - Created new session. {id: xxxxxxxxxxxxxxxxxxxxx}
2021-01-10 21:21:12,268 DEBUG Player:253 - Loading track, id: null, session: xxxxxxxxxxxxxxxxxxxxx, playback: null, play: false
2021-01-10 21:21:12,268 TRACE MercuryClient:140 - Send Mercury request, seq: 5, uri: hm://event-service/v1/events, method: POST
2021-01-10 21:21:12,271 ERROR DealerClient:112 - Failed handling request. {key: 574bca03-98cf-4827-928d-c106e3c46f86}
java.lang.IllegalStateException: null
        at xyz.gianlu.librespot.player.StateWrapper.getCurrentPlayableOrThrow(StateWrapper.java:558) ~[librespot-api-jar-with-dependencies.jar:1.5.3]
        at xyz.gianlu.librespot.player.Player.loadTrack(Player.java:254) ~[librespot-api-jar-with-dependencies.jar:1.5.3]
        at xyz.gianlu.librespot.player.Player.loadSession(Player.java:239) ~[librespot-api-jar-with-dependencies.jar:1.5.3]
        at xyz.gianlu.librespot.player.Player.handleTransferState(Player.java:370) ~[librespot-api-jar-with-dependencies.jar:1.5.3]
        at xyz.gianlu.librespot.player.Player.command(Player.java:300) ~[librespot-api-jar-with-dependencies.jar:1.5.3]
        at xyz.gianlu.librespot.player.state.DeviceStateHandler.notifyCommand(DeviceStateHandler.java:110) ~[librespot-api-jar-with-dependencies.jar:1.5.3]
        at xyz.gianlu.librespot.player.state.DeviceStateHandler.onRequest(DeviceStateHandler.java:176) ~[librespot-api-jar-with-dependencies.jar:1.5.3]
        at xyz.gianlu.librespot.dealer.DealerClient.lambda$handleRequest$1(DealerClient.java:107) ~[librespot-api-jar-with-dependencies.jar:1.5.3]
        at xyz.gianlu.librespot.common.AsyncWorker.lambda$new$0(AsyncWorker.java:20) ~[librespot-api-jar-with-dependencies.jar:1.5.3]
        at xyz.gianlu.librespot.common.AsyncProcessor.lambda$submit$1(AsyncProcessor.java:40) ~[librespot-api-jar-with-dependencies.jar:1.5.3]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
2021-01-10 21:21:12,556 TRACE MercuryClient:183 - Handling packet, cmd: MercuryReq, seq: 5, flags: 1, parts: 1

**Version/Commit**
jar from 1.5.3 (renamed). running on raspberry pi

**Comment by devgianlu** [comment]
Should be fixed if you compile the latest commit or get a snapshot build.

**Comment by wdehoog** [comment]
And where can I find a snapshot build?

**Comment by devgianlu** [comment]
> And where can I find a snapshot build?

https://oss.sonatype.org/content/repositories/snapshots/xyz/gianlu/librespot/

**Comment by wdehoog** [comment]
I tried librespot-player-1.5.4-20210101.142551-1.jar and indeed connecting now works. Thanks a lot.
