### ISSUE TITLE
java.lang.IllegalStateException: Cannot set output for PlayerQueueEntry

### ISSUE THREAD

**Issue by kokarare1212** [librespot-org/librespot-java#295]
**Describe the bug**
This error occurs when setOutput is specified as `AudioOutput.STDOUT` and `AudioOutput.PIPE` in the Builder of PlayerConfiguration.

**To Reproduce**
```java
public class Main(){
    public static void main(String[] args) {
        Session session = new Session.Builder()
                            .userPass("UserName", "Password")
                            .create();
        PlayerConfiguration playerConfiguration = new PlayerConfiguration.Builder()
//                  .setOutput(AudioOutput.STDOUT) 
// or
//                  .setOutput(AudioOutput.PIPE) 
                    .build();
        Player player = new Player(playerConfiguration, session);
        player.load("spotify:track:xxxxxxxxxxxxxxxxxxxxxx", true);
        // java.lang.IllegalStateException
    }
}
```

**Screenshots/Stracktraces/Logs**
```
Exception in thread "player-queue-61137731" java.lang.IllegalStateException: Cannot set output for PlayerQueueEntry{0172821d2a02ea8dbd2cbf7b10687dcb}
        at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.setOutput(PlayerQueueEntry.java:189)
        at xyz.gianlu.librespot.player.playback.PlayerSession.playInternal(PlayerSession.java:266)
        at xyz.gianlu.librespot.player.playback.PlayerSession.advance(PlayerSession.java:115)
        at xyz.gianlu.librespot.player.playback.PlayerSession.playbackEnded(PlayerSession.java:141)
        at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.run(PlayerQueueEntry.java:324)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Version/Commit**
`v1.5.3`

**Comment by devgianlu** [comment]
Before calling `load` you should call `waitReady`.

**Comment by kokarare1212** [comment]
I tried adding `player.waitReady`, but it didn't work.
I get an error like the one above.
```
Exception in thread "player-queue-975001918" java.lang.IllegalStateException: Cannot set output for PlayerQueueEntry{01cb900f70ac865cacc2f346bc52af14}
        at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.setOutput(PlayerQueueEntry.java:189)
        at xyz.gianlu.librespot.player.playback.PlayerSession.playInternal(PlayerSession.java:266)
        at xyz.gianlu.librespot.player.playback.PlayerSession.advance(PlayerSession.java:115)
        at xyz.gianlu.librespot.player.playback.PlayerSession.playbackEnded(PlayerSession.java:141)
        at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.run(PlayerQueueEntry.java:324)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```
Also, in rare cases, I get the following error
```
Exception in thread "main" Exception in thread "player-queue-88301993" java.lang.IllegalStateException
        at xyz.gianlu.librespot.player.state.DeviceStateHandler.updateState(DeviceStateHandler.java:206)
        at xyz.gianlu.librespot.player.StateWrapper.updated(StateWrapper.java:290)
        at xyz.gianlu.librespot.player.Player.startedLoading(Player.java:584)
        at xyz.gianlu.librespot.player.playback.PlayerSession.startedLoading(PlayerSession.java:147)
        at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.run(PlayerQueueEntry.java:248)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
java.lang.IllegalStateException
        at xyz.gianlu.librespot.player.state.DeviceStateHandler.updateState(DeviceStateHandler.java:206)
        at xyz.gianlu.librespot.player.StateWrapper.updated(StateWrapper.java:290)
        at xyz.gianlu.librespot.player.Player.loadTrack(Player.java:262)
        at xyz.gianlu.librespot.player.Player.loadSession(Player.java:239)
        at xyz.gianlu.librespot.player.Player.load(Player.java:150)
        at xyz.gianlu.librespot.client.Main.main(Main.java:136)
```

**Comment by devgianlu** [comment]
I forgot that `Player#waitReady()` returns a `Future`, so you have to use `player.waitReady().get();`.

**Comment by kokarare1212** [comment]
It worked beautifully!
Thank you so much.
