### ISSUE TITLE
Problem when running on Raspberry Pi Zero W

### ISSUE THREAD

**Issue by TooDizzy** [librespot-org/librespot-java#302]
**Describe the bug**
When running the `player` on the RPI Zero W I am unable to get it to play any songs. The below error happens.

This is when using PulseAudio and using `ZERO_CONF`.

When testing through `mplayer` there's sound output.

Tested the same jar on a macOS 10.14.6 with similar config (no pulseaudio) and without problems.

**To Reproduce**
* Start the `player`
* Connect to it using the official Desktop Spotify App
* Play a song

**Expected behavior**
Song plays and audio are passed through PulseAudio.

**Screenshots/Stracktraces/Logs**
```
2021-01-30 12:00:27,728 FATAL Log4JUncaughtExceptionHandler:15 - [player-audio-sink]
java.lang.IllegalArgumentException: Master Gain not supported
	at org.classpath.icedtea.pulseaudio.PulseAudioLine.getControl(PulseAudioLine.java:89) ~[icedtea-sound.jar:?]
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.getControl(PulseAudioSourceDataLine.java:51) ~[icedtea-sound.jar:?]
	at xyz.gianlu.librespot.player.mixing.AudioSink$Output.setVolume(AudioSink.java:281) ~[librespot-player-1.5.4.jar:1.5.4]
	at xyz.gianlu.librespot.player.mixing.AudioSink$Output.acquireLine(AudioSink.java:209) ~[librespot-player-1.5.4.jar:1.5.4]
	at xyz.gianlu.librespot.player.mixing.AudioSink$Output.start(AudioSink.java:222) ~[librespot-player-1.5.4.jar:1.5.4]
	at xyz.gianlu.librespot.player.mixing.AudioSink.run(AudioSink.java:139) ~[librespot-player-1.5.4.jar:1.5.4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Version/Commit**
Using latest available version: 1.5.4.

**Comment by TooDizzy** [comment]
also tried to uninstall PulseAudio and select the desired hardware, and then it seems to work just fine. So I guess it is likely something with the PulseAudio config....?

**Comment by devgianlu** [comment]
I believe I've had a few issues with the icedtea version of pulse audio too. @spocon Might know something more on this topic.

You may want to have a look at this thread: https://github.com/librespot-org/librespot-java/issues/198

**Comment by TooDizzy** [comment]
> I believe I've had a few issues with the icedtea version of pulse audio too. @spocon Might know something more on this topic.
> 
> You may want to have a look at this thread: #198

Thanks. Will take a look.

**Comment by TooDizzy** [comment]
Tried to uncomment icedtea classes as suggested here: https://nealvs.wordpress.com/2017/08/11/java-sound-on-a-raspberry-pi-with-openjdk/. Sadly with no changes. It fails with the same stacktrace. So there must be a different flag somewere.

Now trying to follow this guide here on how to build the java pulseaudio lib; which seems to be missing: https://www.raspberrypi.org/forums/viewtopic.php?t=24210

**Comment by TooDizzy** [comment]
Just for kicks I ran the app as root (using sudo). This resulted in a different error.
How do I change the settings to match what ever is the system is using?

```
2021-01-30 20:01:13,011 INFO  LineHelper:62 - Available mixers: 'PulseAudio Mixer'
2021-01-30 20:01:13,152 INFO  DeviceStateHandler:252 - Put state. {ts: 1612036871629, connId: YzcxY...yRDQ0, reason: PLAYER_STATE_CHANGED}
2021-01-30 20:01:13,566 WARN  AudioSink:203 - Failed opening like for custom format 'PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian'. Opening default.
2021-01-30 20:01:14,029 INFO  LineHelper:62 - Available mixers: 'PulseAudio Mixer'
2021-01-30 20:01:14,063 FATAL Player:600 - An error with the mixer occurred. This is likely a configuration issue, please consult the project repository.
javax.sound.sampled.LineUnavailableException: null
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openImpl(PulseAudioMixer.java:714) ~[icedtea-sound.jar:?]
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:588) ~[icedtea-sound.jar:?]
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:584) ~[icedtea-sound.jar:?]
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.open(PulseAudioMixer.java:579) ~[icedtea-sound.jar:?]
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:94) ~[icedtea-sound.jar:?]
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:75) ~[icedtea-sound.jar:?]
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:90) ~[icedtea-sound.jar:?]
	at xyz.gianlu.librespot.player.mixing.AudioSink$Output.acquireLine(AudioSink.java:205) ~[librespot-player-1.5.4.jar:1.5.4]
	at xyz.gianlu.librespot.player.mixing.AudioSink$Output.start(AudioSink.java:222) ~[librespot-player-1.5.4.jar:1.5.4]
	at xyz.gianlu.librespot.player.mixing.AudioSink.run(AudioSink.java:139) [librespot-player-1.5.4.jar:1.5.4]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

Then maybe I can get rid of this warning:
`2021-01-30 20:01:13,566 WARN  AudioSink:203 - Failed opening like for custom format 'PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian'. Opening default. `

**Comment by devgianlu** [comment]
The error looks better, but there's still an issue with the pulse audio configuration.

The warning is because librespot-java fried to open a to pipì the track format directly so that it doesn't need to convert it.

The error message refers to the audio configuration in the player README, but since you have only one device this shouldn't be the issue.

**Comment by TooDizzy** [comment]
I am giving up on this for now. Wanted to use `pulseaudio-crossover-rack` with `pulseaudio` to correct the output a little bit, before hitting the speakers.
Will look at running this directly through ALSA instead for now. The same `LADSPA` seems to also function directly through ALSA, but then there's no GUI...

**Comment by b-hahn** [comment]
> also tried to uninstall PulseAudio and select the desired hardware, and then it seems to work just fine. So I guess it is likely something with the PulseAudio config....?

I'm having the same issue on an UDOO board, sounds works fine using VLC but I hear nothing when trying to use librespot-java. What do you mean by selecting the desired hardware and it then working fine? How would I do that?

Thanks!

**Comment by TooDizzy** [comment]
> > also tried to uninstall PulseAudio and select the desired hardware, and then it seems to work just fine. So I guess it is likely something with the PulseAudio config....?
> 
> I'm having the same issue on an UDOO board, sounds works fine using VLC but I hear nothing when trying to use librespot-java. What do you mean by selecting the desired hardware and it then working fine? How would I do that?
> 
> Thanks!

I basically just selected the audio hardware directly, instead of trying to go through PulseAudio.

I got it working using ALSA and some LADSPA plugins. Need more work, but seems to be working great.

**Comment by b-hahn** [comment]
Thanks for the quick reply! How did you select the hardware directly, though? With pulseaudio installed I only get the Pulseaudio-Mixer as an available mixer, with it deinstalled I get this error:

`2021-03-08 07:55:55,736 FATAL Player:614 - An error with the mixer occurred. This is likely a configuration issue, please consult the project repository.
xyz.gianlu.librespot.player.mixing.LineHelper$MixerException: Couldn't find a suitable mixer, openLine: 'interface SourceDataLine supporting format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian', available: [Port imxvt1613audio [hw:0], version 4.1.15-g5ece5b16798c, Port imxhdmisoc [hw:1], version 4.1.15-g5ece5b16798c, imxvt1613audio [plughw:0,0], version 4.1.15-g5ece5b16798c, imxhdmisoc [plughw:1,0], version 4.1.15-g5ece5b16798c]
	at xyz.gianlu.librespot.player.mixing.LineHelper.findSupportingMixersFor(LineHelper.java:34) ~[librespot-java-api-v1.5.5.jar:1.5.5]
	at xyz.gianlu.librespot.player.mixing.LineHelper.getLineFor(LineHelper.java:61) ~[librespot-java-api-v1.5.5.jar:1.5.5]
	at xyz.gianlu.librespot.player.mixing.AudioSink$Output.acquireLine(AudioSink.java:204) ~[librespot-java-api-v1.5.5.jar:1.5.5]
	at xyz.gianlu.librespot.player.mixing.AudioSink$Output.start(AudioSink.java:222) ~[librespot-java-api-v1.5.5.jar:1.5.5]
	at xyz.gianlu.librespot.player.mixing.AudioSink.run(AudioSink.java:139) [librespot-java-api-v1.5.5.jar:1.5.5]
	at java.lang.Thread.run(Thread.java:834) [?:?]`

Does my imxvt1613audio somehow not support required features?

**Comment by devgianlu** [comment]
Try running with sudo or adding the user to the group for audio management.

**Comment by b-hahn** [comment]
Thanks! I am running things with sudo, and seem to be in the audio group:

`
ben@udoo:~$ fgrep -ie 'audio' /etc/group
audio: x:29:pulse,ben,spocon
`

Am Mo., 8. März 2021 um 08:10 Uhr schrieb devgianlu <
notifications@github.com>:
