### ISSUE TITLE
nil error when attempting to play a playlist that contains any number of offline files.

### ISSUE THREAD

**Issue by Zageron** [librespot-org/librespot-java#332]
**Describe the bug**
Cannot connect to device with spotify when listening to a playlist with any number of offline files.

**Version**
librespot-java-api-v1.5.5

**To Reproduce**
1. Restart machine
2. Play a custom playlist that contains Offline files, but play a Spotify track.
3. Try to attach to spocon.

**Expected behavior**
Spotify should attach and skip songs that spocon hasn't downloaded / doesn't have access to.

**Logs**
```
Apr 09 05:12:41 spotipi java[1135]: 2021-04-09 05:12:41,223 TRACE DealerClient:97 - Received request. {mid: hm://connect-state/v1/player/command, key: cbf79024-7486-47ec-9fb9-c6268e81005c, pid: 886375822, sender: 4caaba3413d4673d3929a47864cd72a79628748d, command: {"endpoint":"transfer","data":"CgYIARAAGAAS4QUI44XLposvEAAZAAAAAAAA8D8gACrKBQoAEhBkYjc4MDcxNzQxNTE3YjU1GhD1MhFpZ9dBg7T7CcOM4/BeIjEKCWFsYnVtX3VyaRIkc3BvdGlmeTphbGJ1bTo1T0FlQ3VkS2VOT2NQSHpHUlFWeGl0IiUKC2FsYnVtX3RpdGxlEhZZcyBWIE9yY2hlc3RyYSBWZXJzaW9uIkoKEGltYWdlX3hsYXJnZV91cmwSNnNwb3RpZnk6aW1hZ2U6YWI2NzYxNmQwMDAwYjI3MzNmNzEwZTUxODRiM2RmZDJmOTJhY2I3NiIqCiBhY3Rpb25zLnNraXBwaW5nX3ByZXZfcGFzdF90cmFjaxIGcmVzdW1lIkkKD2ltYWdlX3NtYWxsX3VybBI2c3BvdGlmeTppbWFnZTphYjY3NjE2ZDAwMDA0ODUxM2Y3MTBlNTE4NGIzZGZkMmY5MmFjYjc2IjUKCmVudGl0eV91cmkSJ3Nwb3RpZnk6cGxheWxpc3Q6NVJKVndsNmRKWGFSM0lVRDJtTFFIcCIqCiBhY3Rpb25zLnNraXBwaW5nX25leHRfcGFzdF90cmFjaxIGcmVzdW1lIjMKCmFydGlzdF91cmkSJXNwb3RpZnk6YXJ0aXN0OjVXRm9memdSeHBWTmtwd2c5WFJTZGciQwoJaW1hZ2VfdXJsEjZzcG90aWZ5OmltYWdlOmFiNjc2MTZkMDAwMDFlMDIzZjcxMGU1MTg0YjNkZmQyZjkyYWNiNzYiDgoJaXRlcmF0aW9uEgEwIhUKDHRyYWNrX3BsYXllchIFYXVkaW8iSQoPaW1hZ2VfbGFyZ2VfdXJsEjZzcG90aWZ5OmltYWdlOmFiNjc2MTZkMDAwMGIyNzMzZjcxMGU1MTg0YjNkZmQyZjkyYWNiNzYiNgoLY29udGV4dF91cmkSJ3Nwb3RpZnk6cGxheWxpc3Q6NVJKVndsNmRKWGFSM0lVRDJtTFFIcBqjAgomChBkZXNrdG9wLWNsaWVudC14EgoxLjEuNTYuNTk1GgAiACoAMgAS4AEKJ3Nwb3RpZnk6cGxheWxpc3Q6NVJKVndsNmRKWGFSM0lVRDJtTFFIcBIxY29udGV4dDovL3Nwb3RpZnk6cGxheWxpc3Q6NVJKVndsNmRKWGFSM0lVRDJtTFFIcBoYCg1jb250ZXh0X293bmVyEgd6YWdlcjBuGjUKCWltYWdlX3VybBIoYWI2NzcwNmMwMDAwZGE4NGFjY2VkZGQ1ZTUyYzNhNzViYjY4MTQ2YxotChNjb250ZXh0X2Rlc2NyaXB0aW9uEhZ6YWdlcm9uLCBpbiBhIG51dHNoZWxsIgAwARoQZGI3ODA3MTc0MTUxN2I1NSIAKgAyACICEAA=","options":{"restore_paused":"restore","restore_position":"extrapolate","restore_track":"only_current","license":"premium"},"from_device_identifier":"4caaba3413d4673d3929a47864cd72a79628748d"}}
Apr 09 05:12:41 spotipi java[1135]: 2021-04-09 05:12:41,227 DEBUG Player:89 - Received command: Transfer
Apr 09 05:12:41 spotipi java[1135]: 2021-04-09 05:12:41,254 DEBUG Player:379 - Loading context (transfer), uri: spotify:playlist:5RJVwl6dJXaR3IUD2mLQHp
Apr 09 05:12:41 spotipi java[1135]: 2021-04-09 05:12:41,260 TRACE MercuryClient:140 - Send Mercury request, seq: 5, uri: hm://context-resolve/v1/spotify:playlist:5RJVwl6dJXaR3IUD2mLQHp, method: GET
Apr 09 05:12:41 spotipi java[1135]: 2021-04-09 05:12:41,662 TRACE MercuryClient:183 - Handling packet, cmd: MercuryReq, seq: 5, flags: 0, parts: 1
Apr 09 05:12:41 spotipi java[1135]: 2021-04-09 05:12:41,769 TRACE MercuryClient:183 - Handling packet, cmd: MercuryReq, seq: 5, flags: 2, parts: 1
Apr 09 05:12:41 spotipi java[1135]: 2021-04-09 05:12:41,801 TRACE MercuryClient:183 - Handling packet, cmd: MercuryReq, seq: 5, flags: 2, parts: 1
Apr 09 05:12:41 spotipi java[1135]: 2021-04-09 05:12:41,841 TRACE MercuryClient:183 - Handling packet, cmd: MercuryReq, seq: 5, flags: 1, parts: 1
Apr 09 05:12:41 spotipi java[1135]: 2021-04-09 05:12:41,945 ERROR DealerClient:112 - Failed handling request. {key: cbf79024-7486-47ec-9fb9-c6268e81005c}
Apr 09 05:12:41 spotipi java[1135]: java.lang.UnsupportedOperationException: null
Apr 09 05:12:41 spotipi java[1135]:         at xyz.gianlu.librespot.metadata.UnsupportedId.getGid(UnsupportedId.java:17) ~[librespot-java-api-v1.5.5.jar:1.5.5]
Apr 09 05:12:41 spotipi java[1135]:         at xyz.gianlu.librespot.common.ProtoUtils.lambda$jsonToContextTrack$0(ProtoUtils.java:121) ~[librespot-java-api-v1.5.5.jar:1.5.5]
Apr 09 05:12:41 spotipi java[1135]:         at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
Apr 09 05:12:41 spotipi java[1135]:         at xyz.gianlu.librespot.common.ProtoUtils.jsonToContextTrack(ProtoUtils.java:119) ~[librespot-java-api-v1.5.5.jar:1.5.5]
Apr 09 05:12:41 spotipi java[1135]:         at xyz.gianlu.librespot.common.ProtoUtils.jsonToContextTracks(ProtoUtils.java:137) ~[librespot-java-api-v1.5.5.jar:1.5.5]
Apr 09 05:12:41 spotipi java[1135]:         at xyz.gianlu.librespot.common.ProtoUtils.jsonToContextPage(ProtoUtils.java:148) ~[librespot-java-api-v1.5.5.jar:1.5.5]
Apr 09 05:12:41 spotipi java[1135]:         at xyz.gianlu.librespot.common.ProtoUtils.jsonToContextPages(ProtoUtils.java:156) ~[librespot-java-api-v1.5.5.jar:1.5.5]
Apr 09 05:12:41 spotipi java[1135]:         at xyz.gianlu.librespot.mercury.MercuryRequests$ResolvedContextWrapper.pages(MercuryRequests.java:142) ~[librespot-java-api-v1.5.5.jar:1.5.5]
Apr 09 05:12:41 spotipi java[1135]:         at xyz.gianlu.librespot.player.PagesLoader.getPage(PagesLoader.java:95) ~[librespot-java-api-v1.5.5.jar:1.5.5]
Apr 09 05:12:41 spotipi java[1135]:         at xyz.gianlu.librespot.player.PagesLoader.nextPage(PagesLoader.java:129) ~[librespot-java-api-v1.5.5.jar:1.5.5]
Apr 09 05:12:41 spotipi java[1135]:         at xyz.gianlu.librespot.player.StateWrapper$TracksKeeper.initializeFrom(StateWrapper.java:1075) ~[librespot-java-api-v1.5.5.jar:1.5.5]
Apr 09 05:12:41 spotipi java[1135]:         at xyz.gianlu.librespot.player.StateWrapper.transfer(StateWrapper.java:480) ~[librespot-java-api-v1.5.5.jar:1.5.5]
Apr 09 05:12:41 spotipi java[1135]:         at xyz.gianlu.librespot.player.Player.handleTransferState(Player.java:382) ~[librespot-java-api-v1.5.5.jar:1.5.5]
Apr 09 05:12:41 spotipi java[1135]:         at xyz.gianlu.librespot.player.Player.access$300(Player.java:49) ~[librespot-java-api-v1.5.5.jar:1.5.5]
Apr 09 05:12:41 spotipi java[1135]:         at xyz.gianlu.librespot.player.Player$1.command(Player.java:96) ~[librespot-java-api-v1.5.5.jar:1.5.5]
Apr 09 05:12:41 spotipi java[1135]:         at xyz.gianlu.librespot.player.state.DeviceStateHandler.notifyCommand(DeviceStateHandler.java:110) ~[librespot-java-api-v1.5.5.jar:1.5.5]
Apr 09 05:12:41 spotipi java[1135]:         at xyz.gianlu.librespot.player.state.DeviceStateHandler.onRequest(DeviceStateHandler.java:176) ~[librespot-java-api-v1.5.5.jar:1.5.5]
Apr 09 05:12:41 spotipi java[1135]:         at xyz.gianlu.librespot.dealer.DealerClient.lambda$handleRequest$1(DealerClient.java:107) ~[librespot-java-api-v1.5.5.jar:1.5.5]
Apr 09 05:12:41 spotipi java[1135]:         at xyz.gianlu.librespot.common.AsyncWorker.lambda$new$0(AsyncWorker.java:20) ~[librespot-java-api-v1.5.5.jar:1.5.5]
Apr 09 05:12:41 spotipi java[1135]:         at xyz.gianlu.librespot.common.AsyncProcessor.lambda$submit$1(AsyncProcessor.java:40) ~[librespot-java-api-v1.5.5.jar:1.5.5]
Apr 09 05:12:41 spotipi java[1135]:         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
Apr 09 05:12:41 spotipi java[1135]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Apr 09 05:12:41 spotipi java[1135]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Apr 09 05:12:41 spotipi java[1135]:         at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by devgianlu** [comment]
Should be good now.

**Comment by Zageron** [comment]
> Should be good now.

Awesome, thanks!

**Comment by Zageron** [comment]
@devgianlu  Extension of this bug now that I can try the artifact!

Double clicking on a known offline file results in "frozen playback" until "next" is hit, or a different song is selected.
Non-manual playback is not affected, as it just skips invalid songs
```
Apr 09 17:00:10 spotipi java[10019]: 2021-04-09 17:00:10,616 TRACE PlayerQueueEntry:76 - Created new PlayerQueueEntry{01fe16c216bf3c57a10358eae3452671}.
Apr 09 17:00:10 spotipi java[10019]: 2021-04-09 17:00:10,617 TRACE PlayerQueue:66 - PlayerQueueEntry{01fe16c216bf3c57a10358eae3452671} added to queue.
Apr 09 17:00:10 spotipi java[10019]: 2021-04-09 17:00:10,618 DEBUG PlayerSession:267 - PlayerQueueEntry{01fe16c216bf3c57a10358eae3452671} has been added to the output. {sessionId: Iv0IzmPNvZlyq/Z5Ej6mnA, pos: 14, reason: CLICK_ROW}
Apr 09 17:00:10 spotipi java[10019]: 2021-04-09 17:00:10,619 TRACE PlayerSession:146 - PlayerQueueEntry{01fe16c216bf3c57a10358eae3452671} started loading.
Apr 09 17:00:10 spotipi java[10019]: 2021-04-09 17:00:10,621 DEBUG DealerClient:109 - Handled request. {key: 7142d111-79bd-4b66-a3a2-8bc20987acdf, result: SUCCESS}
Apr 09 17:00:10 spotipi java[10019]: 2021-04-09 17:00:10,624 FATAL Log4JUncaughtExceptionHandler:15 - [player-queue-4965132]
Apr 09 17:00:10 spotipi java[10019]: java.lang.IllegalArgumentException: Unknown content: UnsupportedId{spotify:local:%E8%8F%85%E9%87%8E%E3%82%88%E3%81%86%E5%AD%90:Ragnarok+Online+II:Swamper:267}
Apr 09 17:00:10 spotipi java[10019]:         at xyz.gianlu.librespot.audio.PlayableContentFeeder.load(PlayableContentFeeder.java:65) ~[librespot-api-1.5.6-20210409.154523-16.jar:1.5.6-SNAPSHOT]
Apr 09 17:00:10 spotipi java[10019]:         at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.load(PlayerQueueEntry.java:94) ~[librespot-api-1.5.6-20210409.154523-16.jar:1.5.6-SNAPSHOT]
Apr 09 17:00:10 spotipi java[10019]:         at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.run(PlayerQueueEntry.java:251) ~[librespot-api-1.5.6-20210409.154523-16.jar:1.5.6-SNAPSHOT]
Apr 09 17:00:10 spotipi java[10019]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
Apr 09 17:00:10 spotipi java[10019]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
Apr 09 17:00:10 spotipi java[10019]:         at java.lang.Thread.run(Thread.java:834) [?:?]
Apr 09 17:00:10 spotipi java[10019]: 2021-04-09 17:00:10,702 TRACE MercuryClient:183 - Handling packet, cmd: MercuryReq, seq: 15, flags: 1, parts: 1
Apr 09 17:00:10 spotipi java[10019]: 2021-04-09 17:00:10,702 DEBUG EventService:35 - Event sent. {body: 12|38|3|efe0783dd240b86a23e7bd837b85ca9831bdee8f|01d3642efa1f441169ea697c887a6260|00000000000000000000000000000000|desktop-client-x|fwdbtn|desktop-client-x|endplay|1572864|6539932|1|1|158666|8|0|0|0|1|13|0|-1|context|137|0|0|0|0|0|1|1|0|176400|spotify:playlist:5RJVwl6dJXaR3IUD2mLQHp|vorbis|701a0966717f43cfa07182dbd7e5dfe5||0|1617983985531|0|context||1.1.56.595|com.spotify|crossfade|none|daabfe9546970a2fb6a60fd412e854af9caf1653|na|none, result: 200}
Apr 09 17:00:10 spotipi java[10019]: 2021-04-09 17:00:10,703 TRACE MercuryClient:140 - Send Mercury request, seq: 16, uri: hm://event-service/v1/events, method: POST
Apr 09 17:00:10 spotipi java[10019]: 2021-04-09 17:00:10,797 TRACE MercuryClient:183 - Handling packet, cmd: MercuryReq, seq: 16, flags: 1, parts: 1
Apr 09 17:00:10 spotipi java[10019]: 2021-04-09 17:00:10,797 DEBUG EventService:35 - Event sent. {body: 557|3|Iv0IzmPNvZlyq/Z5Ej6mnA|spotify:playlist:5RJVwl6dJXaR3IUD2mLQHp|spotify:playlist:5RJVwl6dJXaR3IUD2mLQHp|1617984010667||286|context://spotify:playlist:5RJVwl6dJXaR3IUD2mLQHp, result: 200}
Apr 09 17:00:10 spotipi java[10019]: 2021-04-09 17:00:10,798 TRACE MercuryClient:140 - Send Mercury request, seq: 17, uri: hm://event-service/v1/events, method: POST
Apr 09 17:00:10 spotipi java[10019]: 2021-04-09 17:00:10,943 TRACE MercuryClient:183 - Handling packet, cmd: MercuryReq, seq: 17, flags: 1, parts: 1
```

**Comment by Zageron** [comment]
Thanks so much for these crazy rapid fixes :)

**Comment by Zageron** [comment]
Also there is no link that I can find that goes straight to the appropriate artifact folder (I had to skim the upload messages in the action to find it.). May be a good idea to add a link somewhere, or make it more obvious if there is one already.

**Comment by devgianlu** [comment]
That should be fixed too.

I've also added the snapshots link to the README.

**Comment by Zageron** [comment]
Works beautifully, even if connecting while listening to an invalid song.

**Comment by devgianlu** [comment]
Shall I close this?
