### ISSUE TITLE
Adding to queue causes IndexOutOfBounds

### ISSUE THREAD

**Issue by prototypicalpro** [librespot-org/librespot-java#377]
Hello! I'm using the latest version of [spocon](https://github.com/spocon/spocon) on an Ubuntu 20.04 box as a spotify connect device (default config except for audio quality). So far it's working well except for one issue that occurs when I attempt to add an item to the play queue:
```
Jul 04 17:27:42 spotify-box java[17637]: java.lang.IndexOutOfBoundsException: Index 17 out of bounds for length 17
Jul 04 17:27:42 spotify-box java[17637]:         at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
Jul 04 17:27:42 spotify-box java[17637]:         at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
Jul 04 17:27:42 spotify-box java[17637]:         at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
Jul 04 17:27:42 spotify-box java[17637]:         at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
Jul 04 17:27:42 spotify-box java[17637]:         at java.util.ArrayList.get(ArrayList.java:459) ~[?:?]
Jul 04 17:27:42 spotify-box java[17637]:         at xyz.gianlu.librespot.player.StateWrapper$TracksKeeper.updatePrevNextTracks(StateWrapper.java:972) ~[librespot-java-api-v1.6.0.jar:1.6.0]
Jul 04 17:27:42 spotify-box java[17637]:         at xyz.gianlu.librespot.player.StateWrapper$TracksKeeper.setQueue(StateWrapper.java:1069) ~[librespot-java-api-v1.6.0.jar:1.6.0]
Jul 04 17:27:42 spotify-box java[17637]:         at xyz.gianlu.librespot.player.StateWrapper.setQueue(StateWrapper.java:643) ~[librespot-java-api-v1.6.0.jar:1.6.0]
Jul 04 17:27:42 spotify-box java[17637]:         at xyz.gianlu.librespot.player.Player.handleSetQueue(Player.java:602) ~[librespot-java-api-v1.6.0.jar:1.6.0]
Jul 04 17:27:42 spotify-box java[17637]:         at xyz.gianlu.librespot.player.Player.access$1200(Player.java:62) ~[librespot-java-api-v1.6.0.jar:1.6.0]
Jul 04 17:27:42 spotify-box java[17637]:         at xyz.gianlu.librespot.player.Player$1.command(Player.java:146) ~[librespot-java-api-v1.6.0.jar:1.6.0]
Jul 04 17:27:42 spotify-box java[17637]:         at xyz.gianlu.librespot.player.state.DeviceStateHandler.notifyCommand(DeviceStateHandler.java:129) ~[librespot-java-api-v1.6.0.jar:1.6.0]
Jul 04 17:27:42 spotify-box java[17637]:         at xyz.gianlu.librespot.player.state.DeviceStateHandler.onRequest(DeviceStateHandler.java:194) ~[librespot-java-api-v1.6.0.jar:1.6.0]
Jul 04 17:27:42 spotify-box java[17637]:         at xyz.gianlu.librespot.dealer.DealerClient.lambda$handleRequest$1(DealerClient.java:124) ~[librespot-java-api-v1.6.0.jar:1.6.0]
Jul 04 17:27:42 spotify-box java[17637]:         at xyz.gianlu.librespot.common.AsyncWorker.lambda$new$0(AsyncWorker.java:36) ~[librespot-java-api-v1.6.0.jar:1.6.0]
Jul 04 17:27:42 spotify-box java[17637]:         at xyz.gianlu.librespot.common.AsyncProcessor.lambda$submit$1(AsyncProcessor.java:56) ~[librespot-java-api-v1.6.0.jar:1.6.0]
Jul 04 17:27:42 spotify-box java[17637]:         at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
Jul 04 17:27:42 spotify-box java[17637]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
Jul 04 17:27:42 spotify-box java[17637]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
Jul 04 17:27:42 spotify-box java[17637]:         at java.lang.Thread.run(Thread.java:829) [?:?]
```
More specifically, this seems to occur when I am listening to a playlist and attempt to add a song to the queue that is too many songs before the current song in the playlist. The index in the error changes based on which song I'm currently listening to.

Thanks, and let me know if you need more context/logs/etc.

**Comment by devgianlu** [comment]
I was not able to reproduce the issue with this information. Can you please add a full log? Possibly toggling the log level to DEBUG.

**Comment by devgianlu** [comment]
@prototypicalpro
