### ISSUE TITLE
LineUnavailableExeption and no playback

### ISSUE THREAD

**Issue by loeffelpan** [librespot-org/librespot-java#41]
I get `LineUnavailableExecption` on each attempt to play.
There is no pulse daemon configured on the system. It's OSMC where I just set ALSA to use usb sound card by default with 48000 kHz sample rate.
KODI is running on the same device and uses HDMI for audio and video playback.

**asound.conf**
```
ctl.!default {
        type hw
        card 1
}

pcm.!default {
        type plug
        slave {
                pcm "hw:1"
                rate 48000
        }
}
```

**Librespot log**
```
2019-01-10 20:43:07 DEBUG PlayerRunner:83 - Mixer for playback: PulseAudio Mixer, version 0.02
2019-01-10 20:43:07 FATAL TrackHandler:62 - Failed starting playback!
xyz.gianlu.librespot.player.PlayerRunner$PlayerException: javax.sound.sampled.LineUnavailableException
        at xyz.gianlu.librespot.player.PlayerRunner.initializeSound(PlayerRunner.java:156)
        at xyz.gianlu.librespot.player.PlayerRunner.<init>(PlayerRunner.java:69)
        at xyz.gianlu.librespot.player.TrackHandler.load(TrackHandler.java:52)
        at xyz.gianlu.librespot.player.TrackHandler.access$600(TrackHandler.java:21)
        at xyz.gianlu.librespot.player.TrackHandler$Looper.run(TrackHandler.java:155)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.sound.sampled.LineUnavailableException
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openImpl(PulseAudioMixer.java:714)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:588)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:584)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.open(PulseAudioMixer.java:579)
        at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:94)
        at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:75)
        at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:90)
        at xyz.gianlu.librespot.player.PlayerRunner.initializeSound(PlayerRunner.java:154)
        ... 5 more
2019-01-10 20:43:07 FATAL Player:226 - Failed loading track, gid: C63B032F82EB4899B897B65E4247E1BB
xyz.gianlu.librespot.player.PlayerRunner$PlayerException: javax.sound.sampled.LineUnavailableException
        at xyz.gianlu.librespot.player.PlayerRunner.initializeSound(PlayerRunner.java:156)
        at xyz.gianlu.librespot.player.PlayerRunner.<init>(PlayerRunner.java:69)
        at xyz.gianlu.librespot.player.TrackHandler.load(TrackHandler.java:52)
        at xyz.gianlu.librespot.player.TrackHandler.access$600(TrackHandler.java:21)
        at xyz.gianlu.librespot.player.TrackHandler$Looper.run(TrackHandler.java:155)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.sound.sampled.LineUnavailableException
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openImpl(PulseAudioMixer.java:714)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:588)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:584)
        at org.classpath.icedtea.pulseaudio.PulseAudioMixer.open(PulseAudioMixer.java:579)
        at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:94)
        at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:75)
        at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:90)
        at xyz.gianlu.librespot.player.PlayerRunner.initializeSound(PlayerRunner.java:154)
        ... 5 more
```

**Comment by devgianlu** [comment]
This exception usually means that the device is already in use.

**Comment by loeffelpan** [comment]
Seems to be right. Working since selecting another mixer (e. g. ALSA) with #40.
Thanks.

**Comment by devgianlu** [comment]
https://github.com/librespot-org/librespot-java/issues/40#issuecomment-453649311

**Comment by loeffelpan** [comment]
You are my hero of the day.
Working flawlessly on my RPi with OSMC now.

Thank you very much for the rapid development.
