### ISSUE TITLE
EOFException when leaving Librespot alone

### ISSUE THREAD

**Issue by loeffelpan** [librespot-org/librespot-java#43]
Yesterday I played some songs. Paused the playback and leaved the room.
Spotify app quit automaticly after a couple of time on my iPhone. Today I found this in the afternoon.
Seems to be the paused track causes a kind of timeout after hours?
Should I end playback another way? The device with Librespot is always on and so librespot will be always on and ready to connect.

```
Jan 14 17:35:36 osmc java[5188]: 2019-01-14 17:35:36 TRACE Session:563 - Handled PongAck
Jan 14 17:37:36 osmc java[5188]: 2019-01-14 17:37:36 TRACE Session:557 - Handled Ping
Jan 14 17:37:36 osmc java[5188]: 2019-01-14 17:37:36 TRACE Session:563 - Handled PongAck
Jan 14 17:38:08 osmc java[5188]: 2019-01-14 17:38:08 FATAL Session:549 - Failed reading packet!
Jan 14 17:38:08 osmc java[5188]: java.io.EOFException
Jan 14 17:38:08 osmc java[5188]:         at java.io.DataInputStream.readFully(DataInputStream.java:197)
Jan 14 17:38:08 osmc java[5188]:         at java.io.DataInputStream.readFully(DataInputStream.java:169)
Jan 14 17:38:08 osmc java[5188]:         at xyz.gianlu.librespot.crypto.CipherPair.receiveEncoded(CipherPair.java:60)
Jan 14 17:38:08 osmc java[5188]:         at xyz.gianlu.librespot.core.Session$Receiver.run(Session.java:542)
Jan 14 17:38:08 osmc java[5188]:         at java.lang.Thread.run(Thread.java:748)
```

**Comment by loeffelpan** [comment]
Same issue even after implementation of reconnection.

**Comment by devgianlu** [comment]
It's not fully implement yet.

**Comment by loeffelpan** [comment]
I thought this was implemented with #42 ?

**Comment by loeffelpan** [comment]
Just compiled that for me.
I will give a report in a few days.

**Comment by loeffelpan** [comment]
Never faced this issue again.
Thanks a lot.
