### ISSUE TITLE
Exception in thread "handle-packet-3146781"

### ISSUE THREAD

**Issue by loeffelpan** [librespot-org/librespot-java#44]
Call me a bug finder, but I have another issue concerning reconnecting.

Steps to reproduce:
1. First connection with Spotify app 1 (iPhone) and play some song.
2. Close connection (and app 1).
(At this point reconnecting from the same app on my iPhone would work fine.)
3. Taking another Spotify app 2 (iPad or another iPhone) and try to reconnect.
4. Connection seems to be fine but on pressing play I see following error message.
5. Disconnecting and reconnecting again works at this point.

```
Jan 19 00:34:15 osmc java[32469]: Exception in thread "handle-packet-32031319" java.lang.IllegalStateException: Looper is stopped!
Jan 19 00:34:15 osmc java[32469]:         at xyz.gianlu.librespot.player.TrackHandler.sendCommand(TrackHandler.java:70)
Jan 19 00:34:15 osmc java[32469]:         at xyz.gianlu.librespot.player.TrackHandler.sendStop(TrackHandler.java:87)
Jan 19 00:34:15 osmc java[32469]:         at xyz.gianlu.librespot.player.Player.frame(Player.java:86)
Jan 19 00:34:15 osmc java[32469]:         at xyz.gianlu.librespot.spirc.SpotifyIrc$SpircListener.event(SpotifyIrc.java:193)
Jan 19 00:34:15 osmc java[32469]:         at xyz.gianlu.librespot.mercury.MercuryClient$InternalSubListener.dispatch(MercuryClient.java:237)
Jan 19 00:34:15 osmc java[32469]:         at xyz.gianlu.librespot.mercury.MercuryClient.handle(MercuryClient.java:167)
Jan 19 00:34:15 osmc java[32469]:         at xyz.gianlu.librespot.core.PacketsManager$Looper.lambda$run$0(PacketsManager.java:64)
Jan 19 00:34:15 osmc java[32469]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Jan 19 00:34:15 osmc java[32469]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Jan 19 00:34:15 osmc java[32469]:         at java.lang.Thread.run(Thread.java:748)
```

**Comment by devgianlu** [comment]
Not quite sure what it was, but it won't happen again.

**Comment by loeffelpan** [comment]
Unfortunately I faced this issue again.
This this the error occured on the first try of connecting with zeroconf. Server was started over a day before.
Second connection attempt works.

Please check again.

**Comment by devgianlu** [comment]
Can you post the new stacktrace? Or is it the same?

**Comment by loeffelpan** [comment]
At least very similar.
I will take another trace when the error occurs.

**Comment by loeffelpan** [comment]
I got this at first connection attempt after starting the server. Maybe another issue.
I will report if the initial exception appears again or if it's this one every time.

```
Jan 31 19:30:55 osmc java[4809]: Exception in thread "track-handler-31211803" java.lang.IllegalStateException: Session isn't authenticated!
Jan 31 19:30:55 osmc java[4809]:         at xyz.gianlu.librespot.core.Session.audioKey(Session.java:282)
Jan 31 19:30:55 osmc java[4809]:         at xyz.gianlu.librespot.player.StreamFeeder.load(StreamFeeder.java:53)
Jan 31 19:30:55 osmc java[4809]:         at xyz.gianlu.librespot.player.StreamFeeder.load(StreamFeeder.java:76)
Jan 31 19:30:55 osmc java[4809]:         at xyz.gianlu.librespot.player.StreamFeeder.load(StreamFeeder.java:88)
Jan 31 19:30:55 osmc java[4809]:         at xyz.gianlu.librespot.player.TrackHandler.load(TrackHandler.java:45)
Jan 31 19:30:55 osmc java[4809]:         at xyz.gianlu.librespot.player.TrackHandler.access$600(TrackHandler.java:21)
Jan 31 19:30:55 osmc java[4809]:         at xyz.gianlu.librespot.player.TrackHandler$Looper.run(TrackHandler.java:166)
Jan 31 19:30:55 osmc java[4809]:         at java.lang.Thread.run(Thread.java:748)
```

**Comment by devgianlu** [comment]
That is indeed a differente issue, but it should be fixed now.
