### ISSUE TITLE
BadAuth when creating session

### ISSUE THREAD

**Issue by KagChi** [librespot-org/librespot-java#488]
**Describe the bug**
Somehow I can't login to spotify account, it always throwing BadAuth error, I tried with other account, still same. (im sure the pass i use is valid, tried on web player) 

**To Reproduce**
Login as usual

**Expected behavior**
Logged in with provided account

**Screenshots/Stracktraces/Logs**
![Screenshot_2022-04-21-18-18-29-07](https://user-images.githubusercontent.com/59391215/164447176-5a1cb9ce-9aab-4e67-9906-3cd8ed309fe2.jpg)

**Version/Commit**
c3473bda8a70fad209c8525b04c2fd23ccc0d2fa

**Comment by KagChi** [comment]
Note: this error does not throw when using proxy.

**Comment by jpgrovy** [comment]
Is this working for you today?

**Comment by KagChi** [comment]
> Is this working for you today?

no, is it possible to get IP ban?

**Comment by jpgrovy** [comment]
I’m not sure. It’s very frustrating.  I really need to fix this 😭

**Comment by jpgrovy** [comment]
I don’t think it’s an ip ban issue.  I tried making a whole new deployment on a new server and it’s not working for me.

**Comment by iscle** [comment]
If it's not shown when using a proxy it must be something related to your IP... Which proxy did you use?

**Comment by KagChi** [comment]
i use [webshare.io](https://www.webshare.io/) proxy

**Comment by bs2kbs2k** [comment]
Same issue on an android app that I custom-built. Username and passwords are being passed in correctly yet it throws BadCredentials.

**Comment by iscle** [comment]
@bs2kbs2k @KagChi Can you post the full log please? Set the logLevel to all in the config file first :)

**Comment by KagChi** [comment]
Its was working yesterday. but i think the reason i got blocked is because too many times relogin to that account. 

iirc the error is same if you provide wrong creds.

**Comment by bs2kbs2k** [comment]
> @bs2kbs2k @KagChi Can you post the full log please? Set the logLevel to all in the config file first :)

```
2022-05-07 20:37:15,175 INFO  ApResolver:90 - Loaded aps into pool: {accesspoint=[ap-gae2.spotify.com:4070, ap-gae2.spotify.com:443, ap-gae2.spotify.com:80, ap-gew1.spotify.com:4070, ap-guc3.spotify.com:443], dealer=[gae2-dealer.spotify.com:443, guc3-dealer.spotify.com:443, gew1-dealer.spotify.com:443], spclient=[gae2-spclient.spotify.com:443, guc3-spclient.spotify.com:443, gew1-spclient.spotify.com:443]}
2022-05-07 20:37:15,268 DEBUG TimeProvider:90 - Loaded time offset from NTP: 13ms
2022-05-07 20:37:15,994 INFO  Session:137 - Created new session! {deviceId: 2c89be24c40cc491dd131e3c5f06b98adae0dc40, ap: ap-gew1.spotify.com:4070, proxy: false} 
2022-05-07 20:37:16,831 INFO  Session:331 - Connected successfully!
2022-05-07 20:37:17,342 ERROR Log4JUncaughtExceptionHandler:31 - [main]
xyz.gianlu.librespot.core.Session$SpotifyAuthenticationException: BadCredentials
        at xyz.gianlu.librespot.core.Session.authenticatePartial(Session.java:450) ~[librespot-player-1.6.2.jar:1.6.2]
        at xyz.gianlu.librespot.core.Session.authenticate(Session.java:339) ~[librespot-player-1.6.2.jar:1.6.2]
        at xyz.gianlu.librespot.core.Session.access$600(Session.java:77) ~[librespot-player-1.6.2.jar:1.6.2]
        at xyz.gianlu.librespot.core.Session$Builder.create(Session.java:1029) ~[librespot-player-1.6.2.jar:1.6.2]
        at xyz.gianlu.librespot.player.Main.main(Main.java:80) ~[librespot-player-1.6.2.jar:1.6.2]
```

**Comment by bs2kbs2k** [comment]
I ripped out everything on my android app so the player log is there

**Comment by jpgrovy** [comment]
Has anyone found a fix for Bad Credential error?  Works fine running locally but doesnt work when hosted on Heroku for example.

**Comment by KagChi** [comment]
Use proxy for temp fix

**Comment by jpgrovy** [comment]
Do you have an example how to do this on Heroku ?

>

**Comment by KagChi** [comment]
Wdym? just configure your session [conf](https://github.com/librespot-org/librespot-java/tree/dev/lib#getting-started)

**Comment by arch-btw** [comment]
I'm getting the same error with a SOCKS proxy, is that what you meant?

**Comment by jpgrovy** [comment]
I wasn’t using any proxies and didn’t have any problems for 6+ months. Now all of a sudden I get Bad Credentials error

**Comment by KagChi** [comment]
![image](https://user-images.githubusercontent.com/59391215/206735955-c149cfa9-183c-4af5-9c5a-43f1bd841986.png)

Looks like proxy isnt working now, still got bad authorizations.

**Comment by KagChi** [comment]
@Iscle https://hastebin.de/ozejeniwiw.apache here is the full stackrace, please investigate out

**Comment by jpgrovy** [comment]
> ![image](https://user-images.githubusercontent.com/59391215/206735955-c149cfa9-183c-4af5-9c5a-43f1bd841986.png)
> 
> Looks like proxy isnt working now, still got bad authorizations.

They made a lot of changes yesterday. They are blocking IP’s now of data centers. They have done this in the past and then reversed it.  Proxies must be good residential proxies for sure to work.

**Comment by KagChi** [comment]
> > ![image](https://user-images.githubusercontent.com/59391215/206735955-c149cfa9-183c-4af5-9c5a-43f1bd841986.png)
> > Looks like proxy isnt working now, still got bad authorizations.
> 
> They made a lot of changes yesterday. They are blocking IP’s now of data centers. They have done this in the past and then reversed it. Proxies must be good residential proxies for sure to work.

Proxy has no effect this time, tested on my local it works neither proxied nor doesnt

**Comment by jpgrovy** [comment]
> > > ![image](https://user-images.githubusercontent.com/59391215/206735955-c149cfa9-183c-4af5-9c5a-43f1bd841986.png)
> > > Looks like proxy isnt working now, still got bad authorizations.
> > 
> > 
> > They made a lot of changes yesterday. They are blocking IP’s now of data centers. They have done this in the past and then reversed it. Proxies must be good residential proxies for sure to work.
> 
> Proxy has no effect this time, tested on my local it works neither proxied nor doesnt

You can’t even log in locally ?

**Comment by KagChi** [comment]
> > > > ![image](https://user-images.githubusercontent.com/59391215/206735955-c149cfa9-183c-4af5-9c5a-43f1bd841986.png)
> > > > Looks like proxy isnt working now, still got bad authorizations.
> > > 
> > > 
> > > They made a lot of changes yesterday. They are blocking IP’s now of data centers. They have done this in the past and then reversed it. Proxies must be good residential proxies for sure to work.
> > 
> > 
> > Proxy has no effect this time, tested on my local it works neither proxied nor doesnt
> 
> You can’t even log in locally ?

I mean, i can log in with same proxy or without proxy. so i suppose the proxy has no effect rn

**Comment by jpgrovy** [comment]
The “Bad Credentials” error is gone ?

**Comment by KagChi** [comment]
It doesnt throw the error on my local pc, but it does throw the error on my
vps

**Comment by jpgrovy** [comment]
Ok.. so same problem then.  And you’ve tried good proxies on your vps?  Spotify started blocking all vps provider ip’s. 



>

**Comment by KagChi** [comment]
I already said, proxy has no effect. the proxy only proxy http request. i
dont think we login to Spotify only using their http. pretty sure they have
ws

**Comment by leon-sleepinglion** [comment]
I found a workaround for this issue.

Steps.

1. Log in **locally** following the [suggested way](https://github.com/librespot-org/librespot-java/tree/dev/player#get-started).
2. Copy the  `credentials.json` from local to VPS.
3. On **VPS**, log in using [stored credentials](https://github.com/librespot-org/librespot-java/tree/dev/player#stored-credentials).
4. Voila. 🎉
