### ISSUE TITLE
BufferUnderflowExeption?

### ISSUE THREAD

**Issue by loeffelpan** [librespot-org/librespot-java#49]
Close of #48 leads me to this while playback. Need to restart librespot after this.
Could you please take look?

```
Feb 16 18:06:25 osmc java[31427]: Exception in thread "channel-queue-6691589" java.nio.BufferUnderflowException
Feb 16 18:06:25 osmc java[31427]:         at java.nio.Buffer.nextGetIndex(Buffer.java:506)
Feb 16 18:06:25 osmc java[31427]:         at java.nio.HeapByteBuffer.getShort(HeapByteBuffer.java:310)
Feb 16 18:06:25 osmc java[31427]:         at xyz.gianlu.librespot.player.ChannelManager$Channel.handle(ChannelManager.java:132)
Feb 16 18:06:25 osmc java[31427]:         at xyz.gianlu.librespot.player.ChannelManager$Channel.access$700(ChannelManager.java:96)
Feb 16 18:06:25 osmc java[31427]:         at xyz.gianlu.librespot.player.ChannelManager$Channel$Handler.run(ChannelManager.java:166)
Feb 16 18:06:25 osmc java[31427]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Feb 16 18:06:25 osmc java[31427]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Feb 16 18:06:25 osmc java[31427]:         at java.lang.Thread.run(Thread.java:748)
```

**Comment by devgianlu** [comment]
That looks like a protocol issue, please roll back to pre #48 until I fix this.

**Comment by devgianlu** [comment]
That looks like a protocol issue, please roll back to pre #48 until I fix this.
