### ISSUE TITLE
When switching Spotify User I got an Nullpointer Exception

### ISSUE THREAD

**Issue by xMordax** [librespot-org/librespot-java#52]
While listening to a track on ZEROCONF, I tried to switch to another Spotify user but librespot-java was not available anymore.
Here the logs:
```
2019-03-09 14:03:43 TRACE AudioFileStreaming:99 - Chunk 49/71 completed, cached: false, fileId: ABB7E97E9329EC437292F207B23F24CCD2D36C5A
2019-03-09 14:03:47 TRACE AudioFileStreaming:99 - Chunk 50/71 completed, cached: false, fileId: ABB7E97E9329EC437292F207B23F24CCD2D36C5A
2019-03-09 14:03:50 TRACE AudioFileStreaming:99 - Chunk 51/71 completed, cached: false, fileId: ABB7E97E9329EC437292F207B23F24CCD2D36C5A
2019-03-09 14:03:54 TRACE SpotifyIrc:101 - Send frame, type: kMessageTypeGoodbye
2019-03-09 14:03:54 TRACE MercuryClient:104 - Send Mercury request, seq: 37, uri: hm://remote/user/asd/, method: SEND
Exception in thread "session-packet-receiver" java.lang.NullPointerException
        at xyz.gianlu.librespot.core.Session$Receiver.run(Session.java:678)
        at java.lang.Thread.run(Thread.java:748)
2019-03-09 14:03:54 DEBUG LinesHolder:114 - Removed closed line, remaining: 0
2019-03-09 14:03:54 TRACE PlayerRunner:271 - Cleaned up player.
```
Afterwards the  librespot-java client did not react anymore, had to restart the java process.

What could it be?

**Comment by xMordax** [comment]
I was able to reproduce this issue, if you have two Spotify users and ZEROCONF configured, follow these steps:

1. Start listening to a song with the first user on librespot-java client
2. Meanwhile start listening to a song on the second account locally on your device(in my case it was my main computer)
3. Connect with your second account to the librespot-java client, meanwhile listening to the song

Crash should occur, here again the logs:

```
2019-03-10 09:12:34 TRACE AudioFileStreaming:99 - Chunk 42/62 completed, cached: false, fileId: 8B81677AAD27D68093663A10B6C22EAEDA94F80F
2019-03-10 09:12:34 TRACE Session:645 - Handled Ping
2019-03-10 09:12:35 TRACE Session:651 - Handled PongAck
2019-03-10 09:12:38 TRACE AudioFileStreaming:99 - Chunk 43/62 completed, cached: false, fileId: 8B81677AAD27D68093663A10B6C22EAEDA94F80F
2019-03-10 09:12:41 TRACE AudioFileStreaming:99 - Chunk 44/62 completed, cached: false, fileId: 8B81677AAD27D68093663A10B6C22EAEDA94F80F
2019-03-10 09:12:45 TRACE SpotifyIrc:101 - Send frame, type: kMessageTypeGoodbye
2019-03-10 09:12:45 TRACE MercuryClient:104 - Send Mercury request, seq: 68, uri: hm://remote/user/aasdsad/, method: SEND
2019-03-10 09:12:46 DEBUG LinesHolder:114 - Removed closed line, remaining: 0
2019-03-10 09:12:46 TRACE PlayerRunner:271 - Cleaned up player.
Exception in thread "session-packet-receiver" java.lang.NullPointerException
        at xyz.gianlu.librespot.core.Session$Receiver.run(Session.java:678)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by devgianlu** [comment]
Not very easy for me to test this as I don't have another account, but I think I might be able to.

**Comment by xMordax** [comment]
PM me on mail I can hand you mine for testing...

**Comment by devgianlu** [comment]
I've literally just moved a single line of code, but did not test it. Could you try again?

**Comment by xMordax** [comment]
I can test it next time I get visitors.

**Comment by devgianlu** [comment]
Tested, looks alright.
