### ISSUE TITLE
Token expired, send Mercury request, Request timeout out

### ISSUE THREAD

**Issue by AndreKR** [librespot-org/librespot-java#554]
**Describe the bug**
After running for a while the device doesn't appear as a device in Spotify anymore. Checking the logs shows a repeated loop of failed reconnects.

A restart fixed the issue for now.

**To Reproduce**
I just let it run idle for a couple of days.

**Expected behavior**
The librespot-java instance should appear in Spotify on another device ready to play on it.

**Screenshots/Stracktraces/Logs**
```
[...]
2023-01-15 21:44:26,224 DEBUG TokenProvider:67 - Token expired or not suitable, requesting again. {scopes: [playlist-read], oldToken: null}
2023-01-15 21:44:26,224 TRACE MercuryClient:156 - Send Mercury request, seq: 16738, uri: hm://keymaster/token/authenticated?scope=playlist-read&client_id=65b7[REDACTED]&device_id=61a8[REDACTED], method: GET
2023-01-15 21:44:29,224 ERROR DealerClient:278 - Failed reconnecting, retrying...
java.io.IOException: Request timeout out, 3000 passed, yet no response. {seq: 16738}
        at xyz.gianlu.librespot.mercury.MercuryClient.sendSync(MercuryClient.java:94) ~[player.jar:1.6.2]
        at xyz.gianlu.librespot.mercury.MercuryClient.sendSync(MercuryClient.java:104) ~[player.jar:1.6.2]
        at xyz.gianlu.librespot.core.TokenProvider.getToken(TokenProvider.java:68) ~[player.jar:1.6.2]
        at xyz.gianlu.librespot.core.TokenProvider.get(TokenProvider.java:79) ~[player.jar:1.6.2]
        at xyz.gianlu.librespot.dealer.DealerClient.connect(DealerClient.java:79) ~[player.jar:1.6.2]
        at xyz.gianlu.librespot.dealer.DealerClient.lambda$connectionInvalided$3(DealerClient.java:276) ~[player.jar:1.6.2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
2023-01-15 21:44:29,224 TRACE DealerClient:271 - Scheduled reconnection attempt in 10 seconds...
2023-01-15 21:44:39,225 DEBUG TokenProvider:67 - Token expired or not suitable, requesting again. {scopes: [playlist-read], oldToken: null}
2023-01-15 21:44:39,225 TRACE MercuryClient:156 - Send Mercury request, seq: 16739, uri: hm://keymaster/token/authenticated?scope=playlist-read&client_id=65b7[REDACTED]&device_id=61a8[REDACTED], method: GET
2023-01-15 21:44:42,226 ERROR DealerClient:278 - Failed reconnecting, retrying...
java.io.IOException: Request timeout out, 3000 passed, yet no response. {seq: 16739}
        at xyz.gianlu.librespot.mercury.MercuryClient.sendSync(MercuryClient.java:94) ~[player.jar:1.6.2]
        at xyz.gianlu.librespot.mercury.MercuryClient.sendSync(MercuryClient.java:104) ~[player.jar:1.6.2]
        at xyz.gianlu.librespot.core.TokenProvider.getToken(TokenProvider.java:68) ~[player.jar:1.6.2]
        at xyz.gianlu.librespot.core.TokenProvider.get(TokenProvider.java:79) ~[player.jar:1.6.2]
        at xyz.gianlu.librespot.dealer.DealerClient.connect(DealerClient.java:79) ~[player.jar:1.6.2]
        at xyz.gianlu.librespot.dealer.DealerClient.lambda$connectionInvalided$3(DealerClient.java:276) ~[player.jar:1.6.2]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
2023-01-15 21:44:42,226 TRACE DealerClient:271 - Scheduled reconnection attempt in 10 seconds...
```

**Version/Commit**
I couldn't find a version number in the log. I'm using this image: https://hub.docker.com/r/agneev/librespot-java

**Comment by thedtvn** [comment]
same  when  host  on linux
