### ISSUE TITLE
Failed reading packet

### ISSUE THREAD

**Issue by xMordax** [librespot-org/librespot-java#56]
Got an exception in the middle of a song when listening on ZEROCONF.

```2019-03-15 12:59:25 TRACE MercuryClient:104 - Send Mercury request, seq: 347, uri: hm://remote/3/user/xxxxxxxx/, method: POST
2019-03-15 12:59:26 INFO  Session:696 - Skipping Pause
2019-03-15 12:59:26 TRACE MercuryClient:146 - Handling packet, cmd: MercuryReq, seq: 347, flags: 1, parts: 1
2019-03-15 12:59:26 TRACE SpotifyIrc:118 - Frame sent successfully, type: kMessageTypeNotify
2019-03-15 12:59:27 TRACE AudioFileStreaming:99 - Chunk 1/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 12:59:32 TRACE AudioFileStreaming:99 - Chunk 2/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 12:59:35 TRACE AudioFileStreaming:99 - Chunk 3/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 12:59:38 TRACE AudioFileStreaming:99 - Chunk 4/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 12:59:40 TRACE AudioFileStreaming:99 - Chunk 5/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 12:59:44 TRACE AudioFileStreaming:99 - Chunk 6/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 12:59:48 TRACE AudioFileStreaming:99 - Chunk 7/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 12:59:52 TRACE AudioFileStreaming:99 - Chunk 8/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 12:59:55 TRACE AudioFileStreaming:99 - Chunk 9/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 12:59:59 TRACE AudioFileStreaming:99 - Chunk 10/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:00:03 TRACE AudioFileStreaming:99 - Chunk 11/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:00:06 TRACE AudioFileStreaming:99 - Chunk 12/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:00:10 TRACE AudioFileStreaming:99 - Chunk 13/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:00:13 TRACE AudioFileStreaming:99 - Chunk 14/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:00:17 TRACE AudioFileStreaming:99 - Chunk 15/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:00:20 TRACE AudioFileStreaming:99 - Chunk 16/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:00:24 TRACE AudioFileStreaming:99 - Chunk 17/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:00:28 TRACE AudioFileStreaming:99 - Chunk 18/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:00:32 TRACE AudioFileStreaming:99 - Chunk 19/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:00:36 TRACE AudioFileStreaming:99 - Chunk 20/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:00:36 TRACE Session:660 - Handled Ping
2019-03-15 13:00:37 TRACE Session:666 - Handled PongAck
2019-03-15 13:00:39 TRACE AudioFileStreaming:99 - Chunk 21/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:00:43 TRACE AudioFileStreaming:99 - Chunk 22/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:00:46 TRACE AudioFileStreaming:99 - Chunk 23/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:00:50 TRACE AudioFileStreaming:99 - Chunk 24/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:00:53 TRACE AudioFileStreaming:99 - Chunk 25/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:00:57 TRACE AudioFileStreaming:99 - Chunk 26/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:01:01 TRACE AudioFileStreaming:99 - Chunk 27/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:01:04 TRACE AudioFileStreaming:99 - Chunk 28/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:01:08 TRACE AudioFileStreaming:99 - Chunk 29/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:01:12 TRACE AudioFileStreaming:99 - Chunk 30/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:01:16 TRACE AudioFileStreaming:99 - Chunk 31/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:01:20 TRACE AudioFileStreaming:99 - Chunk 32/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:01:23 TRACE AudioFileStreaming:99 - Chunk 33/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:01:27 TRACE AudioFileStreaming:99 - Chunk 34/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:01:30 TRACE AudioFileStreaming:99 - Chunk 35/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:01:34 TRACE AudioFileStreaming:99 - Chunk 36/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:01:38 TRACE AudioFileStreaming:99 - Chunk 37/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:01:41 TRACE AudioFileStreaming:99 - Chunk 38/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:01:45 TRACE AudioFileStreaming:99 - Chunk 39/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:01:49 TRACE AudioFileStreaming:99 - Chunk 40/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:01:52 TRACE AudioFileStreaming:99 - Chunk 41/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:01:56 TRACE AudioFileStreaming:99 - Chunk 42/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:01:59 TRACE AudioFileStreaming:99 - Chunk 43/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:02:03 TRACE AudioFileStreaming:99 - Chunk 44/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:02:07 TRACE AudioFileStreaming:99 - Chunk 45/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:02:10 TRACE AudioFileStreaming:99 - Chunk 46/92 completed, cached: false, fileId: EE165038572EF3A9F394F0BF754B639A6C4F31ED
2019-03-15 13:02:11 FATAL Session:649 - Failed reading packet!
java.io.EOFException
        at java.io.DataInputStream.readFully(DataInputStream.java:197)
        at java.io.DataInputStream.readFully(DataInputStream.java:169)
        at xyz.gianlu.librespot.crypto.CipherPair.receiveEncoded(CipherPair.java:60)
        at xyz.gianlu.librespot.core.Session$Receiver.run(Session.java:641)
        at java.lang.Thread.run(Thread.java:748)
2019-03-15 13:02:12 INFO  Session:199 - Connected successfully!
Exception in thread "session-packet-receiver" java.lang.RuntimeException: Failed reconnecting!
        at xyz.gianlu.librespot.core.Session.reconnect(Session.java:408)
        at xyz.gianlu.librespot.core.Session.access$700(Session.java:44)
        at xyz.gianlu.librespot.core.Session$Receiver.run(Session.java:650)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
        at java.io.DataInputStream.readFully(DataInputStream.java:197)
        at java.io.DataInputStream.readFully(DataInputStream.java:169)
        at xyz.gianlu.librespot.crypto.CipherPair.receiveEncoded(CipherPair.java:60)
        at xyz.gianlu.librespot.core.Session.authenticatePartial(Session.java:232)
        at xyz.gianlu.librespot.core.Session.reconnect(Session.java:398)
        ... 3 more
```

Afterwards I could not reconnect to the librespot-java client till I restarted the application.

**Comment by devgianlu** [comment]
That was probably due to a long network hick up. Not really sure what to do about it.

**Comment by xMordax** [comment]
I never did something like this but what if you would catch exceptions like that and restart the librespot client over ProcessBuilder or something in that direction?
What about if you build in timeout exceptions, meaning, in a case where it cannot read packets it has a bit of a timeout and retries several time to reconnect?

Regards

**Comment by devgianlu** [comment]
How much bandwidth do you have? I guess all these hiccups are caused by network latency issues. Can you run a speed test? So that I have a baseline to test the code against.

**Comment by xMordax** [comment]
![cda8af4a-43c5-4c59-9c46-0829c66d3d8d](https://user-images.githubusercontent.com/27705384/54498223-bf518b80-4904-11e9-9c26-7bc76dc2c3a9.jpeg)

**Comment by xMordax** [comment]
![cda8af4a-43c5-4c59-9c46-0829c66d3d8d](https://user-images.githubusercontent.com/27705384/54498242-f9229200-4904-11e9-9aff-b5937041372d.png)

**Comment by xMordax** [comment]
here some more logs:
```
2019-03-20 10:09:38 TRACE MercuryClient:104 - Send Mercury request, seq: 169, uri: hm://remote/3/user/USER/, method: POST
2019-03-20 10:09:38 TRACE MercuryClient:146 - Handling packet, cmd: MercuryReq, seq: 169, flags: 1, parts: 1
2019-03-20 10:09:38 TRACE SpotifyIrc:118 - Frame sent successfully, type: kMessageTypeNotify
2019-03-20 10:10:00 DEBUG TimeProvider:20 - Corrected time offset, delta: 0s
2019-03-20 10:10:00 TRACE Session:683 - Handled Ping {payload: 5C920368}
2019-03-20 10:10:00 TRACE Session:689 - Handled PongAck {payload: 5C920368}
2019-03-20 10:10:07 FATAL CdnManager:230 - Failed requesting chunk, index: 11
java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
        at xyz.gianlu.librespot.cdn.CdnManager$AudioUrl.sendRequest(CdnManager.java:116)
        at xyz.gianlu.librespot.cdn.CdnManager$AudioUrl.access$900(CdnManager.java:95)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$CdnLoader.request(CdnManager.java:254)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$CdnLoader.request(CdnManager.java:249)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:226)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer.access$1600(CdnManager.java:137)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-03-20 10:10:10 FATAL CdnManager:230 - Failed requesting chunk, index: 12
java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
        at xyz.gianlu.librespot.cdn.CdnManager$AudioUrl.sendRequest(CdnManager.java:116)
        at xyz.gianlu.librespot.cdn.CdnManager$AudioUrl.access$900(CdnManager.java:95)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$CdnLoader.request(CdnManager.java:254)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$CdnLoader.request(CdnManager.java:249)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:226)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer.access$1600(CdnManager.java:137)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-03-20 10:10:14 FATAL CdnManager:230 - Failed requesting chunk, index: 13
java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
        at xyz.gianlu.librespot.cdn.CdnManager$AudioUrl.sendRequest(CdnManager.java:116)
        at xyz.gianlu.librespot.cdn.CdnManager$AudioUrl.access$900(CdnManager.java:95)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$CdnLoader.request(CdnManager.java:254)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$CdnLoader.request(CdnManager.java:249)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:226)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer.access$1600(CdnManager.java:137)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-03-20 10:12:00 DEBUG TimeProvider:20 - Corrected time offset,
```
Afterwards my Spotify Client was showing me like the song is playing but librespot-java client didnt play the music.

**Comment by xMordax** [comment]
Another thing I noticed is that if you pause in the middle of the song the Spotify client jumps to the end of the song in the progress bar If you click play again it continues where it left but the progress bar starts from the beginning, after few seconds it again crashes... here the logs:
```
2019-03-20 11:13:58 TRACE MercuryClient:104 - Send Mercury request, seq: 33, uri: hm://remote/3/user/USER/, method: POST
2019-03-20 11:13:59 TRACE MercuryClient:146 - Handling packet, cmd: MercuryReq, seq: 33, flags: 1, parts: 1
2019-03-20 11:13:59 TRACE SpotifyIrc:118 - Frame sent successfully, type: kMessageTypeNotify
Exception in thread "pool-7-thread-5" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at xyz.gianlu.librespot.common.NetUtils.parseStatusLine(NetUtils.java:21)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$CdnLoader.request(CdnManager.java:256)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$CdnLoader.request(CdnManager.java:249)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:226)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer.access$1600(CdnManager.java:137)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-7-thread-6" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at xyz.gianlu.librespot.common.NetUtils.parseStatusLine(NetUtils.java:21)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$CdnLoader.request(CdnManager.java:256)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$CdnLoader.request(CdnManager.java:249)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:226)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer.access$1600(CdnManager.java:137)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-7-thread-7" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at xyz.gianlu.librespot.common.NetUtils.parseStatusLine(NetUtils.java:21)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$CdnLoader.request(CdnManager.java:256)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$CdnLoader.request(CdnManager.java:249)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:226)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer.access$1600(CdnManager.java:137)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Exception in thread "pool-7-thread-8" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1967)
        at xyz.gianlu.librespot.common.NetUtils.parseStatusLine(NetUtils.java:21)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$CdnLoader.request(CdnManager.java:256)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$CdnLoader.request(CdnManager.java:249)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer.requestChunk(CdnManager.java:226)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer.access$1600(CdnManager.java:137)
        at xyz.gianlu.librespot.cdn.CdnManager$Streamer$InternalStream.lambda$requestChunkFromStream$0(CdnManager.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-03-20 11:14:18 DEBUG TimeProvider:20 - Corrected time offset, delta: -1s
```

**Comment by devgianlu** [comment]
I've added some countermeasures to possibly avoid this in the feature.
