### ISSUE TITLE
SpotifyAuthenticationException: PremiumAccountRequired

### ISSUE THREAD

**Issue by kokarare1212** [librespot-org/librespot-java#614]
**Describe the bug**
Spotify seems to have made some changes and USER_PASS, ZEROCONF login is no longer available.
Of course, the account is a Premium account.
This is the [same problem](https://github.com/kokarare1212/librespot-python/issues/193) with [librespot-python](https://github.com/kokarare1212/librespot-python), which has been ported to Python.

**To Reproduce**
Download and run librespot-player-1.6.2.jar from the release page.

**Expected behavior**
The login should complete successfully with no exceptions.

**Screenshots/Stracktraces/Logs**
```
xyz.gianlu.librespot.core.Session$SpotifyAuthenticationException: PremiumAccountRequired
        at xyz.gianlu.librespot.core.Session.authenticatePartial(Session.java:450) ~[librespot-player-1.6.2.jar:1.6.2]
        at xyz.gianlu.librespot.core.Session.authenticate(Session.java:339) ~[librespot-player-1.6.2.jar:1.6.2]
        at xyz.gianlu.librespot.core.Session.access$600(Session.java:77) ~[librespot-player-1.6.2.jar:1.6.2]
        at xyz.gianlu.librespot.core.Session$Builder.create(Session.java:1029) ~[librespot-player-1.6.2.jar:1.6.2]
        at xyz.gianlu.librespot.ZeroconfServer.handleAddUser(ZeroconfServer.java:367) ~[librespot-player-1.6.2.jar:1.6.2]
        at xyz.gianlu.librespot.ZeroconfServer.access$200(ZeroconfServer.java:56) ~[librespot-player-1.6.2.jar:1.6.2]
        at xyz.gianlu.librespot.ZeroconfServer$HttpRunner.handleRequest(ZeroconfServer.java:499) ~[librespot-player-1.6.2.jar:1.6.2]
        at xyz.gianlu.librespot.ZeroconfServer$HttpRunner.handle(ZeroconfServer.java:574) ~[librespot-player-1.6.2.jar:1.6.2]
        at xyz.gianlu.librespot.ZeroconfServer$HttpRunner.lambda$run$1(ZeroconfServer.java:482) ~[librespot-player-1.6.2.jar:1.6.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Version/Commit**
https://github.com/librespot-org/librespot-java/releases/tag/v1.6.2

**Comment by DanGurt** [comment]
The problem now also occurs with version 1.6.2 when trying to authenticate with USER_PASS
```
May 16 17:33:14 bash[7012]: 2023-05-16 17:33:14,170 INFO  Session:331 - Connected successfully!
May 16 17:33:14 bash[7012]: 2023-05-16 17:33:14,591 ERROR Log4JUncaughtExceptionHandler:31 - [main]
May 16 17:33:14 bash[7012]: xyz.gianlu.librespot.core.Session$SpotifyAuthenticationException: PremiumAccountRequired
May 16 17:33:14 bash[7012]:         at xyz.gianlu.librespot.core.Session.authenticatePartial(Session.java:450) ~[librespot-player-1.6.2.jar:1.6.2]
May 16 17:33:14 bash[7012]:         at xyz.gianlu.librespot.core.Session.authenticate(Session.java:339) ~[librespot-player-1.6.2.jar:1.6.2]
May 16 17:33:14 bash[7012]:         at xyz.gianlu.librespot.core.Session.access$600(Session.java:77) ~[librespot-player-1.6.2.jar:1.6.2]
May 16 17:33:14 bash[7012]:         at xyz.gianlu.librespot.core.Session$Builder.create(Session.java:1029) ~[librespot-player-1.6.2.jar:1.6.2]
May 16 17:33:14 bash[7012]:         at xyz.gianlu.librespot.player.Main.main(Main.java:80) ~[librespot-player-1.6.2.jar:1.6.2]
```

**Comment by justingood** [comment]
I am seeing the same error using Zeroconf as well

```
2023-05-16 17:54:04,336 INFO  ZeroconfServer:345 - Accepted new user from Pixel 5. {deviceId: a3zxnza29pchzhxwecjf9yb8ghdmpuuwbjpu828p2}
2023-05-16 17:54:05,381 INFO  Session:137 - Created new session! {deviceId: a3zxnza29pchzhxwecjf9yb8ghdmpuuwbjpu828p2, ap: ap-gae2.spotify.com:80, proxy: false}
2023-05-16 17:54:06,338 INFO  Session:331 - Connected successfully!
2023-05-16 17:54:06,895 ERROR ZeroconfServer:375 - Couldn't establish a new session.
xyz.gianlu.librespot.core.Session$SpotifyAuthenticationException: PremiumAccountRequired
	at xyz.gianlu.librespot.core.Session.authenticatePartial(Session.java:450) ~[librespot.jar:1.6.2]
	at xyz.gianlu.librespot.core.Session.authenticate(Session.java:339) ~[librespot.jar:1.6.2]
	at xyz.gianlu.librespot.core.Session.access$600(Session.java:77) ~[librespot.jar:1.6.2]
	at xyz.gianlu.librespot.core.Session$Builder.create(Session.java:1029) ~[librespot.jar:1.6.2]
	at xyz.gianlu.librespot.ZeroconfServer.handleAddUser(ZeroconfServer.java:367) ~[librespot.jar:1.6.2]
	at xyz.gianlu.librespot.ZeroconfServer.access$200(ZeroconfServer.java:56) ~[librespot.jar:1.6.2]
	at xyz.gianlu.librespot.ZeroconfServer$HttpRunner.handleRequest(ZeroconfServer.java:499) ~[librespot.jar:1.6.2]
	at xyz.gianlu.librespot.ZeroconfServer$HttpRunner.handle(ZeroconfServer.java:574) ~[librespot.jar:1.6.2]
	at xyz.gianlu.librespot.ZeroconfServer$HttpRunner.lambda$run$1(ZeroconfServer.java:482) ~[librespot.jar:1.6.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by i-do-cpp** [comment]
The fix is to provide a newer client version at https://github.com/librespot-org/librespot-java/blob/0a8e685/lib/src/main/java/xyz/gianlu/librespot/Version.java#L72.
Specifying `117300517` from https://github.com/librespot-org/librespot/blob/ae8387a/core/src/version.rs#L20 makes the login work again.

**Comment by kokarare1212** [comment]
They seem to work well!
I opened [a PR](https://github.com/librespot-org/librespot-java/pull/615) regarding the fixes.

**Comment by devgianlu** [comment]
I have published [v1.6.3](https://github.com/librespot-org/librespot-java/releases/tag/v1.6.3)

**Comment by wojked** [comment]
Thank you so much!

**Comment by maxwen** [comment]
Thanks a lot for fixing this so fast
