### ISSUE TITLE
EOFException when trying to connect

### ISSUE THREAD

**Issue by werwolf2303** [librespot-org/librespot-java#681]
**Describe the bug**
When trying to connect to Spotify with librespot-java (player) a exception is thrown.

**To Reproduce**
1. Feed username and password
2. Make connection

**Expected behavior**
Player loads uri and plays

**Screenshots/Stracktraces/Logs**
2023-06-21 15:13:52,548 DEBUG TimeProvider:90 - Loaded time offset from NTP: 211ms
2023-06-21 15:13:53,232 INFO  ApResolver:99 - Loaded aps into pool: {accesspoint=[ap-gew4.spotify.com:4070, ap-gew4.spotify.com:443, ap-gew4.spotify.com:80, ap-gae2.spotify.com:4070, ap-gew1.spotify.com:443, ap-gue1.spotify.com:80], dealer=[gew4-dealer.spotify.com:443, gae2-dealer.spotify.com:443, gew1-dealer.spotify.com:443, gue1-dealer.spotify.com:443], spclient=[gew4-spclient.spotify.com:443, gae2-spclient.spotify.com:443, gew1-spclient.spotify.com:443, gue1-spclient.spotify.com:443]}
2023-06-21 15:13:53,357 INFO  Session:140 - Created new session! {deviceId: 13cd3839417f29276c23fb3bed0e10c411f62654, ap: ap-gue1.spotify.com:80, proxy: false} 
java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readFully(DataInputStream.java:169)
	at xyz.gianlu.librespot.core.Session.connect(Session.java:315)
	at xyz.gianlu.librespot.core.Session.access$500(Session.java:77)
	at xyz.gianlu.librespot.core.Session$Builder.create(Session.java:1056)
	at org.example.Main.main(Main.java:40)

**Version/Commit**
1.6.3

**Comment by werwolf2303** [comment]
Please reply its important for the project SpotifyXP, thanks
