### ISSUE TITLE
Audio Key Error, librespot won't play anymore

### ISSUE THREAD

**Issue by praul** [librespot-org/librespot-java#694]
**Describe the bug**
Suddenly librespot won't play anymore. Running 1.63 in alpine java (docker) with pipe backend

**Screenshots/Stracktraces/Logs**
```
2023-08-07 09:32:43,872 ERROR AudioKeyManager:128 - Audio key error, code: 1
soundsystem-librespot-1   | 2023-08-07 09:32:43,960 ERROR AudioKeyManager:128 - Audio key error, code: 1
soundsystem-librespot-1   | 2023-08-07 09:32:44,664 ERROR AudioKeyManager:128 - Audio key error, code: 1
soundsystem-librespot-1   | 2023-08-07 09:32:44,747 ERROR AudioKeyManager:128 - Audio key error, code: 1
soundsystem-librespot-1   | 2023-08-07 09:32:44,750 ERROR Player:387 - Failed loading track.
soundsystem-librespot-1   | xyz.gianlu.librespot.audio.AudioKeyManager$AesKeyException: Failed fetching audio key! {gid: 72EDC23D86A749AB9AE30EAE1B38E60E, fileId: 156F7208C8C103C828B2D6DD4DA1A497223261CB}
soundsystem-librespot-1   |     at xyz.gianlu.librespot.audio.AudioKeyManager.getAudioKey(AudioKeyManager.java:79) ~[librespot.jar:1.6.3]
soundsystem-librespot-1   |     at xyz.gianlu.librespot.audio.AudioKeyManager.getAudioKey(AudioKeyManager.java:78) ~[librespot.jar:1.6.3]
soundsystem-librespot-1   |     at xyz.gianlu.librespot.audio.AudioKeyManager.getAudioKey(AudioKeyManager.java:55) ~[librespot.jar:1.6.3]
soundsystem-librespot-1   |     at xyz.gianlu.librespot.audio.cdn.CdnFeedHelper.loadTrack(CdnFeedHelper.java:55) ~[librespot.jar:1.6.3]
soundsystem-librespot-1   |     at xyz.gianlu.librespot.audio.cdn.CdnFeedHelper.loadTrack(CdnFeedHelper.java:67) ~[librespot.jar:1.6.3]
soundsystem-librespot-1   |     at xyz.gianlu.librespot.audio.PlayableContentFeeder.loadStream(PlayableContentFeeder.java:139) ~[librespot.jar:1.6.3]
soundsystem-librespot-1   |     at xyz.gianlu.librespot.audio.PlayableContentFeeder.loadTrack(PlayableContentFeeder.java:166) ~[librespot.jar:1.6.3]
soundsystem-librespot-1   |     at xyz.gianlu.librespot.audio.PlayableContentFeeder.loadTrack(PlayableContentFeeder.java:116) ~[librespot.jar:1.6.3]
soundsystem-librespot-1   |     at xyz.gianlu.librespot.audio.PlayableContentFeeder.load(PlayableContentFeeder.java:86) ~[librespot.jar:1.6.3]
soundsystem-librespot-1   |     at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.load(PlayerQueueEntry.java:115) ~[librespot.jar:1.6.3]
soundsystem-librespot-1   |     at xyz.gianlu.librespot.player.playback.PlayerQueueEntry.run(PlayerQueueEntry.java:276) [librespot.jar:1.6.3]
soundsystem-librespot-1   |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
soundsystem-librespot-1   |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
soundsystem-librespot-1   |     at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

```
**Version/Commit**
1.63, alpine java in docker

**Comment by praul** [comment]
... it works again. Maybe temporary hickup?
