### ISSUE TITLE
Exceptions since 0.4.0

### ISSUE THREAD

**Issue by loeffelpan** [librespot-org/librespot-java#73]
I get several exceptions in different situations.
These are two the logs i found (got this multiple times).
Seems to be related to CND. With this setting to false there are no issues.
`# Use CDN to download tracks (faster)
player.useCdn=false`

PS: I noticed that my spotify app is closing/hiding the whole player (inside the app) for a short time during connecting to Librespot. I don't know if this is related to Librespot or to the last update of the spotify app.

```
2019-04-05 16:47:19 DEBUG Player:357 - Loading context, uri: spotify:album:3ZbWbwXloEnASgkeUyPDLg
Exception in thread "handle-packet-27046947" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at xyz.gianlu.librespot.player.Player$StateWrapper.update(Player.java:603)
	at xyz.gianlu.librespot.player.Player.updatedTracks(Player.java:268)
	at xyz.gianlu.librespot.player.Player.handleLoad(Player.java:359)
	at xyz.gianlu.librespot.player.Player.handleFrame(Player.java:101)
	at xyz.gianlu.librespot.player.Player.frame(Player.java:192)
	at xyz.gianlu.librespot.spirc.SpotifyIrc$SpircListener.event(SpotifyIrc.java:198)
	at xyz.gianlu.librespot.mercury.MercuryClient$InternalSubListener.dispatch(MercuryClient.java:256)
	at xyz.gianlu.librespot.mercury.MercuryClient.handle(MercuryClient.java:173)
	at xyz.gianlu.librespot.core.PacketsManager$Looper.lambda$run$0(PacketsManager.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

```
2019-04-05 16:51:36 TRACE Player:191 - Frame has context_player_state: {"endpoint":"skip_next","options":{},"logging_params":{"command_initiated_time":1554475896464,"command_received_time":1554475896499}}
Exception in thread "handle-packet-24299298" java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4454)
	at xyz.gianlu.librespot.common.proto.Spirc$State$Builder.getTrack(Spirc.java:9795)
	at xyz.gianlu.librespot.player.tracks.PlaylistProvider.getNextTrackIndex(PlaylistProvider.java:119)
	at xyz.gianlu.librespot.player.Player.handleNext(Player.java:422)
	at xyz.gianlu.librespot.player.Player.handleFrame(Player.java:120)
	at xyz.gianlu.librespot.player.Player.frame(Player.java:192)
	at xyz.gianlu.librespot.spirc.SpotifyIrc$SpircListener.event(SpotifyIrc.java:198)
	at xyz.gianlu.librespot.mercury.MercuryClient$InternalSubListener.dispatch(MercuryClient.java:256)
	at xyz.gianlu.librespot.mercury.MercuryClient.handle(MercuryClient.java:173)
	at xyz.gianlu.librespot.core.PacketsManager$Looper.lambda$run$0(PacketsManager.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by devgianlu** [comment]
Apparently the client doesn't always fetch the pages for you. That should fix it.

**Comment by loeffelpan** [comment]
Exceptions are gone. Thanks.
Had some mysterious trouble. But after restarting everything is fine for now.
I'll make another issue if I can catch this again.
