### ISSUE TITLE
Queing impossible since 0.4.0

### ISSUE THREAD

**Issue by loeffelpan** [librespot-org/librespot-java#75]
Librespot throws exceptions when I try to queue a song.

```
Exception in thread "handle-packet-2196780" java.lang.IllegalArgumentException: Unknown endpoint for set_queue
        at xyz.gianlu.librespot.player.remote.Remote3Frame$Endpoint.opt(Remote3Frame.java:89)
        at xyz.gianlu.librespot.player.remote.Remote3Frame.<init>(Remote3Frame.java:52)
        at xyz.gianlu.librespot.player.Player.frame(Player.java:197)
        at xyz.gianlu.librespot.spirc.SpotifyIrc$SpircListener.event(SpotifyIrc.java:199)
        at xyz.gianlu.librespot.mercury.MercuryClient$InternalSubListener.dispatch(MercuryClient.java:252)
        at xyz.gianlu.librespot.mercury.MercuryClient.handle(MercuryClient.java:171)
        at xyz.gianlu.librespot.core.PacketsManager$Looper.lambda$run$0(PacketsManager.java:64)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by loeffelpan** [comment]
Thanks. But not fixed at all.
Now I got this:

```
2019-04-08 20:47:28 FATAL SpotifyIrc:201 - Couldn't create frame!
com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:86)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readRawBytes(CodedInputStream.java:1293)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readBytes(CodedInputStream.java:947)
	at xyz.gianlu.librespot.common.proto.Spirc$Frame.<init>(Spirc.java:1854)
	at xyz.gianlu.librespot.common.proto.Spirc$Frame.<init>(Spirc.java:1661)
	at xyz.gianlu.librespot.common.proto.Spirc$Frame$1.parsePartialFrom(Spirc.java:1688)
	at xyz.gianlu.librespot.common.proto.Spirc$Frame$1.parsePartialFrom(Spirc.java:1682)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:163)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:197)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:214)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at xyz.gianlu.librespot.common.proto.Spirc$Frame.parseFrom(Spirc.java:1932)
	at xyz.gianlu.librespot.spirc.SpotifyIrc$SpircListener.event(SpotifyIrc.java:189)
	at xyz.gianlu.librespot.mercury.MercuryClient$InternalSubListener.dispatch(MercuryClient.java:252)
	at xyz.gianlu.librespot.mercury.MercuryClient.handle(MercuryClient.java:171)
	at xyz.gianlu.librespot.core.PacketsManager$Looper.lambda$run$0(PacketsManager.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by devgianlu** [comment]
I think that wasn't related. Try again with current master.

**Comment by loeffelpan** [comment]
Kind of weired! 😀 
This must have been related. Was exactly when i tried to queue some songs.

And I don't know if this is related, but with current master I got this:
```
2019-04-09 19:09:44 TRACE MercuryClient:144 - Handling packet, cmd: MercuryEvent, seq: 4062023663027748864, flags: 1, parts: 2
Exception in thread "handle-packet-5468438" java.lang.IllegalStateException: InputStream#read(byte[]) returned invalid result: 0
The InputStream implementation is buggy.
	at com.google.protobuf.CodedInputStream$StreamDecoder.tryRefillBuffer(CodedInputStream.java:2848)
	at com.google.protobuf.CodedInputStream$StreamDecoder.isAtEnd(CodedInputStream.java:2762)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readTag(CodedInputStream.java:2109)
	at xyz.gianlu.librespot.common.proto.Spirc$Frame.<init>(Spirc.java:1750)
	at xyz.gianlu.librespot.common.proto.Spirc$Frame.<init>(Spirc.java:1661)
	at xyz.gianlu.librespot.common.proto.Spirc$Frame$1.parsePartialFrom(Spirc.java:1688)
	at xyz.gianlu.librespot.common.proto.Spirc$Frame$1.parsePartialFrom(Spirc.java:1682)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:221)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:239)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:244)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at com.google.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:311)
	at xyz.gianlu.librespot.common.proto.Spirc$Frame.parseFrom(Spirc.java:1945)
	at xyz.gianlu.librespot.spirc.SpotifyIrc$SpircListener.event(SpotifyIrc.java:189)
	at xyz.gianlu.librespot.mercury.MercuryClient$InternalSubListener.dispatch(MercuryClient.java:252)
	at xyz.gianlu.librespot.mercury.MercuryClient.handle(MercuryClient.java:171)
	at xyz.gianlu.librespot.core.PacketsManager$Looper.lambda$run$0(PacketsManager.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by devgianlu** [comment]
There was an issue with the stream implementation. Should work now.

**Comment by loeffelpan** [comment]
Works. Thanks.
