### ISSUE TITLE
"Preloaded track loading failed" (Couldn't find a suitable mixer) warn on every track

### ISSUE THREAD

**Issue by elganzua124** [librespot-org/librespot-java#81]
Hi, I'm experiencing random disconnections once a while. Watching the logs I noticed a strange behavior every time a new track start playing. When the music stops and the client is disconnected, it cannot reconnect. Here is the log:

```
Apr 16 17:45:11 raspberrypi java[3180]: 2019-04-16 17:45:11 INFO  TrackHandler:80 - Loaded track, name: 'Cactus', artists: 'Gustavo Cerati', gid: 3AF3D86A80CE4B9CB57A81A17987D1C2
Apr 16 17:45:11 raspberrypi java[3180]: 2019-04-16 17:45:11 WARN  Player:344 - Preloaded track loading failed!
Apr 16 17:45:11 raspberrypi java[3180]: xyz.gianlu.librespot.player.LinesHolder$MixerException: Couldn't find a suitable mixer, line: interface SourceDataLine supporting format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian, available: [BossDAC [plughw:0,0], version 4.14.98-v7+, Port BossDAC [hw:0], version 4.14.98-v7+]
Apr 16 17:45:11 raspberrypi java[3180]:         at xyz.gianlu.librespot.player.LinesHolder.findSupportingMixersFor(LinesHolder.java:32)
Apr 16 17:45:11 raspberrypi java[3180]:         at xyz.gianlu.librespot.player.LinesHolder.getLineFor(LinesHolder.java:103)
Apr 16 17:45:11 raspberrypi java[3180]:         at xyz.gianlu.librespot.player.codecs.VorbisCodec.initializeSound(VorbisCodec.java:124)
Apr 16 17:45:11 raspberrypi java[3180]:         at xyz.gianlu.librespot.player.codecs.VorbisCodec.<init>(VorbisCodec.java:52)
Apr 16 17:45:11 raspberrypi java[3180]:         at xyz.gianlu.librespot.player.PlayerRunner.<init>(PlayerRunner.java:28)
Apr 16 17:45:11 raspberrypi java[3180]:         at xyz.gianlu.librespot.player.TrackHandler.createRunner(TrackHandler.java:55)
Apr 16 17:45:11 raspberrypi java[3180]:         at xyz.gianlu.librespot.player.TrackHandler.loadRunner(TrackHandler.java:88)
Apr 16 17:45:11 raspberrypi java[3180]:         at xyz.gianlu.librespot.player.TrackHandler.load(TrackHandler.java:82)
Apr 16 17:45:11 raspberrypi java[3180]:         at xyz.gianlu.librespot.player.TrackHandler.access$600(TrackHandler.java:29)
Apr 16 17:45:11 raspberrypi java[3180]:         at xyz.gianlu.librespot.player.TrackHandler$Looper.run(TrackHandler.java:230)
Apr 16 17:45:11 raspberrypi java[3180]:         at java.lang.Thread.run(Thread.java:748)
```

**Comment by devgianlu** [comment]
I don't see any trace of disconnects or hickups. The mixer thing seems just a warning as I suppose the playback is working fine. Are you running the latest master?

**Comment by elganzua124** [comment]
> Are you running the latest master?

Yes I am. The disconnects happens once a while, I will try to catch the next one and post here an updated log.

**Comment by devgianlu** [comment]
Search for a similar issue when you find the connection issue (try searching for the exception name), I'll reopen that. I'll leave this for an eventual fix of the warning.

**Comment by elganzua124** [comment]
Ok, I will do that. Thanks.

**Comment by devgianlu** [comment]
Could you provide a full log of the warning issue?

**Comment by elganzua124** [comment]
Sorry for the delay, I'll try to gather a full log.

**Comment by devgianlu** [comment]
I suppose this is fixed in the latest master.
