### ISSUE TITLE
ApiClient$StatusCodeException: 400 when use getMetadata4Album

### ISSUE THREAD

**Issue by thedtvn** [librespot-org/librespot-java#835]
**Describe the bug**
bug appear when get Track meta

**To Reproduce**
`session.api().getMetadata4Track(TrackId.fromUri("Track id to here"))`

**Expected behavior**
work without err

**Screenshots/Stracktraces/Logs**
```
xyz.gianlu.librespot.dealer.ApiClient$StatusCodeException: 400: 
    at xyz.gianlu.librespot.dealer.ApiClient$StatusCodeException.checkStatus(ApiClient.java:366)
    at xyz.gianlu.librespot.dealer.ApiClient$StatusCodeException.access$000(ApiClient.java:357)
    at xyz.gianlu.librespot.dealer.ApiClient.clientToken(ApiClient.java:345)
    at xyz.gianlu.librespot.dealer.ApiClient.buildRequest(ApiClient.java:79)
    at xyz.gianlu.librespot.dealer.ApiClient.send(ApiClient.java:114)
    at xyz.gianlu.librespot.dealer.ApiClient.send(ApiClient.java:131)
    at xyz.gianlu.librespot.dealer.ApiClient.getMetadata4Album(ApiClient.java:168)
    at org.librespotapis.Main.loadmeta(Main.java:265)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Version/Commit**
xyz.gianlu.librespot:librespot-lib:1.6.3

**Comment by ShaikaJar** [comment]
I also encountered this.
Did Spotify change the api?

**Comment by Lustyn** [comment]
Likely cause: Your classpath is incorrect.

[Version.java](https://github.com/librespot-org/librespot-java/blob/dev/lib/src/main/java/xyz/gianlu/librespot/Version.java) returns "versionString" as the current version of librespot-java, and if the package does not find a version it will populate `?.?.?` which I'm guessing Spotify recently added validation against. I don't fully understand what is happening here.

To fix it, you should try switching your dependency from `librespot-lib` -> `librespot-player`. For me this made the version number populate correctly and the library began functioning again. You may also run into issues depending on how your Java build is packaged and ran. To validate that you don't encounter the issue, check `Version.versionString()` at runtime to see if it is set correctly.

**Comment by devgianlu** [comment]
I can confirm what @Lustyn is saying, they recently added a check on the version string probably to parse it for their own stuff.

I had to fix this in go-librespot too: https://github.com/devgianlu/go-librespot/commit/92ade8e23f0ccabf77594f7d470ed104cc04c306
