### ISSUE TITLE
Exceptions on add to queue

### ISSUE THREAD

**Issue by loeffelpan** [librespot-org/librespot-java#88]
I got some exceptions on adding some songs to the queue.
After that another exception concerning mixers come up and playback is running, but silent.

```
2019-05-17 15:40:57 TRACE SpotifyIrc:195 - Handling frame, type: kMessageTypeReplace, ident: 4a53069b194ff69d2264022a7344e4829356854c
2019-05-17 15:40:57 TRACE Player:204 - Frame has context_player_state: {"endpoint":"add_to_queue","track":{"uri":"spotify:track:1stlWpeFGKGsZGenc4TD6k","metadata":{"album_uri":"spotify:album:66eeczRKm8U4UPr0sQdYWQ","artist_uri":"spotify:artist:1ZHJdXXtKnmUh2qRN4LmbS","is_queued":"true"}},"options":{},"logging_params":{"command_received_time":1558100457011}}
Exception in thread "handle-packet-13345669" java.lang.IllegalArgumentException: Unknown endpoint for add_to_queue
	at xyz.gianlu.librespot.player.remote.Remote3Frame$Endpoint.opt(Remote3Frame.java:85)
	at xyz.gianlu.librespot.player.remote.Remote3Frame.<init>(Remote3Frame.java:53)
	at xyz.gianlu.librespot.player.Player.frame(Player.java:205)
	at xyz.gianlu.librespot.spirc.SpotifyIrc$SpircListener.event(SpotifyIrc.java:199)
	at xyz.gianlu.librespot.mercury.MercuryClient$InternalSubListener.dispatch(MercuryClient.java:287)
	at xyz.gianlu.librespot.mercury.MercuryClient.handle(MercuryClient.java:171)
	at xyz.gianlu.librespot.core.PacketsManager$Looper.lambda$run$0(PacketsManager.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-05-17 15:41:01 TRACE CdnManager:264 - Chunk 8/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:41:06 TRACE MercuryClient:144 - Handling packet, cmd: MercuryEvent, seq: -8018888934463373312, flags: 1, parts: 2
2019-05-17 15:41:06 TRACE SpotifyIrc:195 - Handling frame, type: kMessageTypeNotify, ident: 4a53069b194ff69d2264022a7344e4829356854c
2019-05-17 15:41:08 TRACE CdnManager:264 - Chunk 9/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:41:15 TRACE CdnManager:264 - Chunk 10/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:41:22 TRACE CdnManager:264 - Chunk 11/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:41:29 TRACE CdnManager:264 - Chunk 12/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:41:36 TRACE CdnManager:264 - Chunk 13/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:41:43 TRACE CdnManager:264 - Chunk 14/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:41:50 TRACE CdnManager:264 - Chunk 15/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:41:57 TRACE CdnManager:264 - Chunk 16/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:42:04 TRACE CdnManager:264 - Chunk 17/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:42:11 TRACE CdnManager:264 - Chunk 18/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:42:15 TRACE MercuryClient:144 - Handling packet, cmd: MercuryEvent, seq: 412412517927616512, flags: 1, parts: 2
2019-05-17 15:42:15 TRACE MercuryClient:144 - Handling packet, cmd: MercuryEvent, seq: 484470111965544448, flags: 1, parts: 2
2019-05-17 15:42:15 WARN  MercuryClient:177 - Couldn't dispatch Mercury event {seq: 412412517927616512, uri: hm://playlist/user/3va30l8lqcu4tl1rj2xdks9bz/rootlist, code: 200, payload: 0A2F73706F746966793A757365723A33766133306C386C71637534746C31726A3278646B7339627A3A726F6F746C6973741218000000B7FDCDE01A1F2178A1D40AC2E02883505F1EA953AF}
2019-05-17 15:42:15 WARN  MercuryClient:177 - Couldn't dispatch Mercury event {seq: 484470111965544448, uri: hm://playlist/v2/user/3va30l8lqcu4tl1rj2xdks9bz/rootlist, code: 200, payload: 0A2F73706F746966793A757365723A33766133306C386C71637534746C31726A3278646B7339627A3A726F6F746C6973741218000000B7FDCDE01A1F2178A1D40AC2E02883505F1EA953AF}
2019-05-17 15:42:18 TRACE CdnManager:264 - Chunk 19/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:42:25 TRACE CdnManager:264 - Chunk 20/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:42:30 DEBUG TimeProvider:20 - Corrected time offset, delta: 0s
2019-05-17 15:42:30 TRACE Session:741 - Handled Ping {payload: 5CDEBA46}
2019-05-17 15:42:30 TRACE Session:747 - Handled PongAck {payload: 5CDEBA46}
2019-05-17 15:42:32 TRACE CdnManager:264 - Chunk 21/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:42:40 TRACE CdnManager:264 - Chunk 22/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:42:47 TRACE CdnManager:264 - Chunk 23/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:42:54 TRACE CdnManager:264 - Chunk 24/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:43:01 TRACE CdnManager:264 - Chunk 25/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:43:08 TRACE CdnManager:264 - Chunk 26/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:43:15 TRACE CdnManager:264 - Chunk 27/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:43:22 TRACE CdnManager:264 - Chunk 28/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:43:29 TRACE CdnManager:264 - Chunk 29/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:43:36 TRACE CdnManager:264 - Chunk 30/31 completed, cdn: audio4-ak.spotify.com.edgesuite.net, cached: false, stream: {fileId: 6E10F2BC8CCAF54542DE6B555EEBD9A2FB9BDC44}
2019-05-17 15:43:49 TRACE Player:379 - Started next track preload, gid: 27A220075F0D4BE2B416BCB14AF6C4ED
2019-05-17 15:43:49 TRACE MercuryClient:102 - Send Mercury request, seq: 615, uri: hm://metadata/4/track/27a220075f0d4be2b416bcb14af6c4ed, method: GET
2019-05-17 15:43:49 TRACE MercuryClient:144 - Handling packet, cmd: MercuryReq, seq: 615, flags: 1, parts: 2
2019-05-17 15:43:49 DEBUG CdnManager:97 - Fetched CDN url for 73513FCA22AA0641D47C3222E15CAF3ECFC59DAA: http://audio4-fa.scdn.co/audio/73513fca22aa0641d47c3222e15caf3ecfc59daa?1558104229_TxBbk_juF2mVlCr_W95c2KCraX_OuHL6mrHmtjFmWws=
2019-05-17 15:43:49 TRACE CdnManager:264 - Chunk 0/32 completed, cdn: audio4-fa.scdn.co, cached: false, stream: {fileId: 73513FCA22AA0641D47C3222E15CAF3ECFC59DAA}
2019-05-17 15:43:50 TRACE NormalizationData:29 - Loaded normalization data, track_gain: -6.29, track_peak: 1.04, album_gain: -7.21, album_peak: 1.16
2019-05-17 15:43:50 INFO  TrackHandler:80 - Loaded track, name: 'Irgendwas bleibt (aus " Sing meinen Song, Vol. 4 " )', artists: 'Mark Forster', gid: 27A220075F0D4BE2B416BCB14AF6C4ED
2019-05-17 15:43:50 TRACE CdnManager:264 - Chunk 0/32 completed, cdn: audio4-fa.scdn.co, cached: true, stream: {fileId: 73513FCA22AA0641D47C3222E15CAF3ECFC59DAA}
2019-05-17 15:43:50 TRACE CdnManager:264 - Chunk 1/32 completed, cdn: audio4-fa.scdn.co, cached: false, stream: {fileId: 73513FCA22AA0641D47C3222E15CAF3ECFC59DAA}
2019-05-17 15:43:50 INFO  LinesHolder:106 - Mixer for playback 'Device [default]', maxLines: 1
2019-05-17 15:43:50 TRACE CdnManager:264 - Chunk 3/32 completed, cdn: audio4-fa.scdn.co, cached: false, stream: {fileId: 73513FCA22AA0641D47C3222E15CAF3ECFC59DAA}
2019-05-17 15:43:50 DEBUG LinesHolder:77 - Mixer 'Device [default]' has 1 lines in use, max: 1
2019-05-17 15:43:50 TRACE PlayerRunner:37 - Player ready for playback, codec: VORBIS, fileId: {fileId: 73513FCA22AA0641D47C3222E15CAF3ECFC59DAA}
2019-05-17 15:43:50 TRACE Player:333 - Preloaded track is ready.
2019-05-17 15:43:50 TRACE CdnManager:264 - Chunk 2/32 completed, cdn: audio4-fa.scdn.co, cached: false, stream: {fileId: 73513FCA22AA0641D47C3222E15CAF3ECFC59DAA}
2019-05-17 15:43:59 TRACE MercuryClient:144 - Handling packet, cmd: MercuryEvent, seq: 1349724190374100992, flags: 1, parts: 2
2019-05-17 15:43:59 TRACE SpotifyIrc:195 - Handling frame, type: kMessageTypeLoad, ident: 4a53069b194ff69d2264022a7344e4829356854c
2019-05-17 15:43:59 TRACE Player:204 - Frame has context_player_state: {"endpoint":"play","context":{"uri":"spotify:user:spotify:playlist:37i9dQZF1DX52oZiy8mdjZ","url":"context://spotify:user:spotify:playlist:37i9dQZF1DX52oZiy8mdjZ","metadata":{"context_description":"Sing meinen Song","context_owner":"spotify","filtering.predicate":"is_available==true&&(is_banned==false&&is_artist_banned==false)","format_list_type":"editorial","image_url":"fbc0498c5d26e57dd58f3591838a3b910e9f158a","status":"PUBLISHED","uri":"spotify:user:spotify:playlist:37i9dQZF1DX52oZiy8mdjZ","zelda.context_uri":"spotify:user:spotify:playlist:37i9dQZF1DX52oZiy8mdjZ"},"pages":[{"tracks":[{"uri":"spotify:track:2GyhgB6ErYddBYb62bP2gf","uid":"30","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:00bLZk9La3CFNOhcwqAdKP","uid":"31","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:08U06Ju60u0RiSQDkWUrYs","uid":"32","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:3HEfc2JwFeVjEK0VRg3pqU","uid":"33","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:06RHkLcZBBnMoqgfuLX3d9","uid":"34","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:0eoWY6a8mRN3BJKCSqQWzJ","uid":"35","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:1yBGUG74gnxDT5ZvLDDC66","uid":"36","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:2bp9dlyzNPVdTV4qfFkDFP","uid":"37","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:5b1QdBB0gfVa9DZcbAuOpX","uid":"38","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:13JeBvwHxgkNVlCsR5r4oy","uid":"39","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:1PjSSitPSV5qivjsRW70CD","uid":"3130","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:2WVwL2JOcHKapuz0Kd5aZ8","uid":"3131","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:1cMN6Yb9jbr9O8ozhu1Uzr","uid":"3132","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:0np8H6HwsUbMEA94zrvq70","uid":"3133","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:53B01LhfOa3NFgyQU5rbDY","uid":"3134","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:1Y5iegz0O9wl3OrmAsWr6R","uid":"3135","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:553HS9LgCttNjrnWrP1aLW","uid":"3136","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:52P8fpTPMgSMg5HFpPYj3u","uid":"3137","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:7wjRIJzA4ZssoBqHhqHjQp","uid":"3138","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:24tUJHIssKQstRKs2u57Ah","uid":"3139","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:5qHNicI0ubQEyCzK5cvOc9","uid":"3230","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:4JNzaoeonHixvOEDw1yx4H","uid":"3231","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:5wrYz7kZnGFrdoeNNMYWDp","uid":"3232","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:5j0zZR32cd2aqmoFBbQdaG","uid":"3233","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:5PvwOEp0CxpcvpxY9TmBfo","uid":"3234","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:6WxjWfU2dxnetFleXYGdNU","uid":"3235","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:4ofUu6bhIMXCJ9jBWWQI8p","uid":"3236","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:1tEWpmVczpj2jZQiEJEqa3","uid":"3237","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:19suBFRE9ZGN7hgA40AZHi","uid":"3238","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:6GAhZHB679emFeysbHwZNJ","uid":"3239","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:59TUbcpEQYnvVq9WwhLX5C","uid":"3330","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:0PEwtu9zCmk7OBg2zr1PmT","uid":"3331","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:6MN5S2HxIDimEMNEyCPYr7","uid":"3332","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:6W8m04qe4KlYYov4sgdZrv","uid":"3333","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:3CtJFUILWy1f5P1cg3ibe1","uid":"3334","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:1ykg6jjGxnKINBzMAKA08j","uid":"3335","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:5B3E3D94NiMycBknYtWZIz","uid":"3336","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:29WQDRPtCykE8yiNJbYLSY","uid":"3337","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:6WHWbDIRa2hb3yRyMsJNJK","uid":"3338","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:2cxmWuA3DkHbk79ykTCBpr","uid":"3339","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:2MBfWWdUYOc7GwiiMkkDeD","uid":"3430","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:6eoGmvchNx09d2AIlF53ln","uid":"3431","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:32C3kHucMcxYbV5OuWiyE8","uid":"3432","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:2J4LeXqA85zwFzs4KVQOnP","uid":"3433","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:2SuuioSK8HAzWSneSXpvA7","uid":"3434","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:4ScFINDsJS9C67ECTNiLAa","uid":"3435","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:1JobaLz7npelV1VJF4muxl","uid":"3436","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:6GAR9artNqCDtTxteXGdFS","uid":"3437","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:5cjGdAUEVMVOWIWC9gYuRD","uid":"3438","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:1Or38xKMBuILHWWe6zqL8O","uid":"3439","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:5z7PZKHsl1uLVYXGyuL0Zc","uid":"3530","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:4GZHSX4w0o6XOCTCZH5fAs","uid":"3531","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:1bwpoQR5QmO0lYesoMYu8n","uid":"3532","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:6o079fmNUbVujLqBxA4NQe","uid":"3533","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}},{"uri":"spotify:track:2UKedLXqJze7BY8FMfzqP4","uid":"3534","metadata":{"collection.artist.is_banned":"false","collection.is_banned":"false"}}]}],"restrictions":{}},"play_origin":{"feature_identifier":"playlist","feature_version":"8.5.5.715","view_uri":"spotify:user:spotify:playlist:37i9dQZF1DX52oZiy8mdjZ","referrer_identifier":"collection"},"options":{"skip_to":{"track_uid":"30"},"player_options_override":{},"suppressions":{},"prefetch_level":"none","audio_stream":"default","session_id":"6FBwGbXER6d8LZd4DfGuFj","license":"premium"},"play_options":{"reason":"interactive","operation":"replace","trigger":"immediately"},"logging_params":{}}
2019-05-17 15:43:59 DEBUG Player:432 - Loading context, uri: spotify:user:spotify:playlist:37i9dQZF1DX52oZiy8mdjZ
2019-05-17 15:43:59 TRACE Player:365 - End of track. Proceeding with next.
2019-05-17 15:43:59 DEBUG LinesHolder:114 - Removed closed line, remaining: 0
2019-05-17 15:43:59 DEBUG LinesHolder:71 - Got first line from mixer 'Device [default]'
Exception in thread "player-runner-27751803" java.lang.IndexOutOfBoundsException: Index: 11, Size: 8
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at xyz.gianlu.librespot.common.proto.Spirc$State$Builder.getTrack(Spirc.java:9795)
	at xyz.gianlu.librespot.player.tracks.PlaylistProvider.getNextTrackIndex(PlaylistProvider.java:128)
	at xyz.gianlu.librespot.player.Player.handleNext(Player.java:496)
	at xyz.gianlu.librespot.player.Player.endOfTrack(Player.java:366)
	at xyz.gianlu.librespot.player.TrackHandler.endOfTrack(TrackHandler.java:134)
	at xyz.gianlu.librespot.player.codecs.Codec.run(Codec.java:69)
2019-05-17 15:43:59 TRACE SpotifyIrc:105 - Send frame, type: kMessageTypeNotify
	at xyz.gianlu.librespot.player.PlayerRunner.run(PlayerRunner.java:42)
	at java.lang.Thread.run(Thread.java:748)
2019-05-17 15:43:59 TRACE MercuryClient:102 - Send Mercury request, seq: 616, uri: hm://metadata/4/track/5843bb767479417b8e723738dd40f3cf, method: GET
2019-05-17 15:43:59 TRACE LinesHolder:165 - Line opened for mixer 'Device [default]'.
2019-05-17 15:43:59 TRACE MercuryClient:102 - Send Mercury request, seq: 617, uri: hm://remote/3/user/3va30l8lqcu4tl1rj2xdks9bz/, method: POST
2019-05-17 15:43:59 TRACE MercuryClient:144 - Handling packet, cmd: MercuryReq, seq: 616, flags: 1, parts: 2
2019-05-17 15:43:59 TRACE MercuryClient:144 - Handling packet, cmd: MercuryReq, seq: 617, flags: 1, parts: 1
2019-05-17 15:43:59 TRACE SpotifyIrc:119 - Frame sent successfully, type: kMessageTypeNotify
```

**Comment by devgianlu** [comment]
Looks like they changed the endpoint to add a songs to the queue. Should be an easy fix.

**Comment by devgianlu** [comment]
@loeffelpan Which version of Spotify are you using? I can't reproduce.

**Comment by loeffelpan** [comment]
Last compiled on 3rd of May. This must be your 0.5.2 release.
Reproducable for me.

**Comment by devgianlu** [comment]
I meant the official client. I am on `1.1.6.113.gb388fe17`.

**Comment by loeffelpan** [comment]
Tested this with iOS app 8.5.5.715.
Spotify client on windows maybe work. Didn‘t tested yet.

**Comment by devgianlu** [comment]
No problem with Android app 8.5.6.673.

**Comment by loeffelpan** [comment]
Just did the update to 8.5.6.630 in both iOS devices.
Same as before 😞

**Comment by devgianlu** [comment]
I should be able to implement this just with the stacktrace you provided, but I'll do this with #91 as right now the code is a mess.

**Comment by loeffelpan** [comment]
Thanks.
I‘ll wait for it.

**Comment by devgianlu** [comment]
Should be fixed now. Let me know if it works.

**Comment by loeffelpan** [comment]
Just tested. Working again. Thanks.
But now I got some other issues, when selecting a track. Please take a look at #93 .
And unfotunately shuffling issues reappeared for me (...).
