### ISSUE TITLE
Playing from playlist fails if the playlist contains locally added tracks

### ISSUE THREAD

**Issue by Iscle** [librespot-org/librespot-java#92]
**Describe the bug**
When trying to play any song from a playlist that contains locally added songs (a song not available on spotify by default), it will not pass any audio to librespot-java and an IllegalArgumentException is thrown.

**To Reproduce**
Create a playlist and add some local songs to it, as well as spotify songs. Then, try to play them and send them to librespot-java.

**Expected behavior**
The song will start playing on the speaker.

**Screenshots/Stracktraces/Logs**
```
Exception in thread "handle-packet-2034787828" java.lang.IllegalArgumentException: Unknown uri: spotify:local:Wuki:Wukileaks+Secret+Stash:Pon+De+Time+%28Nitti+Gritti+Edit%29:152
	at xyz.gianlu.librespot.mercury.model.PlayableId.fromUri(PlayableId.java:16)
	at xyz.gianlu.librespot.player.remote.Remote3Track.id(Remote3Track.java:83)
	at xyz.gianlu.librespot.player.remote.Remote3Track.toTrackRef(Remote3Track.java:77)
	at xyz.gianlu.librespot.player.remote.Remote3Track.addToState(Remote3Track.java:55)
	at xyz.gianlu.librespot.player.Player$StateWrapper.updateContext(Player.java:771)
	at xyz.gianlu.librespot.player.Player.updateContext(Player.java:295)
	at xyz.gianlu.librespot.player.Player.handleLoad(Player.java:430)
	at xyz.gianlu.librespot.player.Player.handleFrame(Player.java:110)
	at xyz.gianlu.librespot.player.Player.frame(Player.java:206)
	at xyz.gianlu.librespot.spirc.SpotifyIrc$SpircListener.event(SpotifyIrc.java:199)
	at xyz.gianlu.librespot.mercury.MercuryClient$InternalSubListener.dispatch(MercuryClient.java:287)
	at xyz.gianlu.librespot.mercury.MercuryClient.handle(MercuryClient.java:171)
	at xyz.gianlu.librespot.core.PacketsManager$Looper.lambda$run$0(PacketsManager.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Version/Commit**
Latest version built from source (as of today)

**Comment by Iscle** [comment]
I've temporarily fixed on my build by adding this on line 771 on Player.java:
`if (track.uri.contains("spotify:local")) continue;`

**Comment by devgianlu** [comment]
I did not think that local songs would be passed to an external player. Your workaround should be fine and I'll use a similar one while we investigate how to implement this functionality.

**Comment by Iscle** [comment]
Well, my previous workarround didn't work very well. I now have a new workarround which always works, but it's not the best solution.

The trick is, in the PlayableId.java interface, in the fromUri function, add this else if statement:

```
        } else if (uri.contains("spotify:local")) {
            return TrackId.fromUri("spotify:track:7GhIk7Il098yCjg4BQjzvb"); // Return "Never gonna give you up"
        }
```

This will return a PlayableId from the song "Never Gonna Give You Up" if the song it's trying to play is an unplayable local song. Hope this helps a little bit more!

Thanks :)

**Comment by devgianlu** [comment]
Should be fixed now, but you may still experience some issues due to the fact that removing the track messes up the `options.skip_to.track_index`. I'll take care of this ASAP.

**Comment by devgianlu** [comment]
You can't play local tracks with Spotify Connect. Although this could be a pretty interesting feature, I'm closing this for now.

**Comment by Iscle** [comment]
> You can't play local tracks with Spotify Connect. Although this could be a pretty interesting feature, I'm closing this for now.

I know! To play them you would need to have the playlist downloaded (at least in Android), I was just pointing out the error :P

Thanks for fixing it!
