### ISSUE TITLE
mercury returns 404 for a specific music

### ISSUE THREAD

**Issue by crsmoro** [librespot-org/librespot-java#97]
**Describe the bug**
It gives me an exception when i try to play 'Next To You Part II (feat. Rvssian & DaVido) - Becky G' `spotify:track:00yinrzqPZKA2vbnwnn3hS`

**To Reproduce**
Select the music to play

**Expected behavior**
Play the music

**Screenshots/Stracktraces/Logs**
```
2019-05-31 21:30:12 TRACE MercuryClient:102 - Send Mercury request, seq: 98, uri: hm://metadata/4/track/4b0bf23789473a84fa07cc7629c658, method: GET
2019-05-31 21:30:12 TRACE MercuryClient:144 - Handling packet, cmd: MercuryReq, seq: 98, flags: 1, parts: 1
2019-05-31 21:30:12 FATAL Player:278 - Failed loading track, gid: 4B0BF23789473A84FA07CC7629C658
xyz.gianlu.librespot.mercury.MercuryClient$MercuryException: status: 404
        at xyz.gianlu.librespot.mercury.MercuryClient.sendSync(MercuryClient.java:90)
        at xyz.gianlu.librespot.player.feeders.BaseFeeder.loadTrack(BaseFeeder.java:73)
        at xyz.gianlu.librespot.player.feeders.BaseFeeder.load(BaseFeeder.java:67)
        at xyz.gianlu.librespot.player.TrackHandler.load(TrackHandler.java:65)
        at xyz.gianlu.librespot.player.TrackHandler.access$600(TrackHandler.java:29)
        at xyz.gianlu.librespot.player.TrackHandler$Looper.run(TrackHandler.java:230)
        at java.lang.Thread.run(Thread.java:748)
2019-05-31 21:30:12 TRACE SpotifyIrc:113 - Send frame, type: kMessageTypeNotify
2019-05-31 21:30:12 TRACE MercuryClient:102 - Send Mercury request, seq: 99, uri: hm://remote/3/user/1234567890/, method: POST
2019-05-31 21:30:12 TRACE MercuryClient:144 - Handling packet, cmd: MercuryReq, seq: 99, flags: 1, parts: 1
2019-05-31 21:30:12 TRACE SpotifyIrc:127 - Frame sent successfully, type: kMessageTypeNotify
```

**Version/Commit**
today's latest master (2479a4154df4b75e34368888327970369eb73e22)

**Comment by devgianlu** [comment]
I thought uris starting with `00` didn't exist. I should really refactor that code.
